CREATE  PROC USP_CBS_LoanDisbursement_Get_DepositAccountList
(
	@LOAN_NO VARCHAR(50)='',
	@BR_CODE VARCHAR(5),
	@GL_CODE varchar(10),
	@INPUT VARCHAR(200),
	@ROW_COUNT INT,
	@SKIP_COUNT INT,
	@TOTAL_COUNT INT = 0 OUTPUT
)
AS BEGIN

	DROP TABLE IF EXISTS #DT

	CREATE TABLE #DT(AC_NO VARCHAR(50), AC_NAME VARCHAR(500),AC_TYPE_SUB_TYPE_CODE VARCHAR(50), GL_CODE VARCHAR(20), BANK_GL_CODE VARCHAR(20), GL_NAME VARCHAR(500))
	IF @LOAN_NO='LOAN' -- FOR HO LOAN BRANCH AND EMPLOYEE BATCH PAYMENT SCREEN 
	BEGIN
		INSERT INTO #DT
		SELECT AC_NO CODE,AC_NAME [NAME],AG.AC_TYPE_SUB_TYPE_CODE,CHART.GL_CODE,CHART.BANK_GL_CODE,CHART.GL_NAME 
		FROM DEPOSIT_AC_MAST DAM WITH(NOLOCK)
		INNER JOIN AC_GROUP AG WITH(NOLOCK) ON DAM.AC_GROUP_CODE = AG.AC_GROUP_CODE
		INNER JOIN AC_GROUP_GL_MAP AS MAP WITH(NOLOCK) ON MAP.NAMED_AC_CODE='0301' AND MAP.AC_GROUP_CODE=AG.AC_GROUP_CODE
		INNER JOIN AC_CHART AS CHART WITH(NOLOCK) ON CHART.GL_CODE=MAP.GL_CODE 
		WHERE DAM.APPROVED = 'YES' AND BR_CODE =@BR_CODE AND AC_STATUS<>'03' AND (AC_TYPE_SUB_TYPE_CODE='0301' OR AC_TYPE_SUB_TYPE_CODE='0302')
			AND (AC_NO LIKE @INPUT OR AC_NAME LIKE @INPUT+'%')
	END
	ELSE
	BEGIN
		DECLARE @IS_ANY_DEPOSIT_ACCOUNT_ALLOWED_FOR_LOAN_DISBURSE BIT = (SELECT IS_ANY_DEPOSIT_ACCOUNT_ALLOWED_FOR_LOAN_DISBURSE FROM GLOBAL_SETUP)
		DECLARE @CUSTOMER_CODE VARCHAR(50)=''
		
		IF @IS_ANY_DEPOSIT_ACCOUNT_ALLOWED_FOR_LOAN_DISBURSE = 0
		BEGIN
			SELECT TOP 1 @CUSTOMER_CODE= AHHD.CUSTOMER_CODE
			FROM LOAN_MAST DAM WITH(NOLOCK)
			INNER JOIN(SELECT M.TRAN_ID,M.AC_NO,M.AC_GROUP_CODE,M.BR_CODE
							,ROW_NUMBER() OVER(PARTITION BY M.AC_NO ORDER BY M.TRAN_DATE DESC,M.TRAN_ID DESC) RN 
						FROM AC_HOLDER_MAST AS M WITH(NOLOCK)    
						WHERE  M.[STATUS]=1
					) AS AHHM ON AHHM.BR_CODE=DAM.BR_CODE AND AHHM.AC_NO=DAM.AC_NO  AND AHHM.RN=1    
			INNER JOIN (SELECT AC_HOLDER_MAST_ID,CUSTOMER_CODE,ROW_NUMBER() OVER(PARTITION BY AC_HOLDER_MAST_ID ORDER BY TRAN_ID DESC,IS_MASTER_AC_HOLDER DESC)RN 
							FROM AC_HOLDER_DETL AS D WITH(NOLOCK)   
						) AS AHHD ON AHHM.TRAN_ID=AHHD.AC_HOLDER_MAST_ID AND AHHD.RN=1   
						WHERE DAM.AC_NO= @LOAN_NO
		
			DROP TABLE IF EXISTS #DEP_AC
			SELECT DAM.AC_NO , DAM.AC_NAME INTO #DEP_AC
			FROM DEPOSIT_AC_MAST DAM WITH(NOLOCK)
			INNER JOIN(SELECT M.TRAN_ID,M.AC_NO,M.AC_GROUP_CODE,M.BR_CODE
							,ROW_NUMBER() OVER(PARTITION BY M.AC_NO ORDER BY M.TRAN_DATE DESC,M.TRAN_ID DESC) RN 
						FROM AC_HOLDER_MAST AS M WITH(NOLOCK)   
						WHERE  [STATUS]=1
					) AS AHHM ON AHHM.BR_CODE=DAM.BR_CODE AND AHHM.AC_NO=DAM.AC_NO  AND AHHM.RN=1    
			INNER JOIN (SELECT AC_HOLDER_MAST_ID,CUSTOMER_CODE,ROW_NUMBER() OVER(PARTITION BY AC_HOLDER_MAST_ID ORDER BY TRAN_ID DESC,IS_MASTER_AC_HOLDER DESC)RN 
							FROM AC_HOLDER_DETL AS D WITH(NOLOCK)   
						) AS AHHD ON AHHM.TRAN_ID=AHHD.AC_HOLDER_MAST_ID AND AHHD.RN=1   
						WHERE AHHD.CUSTOMER_CODE=@CUSTOMER_CODE
			
			INSERT INTO #DT
			SELECT  D.AC_NO CODE, D.AC_NAME [NAME],AG.AC_TYPE_SUB_TYPE_CODE,CHART.GL_CODE,CHART.BANK_GL_CODE,CHART.GL_NAME
			FROM DEPOSIT_AC_MAST DAM WITH(NOLOCK)
			INNER JOIN AC_GROUP AG WITH(NOLOCK) ON DAM.AC_GROUP_CODE = AG.AC_GROUP_CODE
			INNER JOIN AC_GROUP_GL_MAP AS MAP WITH(NOLOCK) ON MAP.NAMED_AC_CODE='0301' AND MAP.AC_GROUP_CODE=AG.AC_GROUP_CODE
			INNER JOIN AC_CHART AS CHART WITH(NOLOCK) ON CHART.GL_CODE=MAP.GL_CODE 
			INNER JOIN #DEP_AC D ON D.AC_NO=DAM.AC_NO
			WHERE DAM.APPROVED = 'YES' AND BR_CODE =@BR_CODE AND AC_STATUS<>'03' AND (AC_TYPE_SUB_TYPE_CODE='0301' OR AC_TYPE_SUB_TYPE_CODE='0302')
				AND (DAM.AC_NO = @INPUT OR DAM.AC_NAME LIKE @INPUT+'%')
			DROP TABLE IF EXISTS #DEP_AC
		END
		ELSE
		BEGIN
			INSERT INTO #DT
			SELECT  AC_NO CODE,AC_NAME [NAME],AG.AC_TYPE_SUB_TYPE_CODE,CHART.GL_CODE,CHART.BANK_GL_CODE,CHART.GL_NAME 
			FROM DEPOSIT_AC_MAST DAM WITH(NOLOCK)
			INNER JOIN AC_GROUP AG WITH(NOLOCK) ON DAM.AC_GROUP_CODE = AG.AC_GROUP_CODE
			INNER JOIN AC_GROUP_GL_MAP AS MAP WITH(NOLOCK) ON MAP.NAMED_AC_CODE='0301' AND MAP.AC_GROUP_CODE=AG.AC_GROUP_CODE
			INNER JOIN AC_CHART AS CHART WITH(NOLOCK) ON CHART.GL_CODE=MAP.GL_CODE 
			WHERE DAM.APPROVED = 'YES' AND BR_CODE =@BR_CODE AND AC_STATUS<>'03' AND (AC_TYPE_SUB_TYPE_CODE='0301' OR AC_TYPE_SUB_TYPE_CODE='0302')
				AND (AC_NO = @INPUT OR AC_NAME LIKE @INPUT+'%')
		END
	END

	SELECT * FROM #DT
	ORDER BY AC_NO
	OFFSET @SKIP_COUNT ROWS
	FETCH NEXT @ROW_COUNT ROWS ONLY

	SET @TOTAL_COUNT =  (SELECT COUNT(1) FROM #DT)

	DROP TABLE IF EXISTS #DT

END
--GO
--EXEC USP_CBS_LoanDisbursement_Get_DepositAccountList
--	@LOAN_NO= ''
--	,@INPUT =''
--	,@BR_CODE ='001'
--	,@GL_CODE =''
--	,@ROW_COUNT =100,@SKIP_COUNT =0