CREATE  PROCEDURE [dbo].[USP_CBS_TellerTransaction_GenerateVoucher]
(
	@TRAN_ID INT,
	@STATUS INT,
	@PREVIEW_ONLY BIT,
	@CENTER_CODE VARCHAR(30)=NULL,
	@GROUP_CODE VARCHAR(30)=NULL,
	@CUSTOMER_CODE VARCHAR(30),
	@BR_CODE VARCHAR(50),
	@AC_NO VARCHAR(50),
	@AC_NAME VARCHAR(50),
	@OPR_CODE VARCHAR(50),
	@TRAN_DATE DATE,
	@ENTRY_USER_ID VARCHAR(50),
	@TRAN_AMT DECIMAL(18,2),
	-- BANK
	@BANK_CODE VARCHAR(100) = NULL,
	@BANK_NOSTRO_AC_NO VARCHAR(50) = NULL,
	-- JOURNAL
	@JOURNAL_GL_CODE VARCHAR(50) = NULL,
	@JOURNAL_AC_NO VARCHAR(50) = NULL,
	-- INSTRUMENT
	@INST_NO VARCHAR(50) = NULL,
	@INST_CODE VARCHAR(50) = NULL,
	@INST_DATE DATE=NULL,
	-- TABLE TYPES
	@DENO AS TYPE_CBS_TellerTransaction_Deno READONLY,
	@CHARGE_LIST AS TYPE_CBS_TellerTransaction_Charge READONLY,
	--UI FIELDS
	@DESCRIPTION VARCHAR(256),
	@SOURCE_OF_FUND_ID INT = NULL, --@SOURCE_OF_FUND
	@WDR_DEPOSITOR_NAME NVARCHAR(100), --@WDR_DEPOSITOR_NAME
	-- ABBS FIELDS
	@IS_ABBS BIT,
	@REF_BR_CODE VARCHAR(50),
	@BANK_BR_CODE varchar(50),
	--Source
	@SOURCE_BANK_BRCODE  VARCHAR(50)='',
	@SOURCE_AC_NO  VARCHAR(50)='',
	@SOURCE_CHQ_NO  VARCHAR(50)='',
	@SOURCE_CHQ_DATE DATE=null,
	--approval
	@APPROVAL_USER_ID VARCHAR(50) = NULL,
	@APPROVAL_BR_CODE VARCHAR(50) = NULL,

	-- OUTPUT FIELDS
	@NEW_VCH_NO VARCHAR(50) = NULL OUTPUT,
	@NEW_BAL DECIMAL(18,2) = NULL OUTPUT,
	@IS_APPROVAL BIT=0 OUTPUT,
	@MAX_APPROVAL_LEVEL INT = 0 OUTPUT,
	@IS_PREPRINT BIT=0
)
AS
BEGIN
	DECLARE @MENU_CODE int = 701;
	DECLARE @VCH_NO VARCHAR(50)='',@OTHER_VCH_NO VARCHAR(50)='',@CHARGE_CODE VARCHAR(50)='',@AMT DECIMAL(18,2)=0
	,@AC_GROUP_CODE VARCHAR(50)='',@IS_LOAN_AC INT=0,@V_AMT DECIMAL(18,2)=0,@VOUCHER_AC_NO VARCHAR(50)='',@DESC VARCHAR(50)
	,@MIN_BAL AS DECIMAL(18,2)=0,@PRN_GL_CODE VARCHAR(50),@NOSTRO_GL_CODE VARCHAR(50)='',@TELLER_GL_CODE varchar(50)
	,@IBT_GL_CODE VARCHAR(50),@CUR_BAL DECIMAL(18,2)=0,@TOT_CHARGE_AMT DECIMAL(18,2)=0,@DESC1 VARCHAR(8000)=@DESCRIPTION,@DR_TRAN_BLOCKED VARCHAR(50)
	,@CR_TRAN_BLOCKED VARCHAR(50),@ALLOWED_WDR_BELOW_MIN_BAL VARCHAR(50),@DEBITING_WDR_CHARGE_DURING_TRAN VARCHAR(50),@CHARGE_METHOD_WDR_BELOW_MIN_BAL VARCHAR(50)
	,@AC_STATUS VARCHAR(50)
	, @DR_CR VARCHAR(2)
	,@SOURCE_AC_GROUP_CODE VARCHAR(50)
	,@SOURCE_PRN_GL_CODE VARCHAR(50)
	DECLARE @IS_CASH BIT ,@IS_VALID BIT,@ERROR_MSG VARCHAR(MAX);
	
	SET @DR_CR=(SELECT TOP 1 DR_CR FROM OPERATION_LIST WHERE OP_CODE=@OPR_CODE)
	IF @DR_CR NOT IN ('DR', 'CR')
		THROW 50000, 'Warning - ! Invalid Operation...!!!', 1 ;

	DECLARE @AC_LIST TYPE_CBS_AcAmtList;
	INSERT INTO @AC_LIST
	SELECT @AC_NO, @TRAN_AMT;
	
	DECLARE @SOURCE_TRAN_ID INT, @SOURCE_TYPE_ID TINYINT

	DROP TABLE IF EXISTS #AC_LIST_PENAL

	CREATE TABLE #AC_LISt_PENAL
	(AC_NO	VARCHAR(50)
	,AC_GROUP_CODE VARCHAR(50)
	,ID INT
	,TRAN_ID INT
	,INST_AMT DECIMAL(18,2)
	,DUE_EDATE DATE
	,DUE_NDATE VARCHAR(50)
	,GRACE_DAYS	INT
	,SCH_VS_NO INT 
	,TRAN_DATE	DATE
	,IS_PENAL_BENEFIT_USED	BIT
	,PENAL_OR_BENEFIT INT
	,MODE INT
	--,PENAL_BENIFIT INT
	,DAY_DIFF INT
	,RN INT
	,UP_TO_DAYS	INT
	,MAST_ID INT
	,DETL_ID INT
	,PENAL_BENEFIT_AMT	DECIMAL(18,2)
	,TOTAL_AMT DECIMAL(18,2)
	,AMOUNT DECIMAL(18,2)
	,PAYMENT_AMT DECIMAL(18,2)
	,LN DECIMAL(18,2)
	)

	INSERT INTO #AC_LIST_PENAL 
	(AC_NO,AC_GROUP_CODE,ID,TRAN_ID,INST_AMT,DUE_EDATE, DUE_NDATE, GRACE_DAYS,SCH_VS_NO,TRAN_DATE,IS_PENAL_BENEFIT_USED,PENAL_OR_BENEFIT,MODE,DAY_DIFF,RN,UP_TO_DAYS,MAST_ID,DETL_ID,PENAL_BENEFIT_AMT,TOTAL_AMT,AMOUNT,PAYMENT_AMT,LN)
	 EXEC USP_ACCOUNT_PENAL_BENEFIT_LIST @AC_LIST,@TRAN_DATE ,1
	
	--SELECT * FROM #AC_LIST_PENAL
	DECLARE @PENAL_AMOUNT DECIMAL(18,2) = ISNULL((SELECT SUM(ISNULL(PENAL_BENEFIT_AMT,0)) PENAL_AMOUNT 
													FROM #AC_LIST_PENAL 
													WHERE AC_NO=@AC_NO AND IS_PENAL_BENEFIT_USED = 1 AND PENAL_OR_BENEFIT = 1
													GROUP BY AC_NO),0)
	
	
	INSERT INTO #AC_LIST_PENAL 
	(AC_NO,AC_GROUP_CODE,ID,TRAN_ID,INST_AMT,DUE_EDATE, DUE_NDATE, GRACE_DAYS,SCH_VS_NO,TRAN_DATE,IS_PENAL_BENEFIT_USED,PENAL_OR_BENEFIT,MODE,DAY_DIFF,RN,UP_TO_DAYS,MAST_ID,DETL_ID,PENAL_BENEFIT_AMT,TOTAL_AMT,AMOUNT,PAYMENT_AMT,LN)
	 EXEC USP_ACCOUNT_PENAL_BENEFIT_LIST @AC_LIST,@TRAN_DATE ,0

	DECLARE @BENEFIT_AMOUNT DECIMAL(18,2) = ISNULL((SELECT SUM(ISNULL(PENAL_BENEFIT_AMT,0)) BENEFIT_AMOUNT 
													FROM #AC_LIST_PENAL 
													WHERE AC_NO=@AC_NO AND IS_PENAL_BENEFIT_USED = 1 AND PENAL_OR_BENEFIT = 2
													GROUP BY AC_NO),0)
	
	DECLARE @FINAL_AMT DECIMAL(18,2)=0
	SET @FINAL_AMT=  @TRAN_AMT + @PENAL_AMOUNT - @BENEFIT_AMOUNT
	--tran_amt
	--select dbo.GetAccountChequeStatus(@SOURCE_BANK_BRCODE, @SOURCE_AC_NO, @SOURCE_CHQ_NO)
		--------
		IF (@OPR_CODE='14' or @OPR_CODE = '15') 
		BEGIN
			DECLARE @WDR_BAL DECIMAL (18,2)=0;
			IF RTRIM(LTRIM(ISNULL(@SOURCE_AC_NO,'')))=''
			BEGIN
			;THROW 50000, 'Warning - ! Source A/C no. is not defined...!!!', 1;
			END
			IF (RTRIM(LTRIM(ISNULL(@INST_NO,'')))='' and @OPR_CODE='14')
			BEGIN
			;THROW 50000, 'Warning - ! Source A/C  cheque no. is not defined...!!!', 1;
			END
			IF (RTRIM(LTRIM(ISNULL(@SOURCE_CHQ_NO,'')))='' and @OPR_CODE='15')
			BEGIN
			;THROW 50000, 'Warning - ! Source A/C  cheque no. is not defined...!!!', 1;
			END
			IF RTRIM(LTRIM(ISNULL(@SOURCE_AC_NO,'')))=RTRIM(LTRIM(ISNULL(@AC_NO,'')))
			BEGIN
			;THROW 50000, 'Warning - ! Source A/C no.  and A/C no. should not be same...!!!', 1;
			END
			IF (DBO.GetAccountChequeStatus(@SOURCE_BANK_BRCODE, @SOURCE_AC_NO, @INST_NO) <> 2 )OR (ISNULL(DBO.GetAccountChequeStatus(@SOURCE_BANK_BRCODE, @SOURCE_AC_NO, @INST_NO),'')='')
			 AND @PREVIEW_ONLY =0 AND @OPR_CODE='14'
			BEGIN
				;THROW 50000, 'Warning - ! Invalid Source Cheque No...!!!', 1;
			END
			IF (DBO.GetAccountChequeStatus(@SOURCE_BANK_BRCODE, @SOURCE_AC_NO, @SOURCE_CHQ_NO) <> 2 )OR (ISNULL(DBO.GetAccountChequeStatus(@SOURCE_BANK_BRCODE, @SOURCE_AC_NO, @SOURCE_CHQ_NO),'')='')
			 AND @PREVIEW_ONLY =0 AND @OPR_CODE='15'
			BEGIN
				;THROW 50000, 'Warning - ! Invalid Source Cheque No...!!!', 1;
			END
			IF @INST_DATE>@TRAN_DATE OR @INST_DATE='' OR @INST_DATE IS NULL
			BEGIN
				;THROW 50000, 'Warning - ! Invalid Source Cheque Date...!!!', 1;
			END
			IF @INST_DATE>@TRAN_DATE OR @INST_DATE='' OR @INST_DATE IS NULL
			BEGIN
				;THROW 50000, 'Warning - ! Invalid Source Cheque Date...!!!', 1;
			END

			SELECT @AC_GROUP_CODE=AC_GROUP_CODE FROM DEPOSIT_AC_MAST WHERE AC_NO=@SOURCE_AC_NO AND BR_CODE=@SOURCE_BANK_BRCODE
			SET @WDR_BAL= (SELECT (CASE WHEN ((CUR_BAL-(CASE WHEN C.HOLD_AMT>DAM.MIN_BALANCE THEN C.HOLD_AMT ELSE DAM.MIN_BALANCE END)) < 0)
                                                THEN 0 ELSE (CUR_BAL-(CASE WHEN C.HOLD_AMT>DAM.MIN_BALANCE THEN C.HOLD_AMT ELSE DAM.MIN_BALANCE END))
                                            END) WDR_ELG_BAL          
                            FROM (
                                    SELECT SUM(GD.AMT) AS CUR_BAL,GD.SOURCE_TRAN_ID,GD.BR_CODE
                                        FROM GLTRAN_DETL AS GD
                                        INNER JOIN DEPOSIT_AC_MAST DAM ON GD.SOURCE_TYPE_ID = 3 AND GD.SOURCE_TRAN_ID = DAM.ID AND DAM.BR_CODE = GD.BR_CODE AND DAM.AC_NO = @SOURCE_AC_NO AND DAM.BR_CODE = @SOURCE_BANK_BRCODE--GD.AC_NO = DAM.AC_NO AND AGGM.AC_GROUP_CODE = DAM.AC_GROUP_CODE
                                        INNER JOIN AC_GROUP_GL_MAP AGGM ON GD.GL_CODE = AGGM.GL_CODE AND AGGM.NAMED_AC_CODE = '0301' AND DAM.AC_GROUP_CODE = AGGM.AC_GROUP_CODE
                                        WHERE GD.VALUE_DATE<=@TRAN_DATE --AND GD.AC_NO=@SOURCE_AC_NO AND DAM.AC_GROUP_CODE = @AC_GROUP_CODE
                                        GROUP BY GD.SOURCE_TRAN_ID,GD.BR_CODE
                                    ) T
									INNER JOIN DEPOSIT_AC_MAST DAM ON DAM.ID = T.SOURCE_TRAN_ID AND DAM.BR_CODE = T.BR_CODE
									INNER JOIN AC_GROUP AG ON DAM.AC_GROUP_CODE = AG.AC_GROUP_CODE AND AG.AC_TYPE_CODE = '03'
                                    INNER JOIN AC_GROUP_PARA AGP ON AG.AC_GROUP_CODE = AGP.AC_GROUP_CODE
									CROSS APPLY (
										SELECT ISNULL(SUM(HOLD_AMT),0) HOLD_AMT FROM BAL_HOLD_HIST B
										LEFT OUTER JOIN (SELECT DETL.BAL_HOLD_HIST_ID, MAST.TRAN_DATE
															FROM [BAL_HOLD_RELEASE_MAST] MAST
															INNER JOIN [BAL_HOLD_RELEASE_DETL] DETL ON DETL.BAL_HOLD_RELEASE_MAST_ID = MAST.TRAN_ID AND MAST.STATUS=1
															) X  ON X.BAL_HOLD_HIST_ID=B.TRAN_ID
										WHERE X.BAL_HOLD_HIST_ID IS NULL AND DAM.AC_NO =B.AC_NO AND DAM.BR_CODE = B.BR_CODE
                            ) C)
			
			IF @FINAL_AMT >@WDR_BAL AND @PREVIEW_ONLY =0
            BEGIN
				;THROW 50000, 'Warning - ! Insufficient balance in source account no. ...!!!', 1;
			END

		END

	-------------------------------
	-- Cheque Number Validations
	IF @OPR_CODE='06' OR (@OPR_CODE='08' AND @INST_CODE='01') OR (@OPR_CODE='12' AND @INST_CODE='01' )
	BEGIN
		IF (@OPR_CODE='12' AND @INST_CODE='01' ) -- DEPOSIT THROUGH CHEQUE
		BEGIN
			IF (DBO.GetAccountChequeStatus(@BR_CODE, @JOURNAL_AC_NO, @INST_NO) <> 2) OR (ISNULL(DBO.GetAccountChequeStatus(@BR_CODE, @JOURNAL_AC_NO, @INST_NO),'')='')
				THROW 50000, 'Warning - ! Invalid Cheque No...!!!', 1;
		END --@OPR_CODE='06' OR (@OPR_CODE='08' AND @INST_CODE='01')
		
		ELSE IF (@OPR_CODE='06' AND @INST_CODE='01')
		BEGIN
			IF (DBO.GetAccountChequeStatus(@REF_BR_CODE, @AC_NO, @INST_NO) <> 2 )OR (ISNULL(DBO.GetAccountChequeStatus(@REF_BR_CODE, @AC_NO, @INST_NO),'')='')
			THROW 50000, 'Warning - ! Invalid Cheque No...!!!', 1;
		END
		ELSE IF (@OPR_CODE='08')
		BEGIN
			-- IF (DBO.GetAccountChequeStatus(@REF_BR_CODE, @BANK_NOSTRO_AC_NO, @INST_NO) <> 2 )OR (ISNULL(DBO.GetAccountChequeStatus(@REF_BR_CODE, @BANK_NOSTRO_AC_NO, @INST_NO),'')='')
			--THROW 50000, 'Warning - ! Invalid Bank Cheque No...!!!', 1;
			 IF (DBO.GetAccountChequeStatus(@REF_BR_CODE, @AC_NO, @SOURCE_CHQ_NO) <> 2 )OR (ISNULL(DBO.GetAccountChequeStatus(@REF_BR_CODE, @AC_NO, @SOURCE_CHQ_NO),'')='')
			THROW 50000, 'Warning - ! Invalid  Source Cheque No...!!!', 1;
			IF @SOURCE_CHQ_DATE>@TRAN_DATE OR @SOURCE_CHQ_DATE='' OR @SOURCE_CHQ_DATE IS NULL
			THROW 50000, 'Warning - ! Invalid Source A/C Cheque Date...!!!', 1;
		END
		
		
		
		IF @INST_CODE<>'01'
			THROW 50000, 'Warning - ! Invalid Instrument Parameter...!!!', 1;
		IF @INST_DATE>@TRAN_DATE OR @INST_DATE='' OR @INST_DATE IS NULL
			THROW 50000, 'Warning - ! Invalid Instrument Date...!!!', 1;
	END

	-- Journal Deposit/Withdrawal(10,11)
	IF @OPR_CODE = '10' OR @OPR_CODE = '11' 
	BEGIN
		IF NOT EXISTS(SELECT TOP 1 1 FROM AC_CHART WHERE BANK_GL_CODE=@JOURNAL_GL_CODE AND APPROVED='YES' AND LEDGER='YES')
			THROW 50000, 'Warning - ! Invalid Journal GL Code Selected...!!!', 1;
		IF EXISTS(SELECT GL_CODE FROM AC_CHART WHERE BANK_GL_CODE=@JOURNAL_GL_CODE AND APPROVED='YES' AND LEDGER='YES' AND SUBLEDGER='YES')
		BEGIN
			IF NOT EXISTS(SELECT SUBLEDGER_CODE FROM SUBLEDGER AS S
								INNER JOIN SUBLEDGER_TYPE AS ST ON S.SUBLEDGER_TYPE_CODE=ST.SUBLEDGER_TYPE_CODE
								INNER JOIN SUBLEDGER_TYPE_GL AS STG ON ST.SUBLEDGER_TYPE_CODE=STG.SUBLEDGER_TYPE_CODE
								INNER JOIN AC_CHART AS AC ON AC.GL_CODE=STG.GL_CODE AND AC.BANK_GL_CODE=@JOURNAL_GL_CODE
						  WHERE S.BR_CODE=@BR_CODE AND S.SUBLEDGER_CODE=@JOURNAL_AC_NO AND S.APPROVED='YES'
						  UNION ALL
						  SELECT EMP_ID FROM EMPLOYEE AS S
								INNER JOIN EMP_GL AS STG ON 1=1
								INNER JOIN AC_CHART AS AC ON AC.GL_CODE=STG.GL_CODE AND AC.BANK_GL_CODE=@JOURNAL_GL_CODE
						  WHERE S.EMP_ID=@JOURNAL_AC_NO AND S.APPROVED='YES'
						  )
			BEGIN
				RAISERROR ('Warning - ! Invalid Journal A/C Selected...!!!',16,1);
				RETURN
			END
		END
	END

	DECLARE @BANK_ALIAS VARCHAR(50);
	IF @OPR_CODE ='08' OR @OPR_CODE ='09'
	BEGIN
		SELECT @NOSTRO_GL_CODE=BA.NOSTRO_GL_CODE
			, @BANK_ALIAS = B.BANK_ALIAS
		FROM BANK_ACNO BA 
			INNER JOIN BANK B ON B.BANK_CODE=@BANK_CODE AND B.BANK_CODE=BA.BANK_CODE
		WHERE BA.NOSTRO_AC_NO=@BANK_NOSTRO_AC_NO AND BA.BR_CODE=@BR_CODE
		IF ISNULL(@NOSTRO_GL_CODE,'')=''
		BEGIN
			RAISERROR ('Warning - ! Invalid Bank A/C No Or Bank Alias...!!!',16,1);
			RETURN
		END
	END

	IF @OPR_CODE ='13'
	BEGIN
		SELECT @NOSTRO_GL_CODE=BA.NOSTRO_GL_CODE
			, @BANK_ALIAS = B.BANK_ALIAS
		FROM BANK_ACNO BA 
			INNER JOIN BANK B ON B.BANK_CODE=@BANK_CODE AND B.BANK_CODE=BA.BANK_CODE
		WHERE BA.NOSTRO_AC_NO=@BANK_NOSTRO_AC_NO AND BA.BR_CODE=@BANK_BR_CODE
		IF ISNULL(@NOSTRO_GL_CODE,'')=''
		BEGIN
			RAISERROR ('Warning - ! Invalid Bank A/C No Or Bank Alias...!!!',16,1);
			RETURN
		END
	END
	
	SELECT @AC_GROUP_CODE=AC_GROUP_CODE,@IS_LOAN_AC=1 FROM LOAN_MAST WHERE AC_NO=@AC_NO AND BR_CODE=@REF_BR_CODE
	IF @IS_LOAN_AC=0 AND (@AC_GROUP_CODE='' OR @AC_GROUP_CODE IS NULL)
	BEGIN
		SELECT @AC_GROUP_CODE=AC_GROUP_CODE,@MIN_BAL=MIN_BALANCE FROM DEPOSIT_AC_MAST WHERE BR_CODE=@REF_BR_CODE AND AC_NO=@AC_NO
	END

	IF @IS_LOAN_AC=1 
	BEGIN
		SET @PRN_GL_CODE=ISNULL((SELECT GL_CODE FROM AC_GROUP_GL_MAP WHERE AC_GROUP_CODE=@AC_GROUP_CODE AND NAMED_AC_CODE='0401' AND CUR_CODE='01'),'')
	END
	ELSE
	BEGIN
		SET @PRN_GL_CODE=ISNULL((SELECT GL_CODE FROM AC_GROUP_GL_MAP WHERE AC_GROUP_CODE=@AC_GROUP_CODE AND NAMED_AC_CODE='0301' AND CUR_CODE='01'),'')
	END

	IF @IS_LOAN_AC=1
	BEGIN
		SET @AC_STATUS = (SELECT LM.LOAN_STATUS FROM LOAN_MAST LM WHERE LM.AC_NO=@AC_NO AND LM.BR_CODE=@REF_BR_CODE AND LM.APPROVED='YES');
		IF @AC_STATUS IS NULL
			THROW 50000, 'Warning - ! Loan A/C doesn''t exist...!!!', 1;
		IF @AC_STATUS = '11'
			THROW 50000, 'Warning - ! Loan A/C No is uploaded for BLB Transaction...!!!', 1;
		IF @AC_STATUS <> '02'
			THROW 50000, 'Warning - ! Invalid Loan A/C No. Loan A/c is not active...!!!', 1;
	END
	ELSE
	BEGIN
		DECLARE @MATURE_DATE DATE;
		SET @AC_STATUS = (SELECT LM.AC_STATUS FROM DEPOSIT_AC_MAST LM WHERE LM.AC_NO=@AC_NO AND LM.BR_CODE=@REF_BR_CODE AND LM.APPROVED='YES');
		SELECT @AC_STATUS = LM.AC_STATUS ,
			@MATURE_DATE = CR_MATURED_DATE
		FROM DEPOSIT_AC_MAST LM WHERE LM.AC_NO=@AC_NO AND LM.BR_CODE=@REF_BR_CODE AND LM.APPROVED='YES'
		IF @AC_STATUS IS NULL
			THROW 50000, 'Warning - ! Deposit A/C doesn''t exist...!!!', 1;
		IF @AC_STATUS = '11' AND @DR_CR = 'DR'
			THROW 50000, 'Warning - ! Withdrawal operation not allowed, Deposit A/C No. has been uploaded for BLB Transaction...!!!', 1;
		IF @AC_STATUS NOT IN ('02', '11')
			THROW 50000, 'Warning - ! Invalid Deposit A/C. Deposit A/c is not active...!!!', 1;

		DECLARE @AC_TYPE_SUB_TYPE_CODE_1 VARCHAR(50);
		SELECT @AC_TYPE_SUB_TYPE_CODE_1 = AC_TYPE_SUB_TYPE_CODE
		FROM AC_GROUP
		WHERE AC_GROUP_CODE = (SELECT TOP 1 AC_GROUP_CODE FROM DEPOSIT_AC_MAST WHERE AC_NO = @AC_NO);

		IF @AC_TYPE_SUB_TYPE_CODE_1 <> '0303'
		BEGIN
			IF @MATURE_DATE < @TRAN_DATE
				THROW 50000, 'Warning - ! Invalid Deposit A/C.Deposit A/C has already been matured...!!!', 1;
		END
	END

	--IF DBO.UserHasMenuRights(@ENTRY_USER_ID,@TRAN_DATE,@BR_CODE,'02101',1)=0
	--BEGIN
	--	SET @ERROR_MSG='Warning - ! Insufficient Privileges. Please Check Menu Rights For NEW Option...!!!'
	--	RAISERROR (@ERROR_MSG,16,1);
	--	RETURN
	--END


	IF @OPR_CODE='13'
	BEGIN
		SET @IS_ABBS=1
	END


	IF @OPR_CODE ='14' OR  @OPR_CODE ='15'
	BEGIN
		SET @IS_ABBS=1
		SELECT @AC_GROUP_CODE=AC_GROUP_CODE FROM DEPOSIT_AC_MAST WHERE BR_CODE=@REF_BR_CODE AND AC_NO=@AC_NO
		SET @PRN_GL_CODE=ISNULL((SELECT GL_CODE FROM AC_GROUP_GL_MAP WHERE AC_GROUP_CODE=@AC_GROUP_CODE AND NAMED_AC_CODE='0301' AND CUR_CODE='01'),'')
		SELECT @SOURCE_AC_GROUP_CODE=AC_GROUP_CODE,@MIN_BAL=MIN_BALANCE FROM DEPOSIT_AC_MAST WHERE BR_CODE=@SOURCE_BANK_BRCODE AND AC_NO=@SOURCE_AC_NO
		SET @SOURCE_PRN_GL_CODE=ISNULL((SELECT GL_CODE FROM AC_GROUP_GL_MAP WHERE AC_GROUP_CODE=@SOURCE_AC_GROUP_CODE AND NAMED_AC_CODE='0301' AND CUR_CODE='01'),'')
	END


	--ABBS Validation --============================================================================================
	IF @IS_ABBS=1
	BEGIN
		SELECT TOP 1 @IBT_GL_CODE=RT.IBT_GL_CODE
		FROM REMIT_TYPE AS RT
			INNER JOIN CURRENCY AS C ON RT.REMIT_CODE=C.REMIT_CODE
		WHERE C.CUR_CODE='01'

		DECLARE @WDR VARCHAR(50)='NO',@DEPOSIT VARCHAR(50)='NO',@ALLOW_COUNTER_CHQ_IN_ABBS BIT=(SELECT ALLOW_COUNTER_CHQ_IN_ABBS FROM GLOBAL_SETUP)
		SELECT TOP 1 @WDR=ISNULL(WDR,'NO'),@DEPOSIT=ISNULL(DEPOSIT,'NO') FROM BRANCH_ABBS WHERE BR_CODE=@BR_CODE AND APPROVED='YES' AND EFFECT_DATE<=@TRAN_DATE ORDER BY EFFECT_DATE DESC
		
		IF (@OPR_CODE='01' OR @OPR_CODE='10' OR @OPR_CODE='12' OR @OPR_CODE='13' OR @OPR_CODE='14' OR @OPR_CODE ='15')
		BEGIN
			IF @DEPOSIT= 'NO'
				THROW 50000, 'Warning - ! ABBS Deposit not allowed...!!!', 1;
		END
		ELSE IF @OPR_CODE='06' OR @OPR_CODE='07' OR @OPR_CODE='08' OR @OPR_CODE='11' 
		BEGIN
			IF @WDR= 'NO'
				THROW 50000, 'Warning - ! ABBS Withdrawl not allowed...!!!', 1;
			IF @OPR_CODE='06' AND @ALLOW_COUNTER_CHQ_IN_ABBS<>1
				THROW 50000, 'Warning - ! ABBS Cheque Withdrawl Not Allowed...!!!', 1;
		END
		ELSE
		BEGIN
			;THROW 50000, 'Warning - ! Invalid ABBS Transaction Operation...!!!', 1;
		END
	END

	--=== Account Group Parameter Validation --============================================================================================

	DECLARE @TRAN_AMT_R1 DECIMAL(18,2),@TRAN_AMT_R2 DECIMAL(18,2),@TRAN_AMT_MULTIPLEOF VARCHAR(MAX)='',@AC_TYPE_SUB_TYPE_CODE VARCHAR(50)
		,@START_DATE DATE,@END_DATE DATE

	SELECT @DR_TRAN_BLOCKED=DR_TRAN_BLOCKED,@CR_TRAN_BLOCKED=CR_TRAN_BLOCKED,@ALLOWED_WDR_BELOW_MIN_BAL=ALLOWED_WDR_BELOW_MIN_BAL,@DEBITING_WDR_CHARGE_DURING_TRAN=DEBITING_WDR_CHARGE_DURING_TRAN 
		,@CHARGE_METHOD_WDR_BELOW_MIN_BAL=CHARGE_METHOD_WDR_BELOW_MIN_BAL
		,@TRAN_AMT_R1=CONVERT(DECIMAL(18,2),TRAN_AMT_R1),@TRAN_AMT_R2=CONVERT(DECIMAL(18,2),TRAN_AMT_R2),@TRAN_AMT_MULTIPLEOF=TRAN_AMT_MULTIPLEOF 
		,@START_DATE=[START_DATE],@END_DATE=END_DATE
	FROM AC_GROUP_PARA WHERE AC_GROUP_CODE=@AC_GROUP_CODE

	SELECT @AC_TYPE_SUB_TYPE_CODE=AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE AC_GROUP_CODE=@AC_GROUP_CODE

	IF @START_DATE>@TRAN_DATE OR (@END_DATE IS NOT NULL AND @END_DATE<@TRAN_DATE)
		THROW 50000, 'Warning - ! Transaction date is not in range of Account Group Parameter...!!!', 1;

	SELECT @SOURCE_TYPE_ID = SOURCE_TYPE_ID, @SOURCE_TRAN_ID = SOURCE_TRAN_ID
	FROM (
			SELECT 3 SOURCE_TYPE_ID, ID AS SOURCE_TRAN_ID FROM dbo.DEPOSIT_AC_MAST WHERE AC_NO = @AC_NO AND BR_CODE = @REF_BR_CODE
			UNION
			SELECT 4 SOURCE_TYPE_ID, ID AS SOURCE_TRAN_ID FROM dbo.LOAN_MAST WHERE AC_NO = @AC_NO AND BR_CODE = @REF_BR_CODE
		)T

	SET @CUR_BAL=CONVERT(decimal(18,2), ISNULL((SELECT SUM(GD.AMT) FROM GLTRAN_DETL AS GD WHERE GD.SOURCE_TYPE_ID = @SOURCE_TYPE_ID AND GD.SOURCE_TRAN_ID = @SOURCE_TRAN_ID AND GD.GL_CODE=@PRN_GL_CODE AND GD.VALUE_DATE <= @TRAN_DATE),0))--GD.AC_NO=@AC_NO AND GD.BR_CODE = @REF_BR_CODE
	--SET @CUR_BAL=CONVERT(decimal(18,2), ISNULL((SELECT SUM(GD.AMT) FROM GLTRAN_DETL AS GD WHERE GD.AC_NO=@AC_NO AND GD.GL_CODE=@PRN_GL_CODE AND GD.BR_CODE = @REF_BR_CODE AND GD.VALUE_DATE <= @TRAN_DATE),0))

	--=== Deposit/Loan Validation --============================================================================================
	IF @IS_LOAN_AC = 0
	BEGIN
		IF @FINAL_AMT  < @TRAN_AMT_R1 OR @FINAL_AMT > @TRAN_AMT_R2
		BEGIN
			SET @ERROR_MSG='Warning - ! Transaction Amount Is Not In Range, Range Is (From '+CONVERT(VARCHAR(50),@TRAN_AMT_R1)+' To '+CONVERT(VARCHAR(50),@TRAN_AMT_R2)+')...!!!';
			;THROW 50000, @ERROR_MSG, 1;
		END


		------------------VALIDATION ADDED--------------------------

		DROP TABLE IF EXISTS #TEMP_M;
		DECLARE @MCODE DECIMAL (18,2) = 0

		SELECT CONVERT(DECIMAL(18,2),I.ITEMS) AS MCODE INTO #TEMP_M FROM DBO.Split(@TRAN_AMT_MULTIPLEOF,',') I
		WHILE EXISTS(SELECT TOP 1 * FROM #TEMP_M)
		BEGIN
			SELECT TOP 1 @MCODE=CONVERT(DECIMAL(18,2),MCODE) FROM #TEMP_M

			IF @MCODE = 0
			BEGIN
				SET @ERROR_MSG='Warning - ! Invalid Transaction Amount '+CONVERT(VARCHAR(50),@FINAL_AMT)+', Amount Is Not Divisible By '+CONVERT(VARCHAR(50),@MCODE)+'..!!!'
				RAISERROR (@ERROR_MSG,16,1);
				RETURN
			END

			If (@FINAL_AMT%@MCODE)>0
			BEGIN
				SET @ERROR_MSG='Warning - ! Invalid Transaction Amount '+CONVERT(VARCHAR(50),@FINAL_AMT)+', Amount Is Not Divisible By '+CONVERT(VARCHAR(50),@MCODE)+'..!!!'
				RAISERROR (@ERROR_MSG,16,1);
				RETURN
			END

			DELETE FROM #TEMP_M WHERE MCODE=@MCODE
		END

		------------------VALIDATION ADDED--------------------------

		--DROP TABLE IF EXISTS #TRAN_AMT_MULTIPLEOF;
		--SELECT CONVERT(DECIMAL(18,2),I.ITEMS) AS MULTIPLE_OF
		--	, REMAINDER = @TRAN_AMT % CONVERT(DECIMAL(18,2),I.ITEMS)
		--INTO #TRAN_AMT_MULTIPLEOF FROM DBO.Split(@TRAN_AMT_MULTIPLEOF,',') I

		--DECLARE @INVALID_TRAN_AMT_MULTIPLEOF DECIMAL(18,2)= (SELECT TOP 1 MULTIPLE_OF FROM #TRAN_AMT_MULTIPLEOF WHERE REMAINDER > 0);
		--DROP TABLE IF EXISTS #TRAN_AMT_MULTIPLEOF;
		--IF @INVALID_TRAN_AMT_MULTIPLEOF IS NOT NULL
		--BEGIN
		--	SET @ERROR_MSG='Warning - ! Invalid Transaction Amount '+CONVERT(VARCHAR(50),@TRAN_AMT)+', Amount Is Not Divisible By '+CONVERT(VARCHAR(50),@INVALID_TRAN_AMT_MULTIPLEOF)+'..!!!'
		--	;THROW 50000, @ERROR_MSG, 1;
		--END

		IF @DR_CR='CR'
		BEGIN
			IF @CR_TRAN_BLOCKED= 'YES'
				THROW 50000, 'Warning - ! Credit transaction is blocked for the product account...!!!', 1;
			IF @AC_TYPE_SUB_TYPE_CODE = '0304' AND @CUR_BAL > 0
				THROW 50000, 'Warning - ! Multiple Deposit not allowed in fixed deposit account...!!!', 1;
		END
		IF @DR_CR='DR' AND @DR_TRAN_BLOCKED= 'YES'
			THROW 50000, 'Warning - ! Debit transaction is blocked for the product account...!!!', 1;
	END
	ELSE IF @IS_LOAN_AC = 1
	BEGIN
		IF @DR_CR='DR'
		BEGIN
			DECLARE @LIMIT_AMT DECIMAL(18,2)=0, @REMAIN_LIMIT DECIMAL(18,2)=0;
			SET @LIMIT_AMT=(
				SELECT SUM(AL.ASSIGNED_LIMIT) AS LIMIT 
				FROM AC_LIMIT AL 
				WHERE AL.AC_NO=@AC_NO AND AL.BR_CODE=@REF_BR_CODE AND AL.STATUS_CHANGE_DATE<=@TRAN_DATE AND AL.[STATUS]=1
			);

			SET @REMAIN_LIMIT=@LIMIT_AMT-(@CUR_BAL*-1)
			IF @LIMIT_AMT<(@CUR_BAL*-1)+ @FINAL_AMT
			BEGIN
				SET @ERROR_MSG='Warning - ! Loan Limit Exceed, Remaining Limit Is'+CONVERT(VARCHAR(50),@REMAIN_LIMIT)+'...!!!';
				THROW 50000, @ERROR_MSG, 1;
			END
		END
		ELSE
		BEGIN
			IF (@CUR_BAL*-1)<@FINAL_AMT
			BEGIN
				SET @ERROR_MSG='Warning - ! Deposit amount is more than loan balance...!!!';
				THROW 50000, @ERROR_MSG, 1;
			END
		END
	END

	--=== Teller Validation --============================================================================================
	SELECT @TELLER_GL_CODE=TELLER_GL_CODE FROM CURRENCY WHERE CUR_CODE='01'
	SET @IS_CASH=(CASE WHEN @OPR_CODE IN('06','07','01') THEN 1 ELSE 0 END)
	SET @TOT_CHARGE_AMT =ISNULL((SELECT SUM(CL.CHARGE_AMT) FROM @CHARGE_LIST CL),0)
	
	IF @APPROVAL_USER_ID = @ENTRY_USER_ID
	BEGIN
		If (@IS_CASH = 1 OR (@TOT_CHARGE_AMT>0 AND @OPR_CODE<>'12')) AND @PREVIEW_ONLY=0 
		BEGIN
			IF DBO.IsUserTeller(@BR_CODE, @ENTRY_USER_ID, @TRAN_DATE) <> 1
				THROW 50000, 'Warning - ! Current user is not teller...!!!', 1;
		END

		IF @DR_CR='DR' -- WITHDRAW
		BEGIN
			--Check Teller Balance
			If @IS_CASH = 1 AND @PREVIEW_ONLY=0
			BEGIN
				SET @AMT=DBO.GetTellerBal(@ENTRY_USER_ID,'01','T',@BR_CODE)
				If @AMT< @FINAL_AMT 
				BEGIN
					SET @ERROR_MSG='Warning - ! Insufficient Teller Balance, Teller Balance Is '+CONVERT(VARCHAR(50),@AMT) +'...!!!';
					THROW 50000, @ERROR_MSG, 1;
				END    
			END 

			EXEC USP_CHECKDEPOSITWDR @AC_NO=@AC_NO,@CUR_CODE='01',@CUR_WDR_AMT=@FINAL_AMT,@BR_CODE=@REF_BR_CODE,@EFFECT_DATE=@TRAN_DATE,@IS_VALID=@IS_VALID OUTPUT,@ERROR_MSG=@ERROR_MSG OUTPUT
			IF @IS_VALID=0 
				THROW 50000, @ERROR_MSG, 1;
		END
	END
	IF @OPR_CODE='12'
	BEGIN
		DECLARE @TOT_AMT AS DECIMAL(18,2)
		SET @TOT_AMT=@FINAL_AMT+@TOT_CHARGE_AMT
		EXEC USP_CHECKDEPOSITWDR @AC_NO=@JOURNAL_AC_NO,@CUR_CODE='01',@CUR_WDR_AMT=@TOT_AMT,@BR_CODE=@BR_CODE,@EFFECT_DATE=@TRAN_DATE,@IS_VALID=@IS_VALID OUTPUT,@ERROR_MSG=@ERROR_MSG OUTPUT
		IF @IS_VALID=0 
		BEGIN
			RAISERROR (@ERROR_MSG,16,1);
			RETURN
		END
	END
	--END VALIDATION
	--CREATE TABLE #VCH(GL_CODE VARCHAR(50),AC_NO VARCHAR(50),DESC1 VARCHAR(8000),AMT DECIMAL(18,2),BR_CODE VARCHAR(50),INST_CODE VARCHAR(50),INST_NO VARCHAR(50),INST_DATE DATE,VCH_TYPE INT)
	
	IF OBJECT_ID('tempdb..#VCH') IS NULL
	BEGIN
		CREATE TABLE #VCH (GL_CODE VARCHAR(50),AC_NO VARCHAR(50),DESC1 VARCHAR(8000),AMT DECIMAL(18,2),BR_CODE VARCHAR(50),INST_CODE VARCHAR(50),INST_NO VARCHAR(50),INST_DATE DATE, VCH_TYPE INT,SOURCE_TYPE_ID TINYINT,SOURCE_TRAN_ID INT)
		--DROP TABLE IF EXISTS #VCH
	END


	IF @OPR_CODE IN ('01','09')
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_01_09 @OPR_CODE, @BR_CODE, @REF_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @NOSTRO_GL_CODE, @AC_NO, @AC_NAME, @TRAN_AMT, @DESCRIPTION, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST,@PENAL_AMOUNT, @BENEFIT_AMOUNT
	END ELSE 
	IF @OPR_CODE IN ('02', '04')
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_02_04 @BR_CODE, @REF_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @AC_NO, @AC_NAME, @TRAN_AMT, @DESCRIPTION, @BANK_ALIAS, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST
	END
	ELSE IF @OPR_CODE = '03'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_03 @BR_CODE, @REF_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @AC_NO, @AC_NAME, @TRAN_AMT, @DESCRIPTION, @INST_NO, @BANK_ALIAS, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST
	END
	ELSE IF @OPR_CODE = '05'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_05 @BR_CODE, @REF_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @NOSTRO_GL_CODE, @AC_NO, @AC_NAME, @TRAN_AMT, @DESCRIPTION, @BANK_ALIAS, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST
	END
	ELSE IF @OPR_CODE IN ('06', '07', '08', '11')
	BEGIN
		SET  @INST_NO= (CASE WHEN @OPR_CODE='08' THEN @SOURCE_CHQ_NO ELSE @INST_NO END)
		SET @INST_DATE=(CASE WHEN @OPR_CODE='08' THEN @SOURCE_CHQ_DATE ELSE @INST_DATE END)
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_06_07_08_11 @OPR_CODE, @BR_CODE, @REF_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @NOSTRO_GL_CODE, @AC_NO, @AC_NAME, @TRAN_AMT, @DESCRIPTION, @BANK_ALIAS, @JOURNAL_GL_CODE, @JOURNAL_AC_NO, @INST_CODE, @INST_NO, @INST_DATE, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST
	END 
	ELSE IF @OPR_CODE = '10'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_10 @BR_CODE = @BR_CODE,@REF_BR_CODE = @REF_BR_CODE,@TELLER_GL_CODE = @TELLER_GL_CODE,@IBT_GL_CODE = @IBT_GL_CODE,@PRN_GL_CODE = @PRN_GL_CODE,@AC_GROUP_CODE = @AC_GROUP_CODE,@AC_NO = @AC_NO, @AC_NAME=@AC_NAME,@TRAN_AMT = @TRAN_AMT,@DESCRIPTION = @DESCRIPTION,@JOURNAL_GL_CODE = @JOURNAL_GL_CODE,@JOURNAL_AC_NO = @JOURNAL_AC_NO,@ENTRY_USER_ID = @ENTRY_USER_ID,@TRAN_DATE = @TRAN_DATE,@CHARGE_LIST = @CHARGE_LIST
	END
	ELSE IF @OPR_CODE = '12'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_12 @BR_CODE = @BR_CODE,@REF_BR_CODE = @REF_BR_CODE,@TELLER_GL_CODE = @TELLER_GL_CODE,@IBT_GL_CODE = @IBT_GL_CODE,@PRN_GL_CODE = @PRN_GL_CODE,@AC_GROUP_CODE = @AC_GROUP_CODE,@AC_NO = @AC_NO, @AC_NAME=@AC_NAME,@TRAN_AMT = @TRAN_AMT,@DESCRIPTION = @DESCRIPTION,@JOURNAL_GL_CODE = @JOURNAL_GL_CODE,@JOURNAL_AC_NO = @JOURNAL_AC_NO,@INST_CODE = @INST_CODE,@INST_NO = @INST_NO,@INST_DATE = @INST_DATE,@ENTRY_USER_ID = @ENTRY_USER_ID,@TRAN_DATE = @TRAN_DATE,@CHARGE_LIST = @CHARGE_LIST
	END
	ELSE IF @OPR_CODE = '13'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_13 @OPR_CODE, @BR_CODE, @BANK_BR_CODE, @TELLER_GL_CODE, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @NOSTRO_GL_CODE, @AC_NO, @AC_NAME, @TRAN_AMT,@TOT_CHARGE_AMT, @DESCRIPTION, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST
	END
	ELSE IF @OPR_CODE = '14'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE, VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_14 @OPR_CODE, @BR_CODE, @REF_BR_CODE, @SOURCE_AC_NO, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @SOURCE_PRN_GL_CODE, @AC_NO, @TRAN_AMT, @DESCRIPTION, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST, @WDR_DEPOSITOR_NAME, @INST_NO
	END
	ELSE IF @OPR_CODE = '15'
	BEGIN
		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE,VCH_TYPE)
		EXEC USP_TELLER_TXN_OPERATION_15 @OPR_CODE, @BR_CODE, @REF_BR_CODE, @SOURCE_AC_NO, @IBT_GL_CODE, @PRN_GL_CODE, @AC_GROUP_CODE, @SOURCE_PRN_GL_CODE, @AC_NO, @TRAN_AMT, @TOT_CHARGE_AMT, @DESCRIPTION, @ENTRY_USER_ID, @TRAN_DATE, @CHARGE_LIST , @SOURCE_BANK_BRCODE, @WDR_DEPOSITOR_NAME, @SOURCE_CHQ_NO
	END

	SET @NEW_BAL=CONVERT(DECIMAL(18,2),CONVERT(DECIMAL(18,2),@CUR_BAL)+CONVERT(DECIMAL(18,2),ISNULL((SELECT SUM(AMT) FROM #VCH WHERE GL_CODE=@PRN_GL_CODE AND AC_NO=@AC_NO),0)))
	IF @IS_LOAN_AC=1
	BEGIN
		SET @NEW_BAL=CONVERT(DECIMAL(18,2),@NEW_BAL*-1);
	END

	IF (@OPR_CODE='08' AND @BANK_NOSTRO_AC_NO<>'')
	BEGIN
		DECLARE @BANKVALIDATION VARCHAR(100)=  DBO.GETBANKBALANCEVALIDATION(@BANK_NOSTRO_AC_NO, @TRAN_AMT ,@TRAN_DATE,@BR_CODE)
		IF(ISNULL(@BANKVALIDATION,'')<>'')
			THROW 50000, @BANKVALIDATION, 1;
	END
	IF (@OPR_CODE='11' AND @JOURNAL_GL_CODE<>'')
	BEGIN
		DECLARE @BANKVALIDATION_GL VARCHAR(100)=  DBO.GETBANKBALANCEVALIDATION_FROM_GL(@JOURNAL_GL_CODE, @TRAN_AMT ,@TRAN_DATE,@BR_CODE)
		IF(ISNULL(@BANKVALIDATION_GL,'')<>'')
			THROW 50000, @BANKVALIDATION_GL, 1;
	END
	---------------------------Previous--------------------
	--IF (@OPR_CODE='13' AND @BANK_NOSTRO_AC_NO<>'')
	--BEGIN
	--	DECLARE @BANKBRVALIDATION VARCHAR(100)=  DBO.GETBANKBALANCEVALIDATION(@BANK_NOSTRO_AC_NO, @TRAN_AMT ,@TRAN_DATE,@BANK_BR_CODE)
	--	IF(ISNULL(@BANKBRVALIDATION,'')<>'')
	--		THROW 50000, @BANKVALIDATION, 1;
	--END
	---------------------------Latest change------------Due to msg supress
	IF (@OPR_CODE='13' AND @BANK_NOSTRO_AC_NO<>'')
	BEGIN
		DECLARE @BANKBRVALIDATION VARCHAR(100);
		set @BANKBRVALIDATION= (select DBO.GETBANKBALANCEVALIDATION(@BANK_NOSTRO_AC_NO, @TRAN_AMT ,@TRAN_DATE,@BANK_BR_CODE))
		IF(ISNULL(@BANKBRVALIDATION,'')<>'')
		BEGIN
			;THROW 50001,@BANKBRVALIDATION , 16;
		END
	END



	IF @TOT_CHARGE_AMT >0
	BEGIN
		SET @AMT =@TOT_CHARGE_AMT*-1
		SET @DESC1='Charge Receipt From A/C NO.' + @AC_NO

		IF (@OPR_CODE IN ('10','12'))
		BEGIN
			DECLARE @GL_CODE varchar(50)
			SET @GL_CODE =(SELECT GL_CODE FROM AC_CHART WHERE BANK_GL_CODE=@JOURNAL_GL_CODE)
			INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
			VALUES(@GL_CODE,@JOURNAL_AC_NO,@DESC1,@AMT,@BR_CODE,1)
		END
		ELSE IF(@OPR_CODE='01')
		BEGIN
			INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
			VALUES(@TELLER_GL_CODE,@ENTRY_USER_ID,@DESC1,@AMT,@BR_CODE,1)
		END
		ELSE IF(@OPR_CODE IN ('09','13'))
		BEGIN
			INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
			VALUES(@NOSTRO_GL_CODE,@BANK_NOSTRO_AC_NO,@DESC1,@AMT,@BR_CODE,1)
		END
		ELSE IF(@OPR_CODE IN ('06','07','08','11','14'))
		BEGIN
			INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
			VALUES(@PRN_GL_CODE,@AC_NO,@DESC1,@AMT,@BR_CODE,1)
		END
		ELSE IF(@OPR_CODE IN ('14','15'))
		BEGIN
			INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
			VALUES(@SOURCE_PRN_GL_CODE,@SOURCE_AC_NO,@DESC1,@AMT,(CASE WHEN @OPR_CODE ='15' THEN @SOURCE_BANK_BRCODE ELSE  @BR_CODE END),1)
		END

		INSERT INTO #VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,VCH_TYPE)
		SELECT C.GL_CODE,'',@DESC1,CL.Charge_Amt,@BR_CODE,1
		FROM AC_GROUP_CHARGE_HIST_DETL D
			INNER JOIN (SELECT AGCHM.TRAN_ID,AGCHM.AC_GROUP_CODE,ROW_NUMBER() OVER(PARTITION BY AGCHM.AC_GROUP_CODE ORDER BY AGCHM.EFFECT_DATE DESC)RN FROM AC_GROUP_CHARGE_HIST_MAST AGCHM WHERE AGCHM.EFFECT_DATE<=@TRAN_DATE AND AGCHM.STATUS=1)AGCHM ON AGCHM.TRAN_ID=D.AC_GROUP_CHARGE_HIST_MAST_ID AND AGCHM.AC_GROUP_CODE=@AC_GROUP_CODE AND AGCHM.RN=1
			INNER JOIN @CHARGE_LIST AS CL ON CL.Charge_Code=D.CHARGE_CODE AND CL.Charge_Amt>0
			INNER JOIN CHARGE AS C ON C.CHARGE_CODE=CL.Charge_Code
	END

	IF @PREVIEW_ONLY=1
	BEGIN
		IF(@IS_PREPRINT =1)
		BEGIN
			IF OBJECT_ID('tempdb..#TEMPP_VCH111',N'U') IS NULL
			BEGIN
				CREATE TABLE #TEMPP_VCH111(BANK_GL_CODE VARCHAR(100),GL_NAME VARCHAR(500),GL_CODE VARCHAR(100),AC_NO VARCHAR(50)
				 ,DESC1 VARCHAR(500),AMT DECIMAL(18,2),BR_CODE VARCHAR(50),INST_CODE VARCHAR(50),INST_NO VARCHAR(50)
				 ,INST_DATE DATE ,CUR_CODE VARCHAR(50),VCH_TYPE INT)
			END
			TRUNCATE TABLE #TEMPP_VCH111
			INSERT INTO #TEMPP_VCH111(BANK_GL_CODE, GL_NAME, GL_CODE, AC_NO, DESC1 ,AMT, BR_CODE, INST_CODE, INST_NO, INST_DATE, CUR_CODE,VCH_TYPE)
			SELECT AC.BANK_GL_CODE,AC.GL_NAME + ' (' + AC.BANK_GL_CODE +')' GL_NAME
			,T.GL_CODE,T.AC_NO,T.DESC1,T.AMT,T.BR_CODE,T.INST_CODE,T.INST_NO,T.INST_DATE
			,'01' CUR_CODE,VCH_TYPE
			FROM #VCH AS T
				LEFT OUTER JOIN AC_CHART AS AC ON T.GL_CODE=AC.GL_CODE
			ORDER BY T.AMT ASC
		END
		ELSE
		BEGIn
			SELECT AC.BANK_GL_CODE,AC.GL_NAME + ' (' + AC.BANK_GL_CODE +')' GL_NAME
			,T.GL_CODE,T.AC_NO,T.DESC1,T.AMT,T.BR_CODE,T.INST_CODE,T.INST_NO,T.INST_DATE
			,'01' CUR_CODE, VCH_TYPE
			FROM #VCH AS T
				LEFT OUTER JOIN AC_CHART AS AC ON T.GL_CODE=AC.GL_CODE
			--ORDER BY T.AMT ASC
		END

		DROP TABLE IF EXISTS ##TEMPP_VCH111
	END
	ELSE
	BEGIN
		IF EXISTS(SELECT T.GL_CODE FROM #VCH AS T 
							LEFT OUTER JOIN AC_CHART AC ON T.GL_CODE=AC.GL_CODE AND AC.APPROVED='YES' AND AC.LEDGER='YES' 
						WHERE AC.GL_CODE IS NULL
					  )
			THROW 50000, 'Warning - ! Invalid GL Code Found In Voucher...!!!', 1;
		IF (SELECT SUM(AMT) FROM #VCH) <> 0
			THROW 50000, 'Warning - ! Invalid Voucher Amount...!!!', 1;
		IF NOT EXISTS(SELECT TOP 1 1 FROM #VCH)
			THROW 50000, 'Warning - ! Transaction Not Found In Voucher...!!!', 1;

		DECLARE @FYEAR VARCHAR(50)=(SELECT TOP 1 FISCAL_YEAR FROM FISCAL_YEAR WHERE START_DATE<=@TRAN_DATE AND END_DATE>=@TRAN_DATE ORDER BY FISCAL_YEAR DESC);
		IF ISNULL(@FYEAR,'')=''
			THROW 50000, 'Warning - ! Invalid Fiscal Year Found...!!!', 1;

		DECLARE @TXN_LIST AS TYPE_CBS_GlTransaction;
		INSERT INTO @TXN_LIST (GL_CODE, AMOUNT)
		SELECT GD.GL_CODE, GD.AMT AMOUNT
		FROM #VCH GD

		DECLARE @IS_CREATE BIT =  CASE WHEN @STATUS = 1 THEN 0 ELSE 1 END;
		DECLARE @HAS_APPROVAL_RIGHTS BIT;
		
		IF @IS_CREATE = 1
		BEGIN
			IF @APPROVAL_USER_ID = @ENTRY_USER_ID
			BEGIN
				SET @APPROVAL_BR_CODE = @BR_CODE;
				SET @APPROVAL_USER_ID = @ENTRY_USER_ID;
			END
			--BEGIN TRY
			--	EXEC USP_CHECK_GLOBAL_APPROVAL_RIGHTS @APPROVAL_BR_CODE, @TRAN_DATE, @MENU_CODE, @TRAN_ID, @APPROVAL_USER_ID, 1, @MAX_APPROVAL_LEVEL OUTPUT, @TXN_LIST
			--	SET @IS_APPROVAL = 1;
			--END TRY
			--BEGIN CATCH
			--	SET @IS_APPROVAL = 0;
			--END CATCH
			EXEC USP_NESTED_CHECK_GLOBAL_APPROVAL_RIGHTS 
				@IS_CREATE = @IS_CREATE,
				@TRAN_DATE = @TRAN_DATE,
				@CREATION_BR_CODE = @BR_CODE,
				@APPROVAL_USER_ID = @APPROVAL_USER_ID,
				@APPROVAL_BR_CODE = @APPROVAL_BR_CODE,
				@MENU_CODE = @MENU_CODE,
				@TXN_LIST = @TXN_LIST,
				@HAS_APPROVAL_RIGHTS = @HAS_APPROVAL_RIGHTS OUTPUT -- FOR CREATE
				SET @IS_APPROVAL = @HAS_APPROVAL_RIGHTS;
			
			SELECT V.GL_CODE, AC.GL_NAME,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE,VCH_TYPE,'01' CUR_CODE
			FROM #VCH V
			INNER JOIN AC_CHART AC ON AC.GL_CODE=V.GL_CODE
		END
		ELSE
		BEGIN
			EXEC USP_CHECK_GLOBAL_APPROVAL_RIGHTS @APPROVAL_BR_CODE, @TRAN_DATE, @MENU_CODE, @TRAN_ID, @APPROVAL_USER_ID, 1, @MAX_APPROVAL_LEVEL OUTPUT, @TXN_LIST
			SET @IS_APPROVAL = 1;
		END
	END
END