CREATE  PROCEDURE USP_CBS_LoanDisbursement_Get_AcGroupList
(
	@INPUT VARCHAR(100)
)
AS
BEGIN

	SELECT AC_GROUP_CODE,AC_GROUP_NAME FROM AC_GROUP WITH(NOLOCK) 
	WHERE AC_TYPE_CODE = '04' AND APPROVED = 'YES' AND (AC_GROUP_CODE = @INPUT OR AC_GROUP_NAME LIKE @INPUT+'%')

END