CREATE  PROC USP_CBS_Get_Location_Data
(
	@TYPE VARCHAR(50),
	@DISTRICT_CODE VARCHAR(50)=NULL,
	@PROVINCE_ID VARCHAR(50)=NULL,
	@LOCAL_BODY_ID VARCHAR(50)=NULL
)
AS
BEGIN
	SET NOCOUNT ON;
	SET ARITHABORT ON;
	
	BEGIN TRY
		IF @TYPE='DIST_LIST'
		BEGIN
			SELECT DISTRICT_CODE,DISTRICT_NAME, ZONE_CODE, STATE_ID FROM DISTRICT WHERE APPROVED = 'YES'  
		END

		IF @TYPE='LB_BY_DIST'
		BEGIN
			IF NOT EXISTS(SELECT TOP 1 'X' FROM DISTRICT WHERE DISTRICT_CODE=@DISTRICT_CODE)
				THROW 50000, 'Warning -! Invalid District Code...!!!', 1;

			SELECT TRAN_ID LOCAL_BODY_ID, LOCAL_BODY_NAME, LOCAL_BODY_NAME_NEP, LOCAL_BODY_TYPE_ID, 
			(CASE WHEN LB.LOCAL_BODY_TYPE_ID=1 THEN 'Rural Municipality'
			  WHEN LB.LOCAL_BODY_TYPE_ID=2 THEN 'Municipality'
			  WHEN LB.LOCAL_BODY_TYPE_ID=3 THEN 'Sub Metropolitan'
			  WHEN LB.LOCAL_BODY_TYPE_ID=4 THEN 'Metropolitan' END) LOCAL_BODY_TYPE,
			LB.DISTRICT_CODE, D.DISTRICT_NAME 
			FROM LOCAL_BODY LB
			INNER JOIN DISTRICT D ON D.DISTRICT_CODE=LB.DISTRICT_CODE
			WHERE [STATUS] = 1  and LB.DISTRICT_CODE = @DISTRICT_CODE 
		END

		IF @TYPE='PROV_LIST'
		BEGIN
			SELECT TRAN_ID,STATE_NAME,STATE_NAME_NEP FROM STATE WHERE [STATUS]=1  
		END

		IF @TYPE='DIST_BY_PROV'
		BEGIN
			SET @PROVINCE_ID=TRY_CAST(@PROVINCE_ID as INT)
			IF NOT EXISTS(SELECT TOP 1 'X' FROM STATE WHERE [STATUS] = 1 AND TRAN_ID = @PROVINCE_ID)
				THROW 50000, 'Warning -! Invalid Province Id...!!!', 1;

			SELECT DISTRICT_CODE,DISTRICT_NAME, ZONE_CODE, STATE_ID FROM DISTRICT 
			WHERE APPROVED = 'YES' AND STATE_ID = @PROVINCE_ID 
		END

		IF @TYPE='DIST_PROV_BY_LB'
		BEGIN
			SET @LOCAL_BODY_ID=TRY_CAST(@LOCAL_BODY_ID as INT)
			IF NOT EXISTS(SELECT TOP 1 'X' FROM LOCAL_BODY WHERE [STATUS] = 1 AND TRAN_ID = @LOCAL_BODY_ID)
				THROW 50000, 'Warning -! Invalid Local Body Id...!!!', 1;

			SELECT D.DISTRICT_CODE, D.DISTRICT_NAME, D.STATE_ID, S.STATE_NAME, LB.TRAN_ID, LB.LOCAL_BODY_NAME
            FROM LOCAL_BODY LB 
            INNER JOIN DISTRICT D ON LB.DISTRICT_CODE=D.DISTRICT_CODE
            INNER JOIN [STATE] S ON S.TRAN_ID=D.STATE_ID
            WHERE LB.TRAN_ID=@LOCAL_BODY_ID AND LB.[STATUS]=1 AND D.APPROVED='YES' AND S.[STATUS]=1
		END

		IF @TYPE='LOCAL_BODY'
		BEGIN
			SELECT TRAN_ID LOCAL_BODY_ID,LOCAL_BODY_NAME,LOCAL_BODY_NAME_NEP, LOCAL_BODY_TYPE_ID,
			(CASE WHEN LB.LOCAL_BODY_TYPE_ID=1 THEN 'Rural Municipality'
			  WHEN LB.LOCAL_BODY_TYPE_ID=2 THEN 'Municipality'
			  WHEN LB.LOCAL_BODY_TYPE_ID=3 THEN 'Sub Metropolitan'
			  WHEN LB.LOCAL_BODY_TYPE_ID=4 THEN 'Metropolitan' END) LOCAL_BODY_TYPE,
			DBO.PROPERCASE(D.DISTRICT_NAME) DISTRICT_NAME,LB.DISTRICT_CODE
			FROM LOCAL_BODY LB
			INNER JOIN DISTRICT D ON D.DISTRICT_CODE=LB.DISTRICT_CODE
		END

	END TRY
	BEGIN CATCH
			;THROW;
	END CATCH
END
GO
