CREATE  PROCEDURE USP_CBS_LoanDisbursement_Get_CustomerFamilyMemberDetails
(
	  @CUSTOMER_CODE VARCHAR(50)
	, @RELATION_CODE VARCHAR(50) = NULL
)
AS
BEGIN

	DROP TABLE IF EXISTS #RESULT

	IF NOT EXISTS(SELECT TOP 1 'X' FROM CUSTOMER_MAST WHERE CUSTOMER_CODE=@CUSTOMER_CODE)
	BEGIN
		RAISERROR ('Warning - ! Invalid Customer Code...!!!',16,1);
		RETURN
	END

	IF NOT EXISTS(SELECT TOP 1 'X' FROM RELATION WHERE RELATION_CODE=@RELATION_CODE)
	BEGIN
		RAISERROR ('Warning - ! Invalid Relation Code...!!!',16,1);
		RETURN
	END

	CREATE TABLE #RESULT (NAME VARCHAR(250), DATE_OF_BIRTH DATE, GENDER_CODE VARCHAR(50), GENDER_NAME VARCHAR(250), CITIZENSHIP_NO VARCHAR(50), CITIZENSHIP_ISSUE_DISTRICT_CODE VARCHAR(50), CITIZENSHIP_ISSUE_DATE VARCHAR(10));

	DECLARE @SPOUSE_GENDER_CODE VARCHAR(50) = (SELECT TOP 1 GENDER_CODE FROM RELATION WHERE RELATION_CODE = @RELATION_CODE AND RELATION_CAT IN (3,4));
	IF (@SPOUSE_GENDER_CODE IS NOT NULL)
	BEGIN
	--NEW
		IF @SPOUSE_GENDER_CODE <> (SELECT TOP 1 GENDER_CODE FROM CUSTOMER_MAST WHERE CUSTOMER_CODE = @CUSTOMER_CODE)
		BEGIN
			INSERT INTO #RESULT ([NAME], DATE_OF_BIRTH, GENDER_CODE, GENDER_NAME, CITIZENSHIP_NO, CITIZENSHIP_ISSUE_DATE, CITIZENSHIP_ISSUE_DISTRICT_CODE)
			SELECT TOP 1 CFT.FULL_NAME , CFT.BIRTH_DATE , GENDER.GENDER_CODE, GENDER.GENDER_NAME, CFTI.IDENTITY_NO, CFTI.ISSUE_DATE,CFTI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE -- CM.SPOUSE_CITIZENSHIP_ISSUE_DIST_CODE
			FROM CUSTOMER_MAST CM
				INNER JOIN CUSTOMER_FAMILY_TREE CFT ON CFT.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT.RELATION_CODE=(CASE WHEN CM.GENDER_CODE = '01' THEN '01' ELSE '02' END) AND CFT.STATUS=1
				INNER JOIN GENDER ON GENDER.GENDER_CODE = ISNULL(CFT.GENDER_CODE, CASE WHEN CM.GENDER_CODE = '01' THEN '01' ELSE '02' END)
				LEFT OUTER JOIN CUSTOMER_FAMILY_TREE_IDENTITY CFTI ON CFTI.CUSTOMER_FAMILY_TREE_ID = CFT.TRAN_ID AND CFTI.STATUS=1
				LEFT OUTER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID = CFTI.IDENTITY_TYPE_ID AND IT.TRAN_ID=1 AND IT.STATUS=1
				LEFT OUTER JOIN IDENTITY_TYPE_ISSUE_OFFICE_TYPE ISSUE_OFFICE  ON ISSUE_OFFICE.TRAN_ID = IT.ISSUE_OFFICE_TYPE_ID AND ISSUE_OFFICE.STATUS=1
			WHERE CM.CUSTOMER_CODE = @CUSTOMER_CODE
		END
		ELSE
		BEGIN -- GET DATA OF CUSTOMER ITSELF
			INSERT INTO #RESULT ([NAME], DATE_OF_BIRTH, GENDER_CODE, GENDER_NAME, CITIZENSHIP_NO, CITIZENSHIP_ISSUE_DATE, CITIZENSHIP_ISSUE_DISTRICT_CODE)
			SELECT TOP 1 CM.FULL_NAME, CM.BIRTH_DATE, GENDER.GENDER_CODE, GENDER.GENDER_NAME, 
				CI.IDENTITY_NO	CITIZENSHIP_NO, CI.ISSUE_DATE CITIZENSHIP_ISSUE_DATE, CI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE CITIZENSHIP_ISSUE_DISTRICT
			FROM CUSTOMER_MAST CM
				LEFT OUTER JOIN CUSTOMER_IDENTITY CI ON CI.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CI.STATUS=1
				LEFT OUTER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID = CI.IDENTITY_TYPE_ID AND IT.TRAN_ID=1 AND IT.STATUS=1
				LEFT OUTER JOIN IDENTITY_TYPE_ISSUE_OFFICE_TYPE ISSUE_OFFICE  ON ISSUE_OFFICE.TRAN_ID = IT.ISSUE_OFFICE_TYPE_ID AND ISSUE_OFFICE.STATUS=1
				INNER JOIN GENDER ON GENDER.GENDER_CODE = ISNULL(CM.GENDER_CODE, CASE WHEN CM.GENDER_CODE = '01' THEN '02' ELSE '01' END)
			WHERE CM.CUSTOMER_CODE = @CUSTOMER_CODE
		END
	END
	ELSE IF EXISTS(SELECT TOP 1 1
					FROM CUSTOMER_FAMILY_TREE CFT
					WHERE ISNULL(CFT.CUSTOMER_CODE,'') = @CUSTOMER_CODE AND CFT.RELATION_CODE = @RELATION_CODE
						AND CFT.STATUS=1)
	BEGIN
		INSERT INTO #RESULT ([NAME], DATE_OF_BIRTH, GENDER_CODE, GENDER_NAME, CITIZENSHIP_NO, CITIZENSHIP_ISSUE_DATE, CITIZENSHIP_ISSUE_DISTRICT_CODE)
		SELECT TOP 1   COALESCE(CI.FULL_NAME,CFT.FULL_NAME,''),  COALESCE(CI.CUSTOMER_BIRTH_DATE,CFT.BIRTH_DATE,'')
			, GENDER.GENDER_CODE, GENDER.GENDER_NAME,  COALESCE(CI.CUSTOMER_CITIZENSHIP_NO, CFTI.IDENTITY_NO,'')
			, COALESCE(CI.CUSTOMER_CITIZENSHIP_ISSUE_DATE, CFTI.ISSUE_DATE, '')
			, COALESCE(CI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE ,CFTI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE,'') 
		FROM CUSTOMER_FAMILY_TREE CFT
			LEFT OUTER JOIN (SELECT CI.CUSTOMER_CODE,CM.FULL_NAME, CI.IDENTITY_TYPE_ID
								,CI.IDENTITY_NO CUSTOMER_CITIZENSHIP_NO
								,ISSUE_DATE CUSTOMER_CITIZENSHIP_ISSUE_DATE
								,CM.BIRTH_DATE CUSTOMER_BIRTH_DATE
								,CI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE
							FROM CUSTOMER_MAST CM
							LEFT OUTER JOIN CUSTOMER_IDENTITY CI ON CM.CUSTOMER_CODE = CI.CUSTOMER_CODE
							LEFT OUTER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID = CI.IDENTITY_TYPE_ID AND IT.TRAN_ID = 1 AND IT.STATUS=1
							LEFT OUTER JOIN IDENTITY_TYPE_ISSUE_OFFICE_TYPE ISSUE_OFFICE_C  ON ISSUE_OFFICE_C.TRAN_ID = IT.ISSUE_OFFICE_TYPE_ID AND ISSUE_OFFICE_C.STATUS=1
							)CI ON CI.CUSTOMER_CODE= cft.FAMILY_CUSTOMER_CODE

			LEFT OUTER JOIN CUSTOMER_FAMILY_TREE_IDENTITY CFTI ON CFTI.CUSTOMER_FAMILY_TREE_ID= CFT.TRAN_ID AND CFTI.STATUS=1
			LEFT OUTER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID = CFTI.IDENTITY_TYPE_ID AND IT.TRAN_ID=1 AND IT.STATUS=1
			INNER JOIN RELATION ON RELATION.RELATION_CODE = CFT.RELATION_CODE
			INNER JOIN GENDER ON GENDER.GENDER_CODE = RELATION.GENDER_CODE
		WHERE CFT.CUSTOMER_CODE = @CUSTOMER_CODE AND CFT.RELATION_CODE = @RELATION_CODE
	END
	ELSE IF EXISTS(SELECT TOP 1 'X' 
					FROM CUSTOMER_MAST CM
					INNER JOIN CUSTOMER_NOMINEE CN ON CM.CUSTOMER_CODE = CN.CUSTOMER_CODE AND CN.STATUS=1
					WHERE ISNULL(CN.NOMINEE_CUSTOMER_CODE,Cm.CUSTOMER_CODE) = @CUSTOMER_CODE AND CN.RELATION_CODE = @RELATION_CODE)
	BEGIN
		INSERT INTO #RESULT ([NAME], DATE_OF_BIRTH, GENDER_CODE, GENDER_NAME, CITIZENSHIP_NO, CITIZENSHIP_ISSUE_DATE, CITIZENSHIP_ISSUE_DISTRICT_CODE)
		SELECT TOP 1  CN.FULL_NAME, CN.BIRTH_DATE , GENDER.GENDER_CODE, GENDER.GENDER_NAME, CNI.IDENTITY_NO, CNI.ISSUE_DATE, CNI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE
		FROM CUSTOMER_MAST CM
			inner join Customer_Nominee CN on CN.customer_code = CM.Customer_code AND CN.STATUS=1
			LEFT OUTER JOIN CUSTOMER_NOMINEE_IDENTITY CNI ON CNI.CUSTOMER_NOMINEE_ID= CN.TRAN_ID AND CNI.STATUS=1
			LEFT OUTER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID = CNI.IDENTITY_TYPE_ID AND IT.TRAN_ID=1 AND IT.STATUS=1
			INNER JOIN RELATION ON RELATION.RELATION_CODE = CN.RELATION_CODE
			INNER JOIN GENDER ON GENDER.GENDER_CODE = RELATION.GENDER_CODE
		WHERE CM.CUSTOMER_CODE = @CUSTOMER_CODE AND RELATION.RELATION_CODE = @RELATION_CODE
	END
	ELSE
	BEGIN
		INSERT INTO #RESULT ([NAME], DATE_OF_BIRTH, GENDER_CODE, GENDER_NAME, CITIZENSHIP_NO, CITIZENSHIP_ISSUE_DATE, CITIZENSHIP_ISSUE_DISTRICT_CODE)
		SELECT FAM.FAM_MEM_NAME, FAM.FM_DOB, GENDER.GENDER_CODE, GENDER.GENDER_NAME, '', '', ''
		FROM CUST_SURVEY_TRAN_MAST MAST
			INNER JOIN CUST_FAMILY_DETL FAM ON MAST.TRAN_ID = FAM.MAST_TRAN_ID
			INNER JOIN GENDER ON FAM.GENDER_CODE  = GENDER.GENDER_CODE
		WHERE MAST.CUSTOMER_CODE = @CUSTOMER_CODE AND FAM.RELATION_CODE = @RELATION_CODE
	END

	SELECT TOP 1 ISNULL([NAME],'') [NAME], @RELATION_CODE RELATION_CODE, RL.RELATION_NAME RELATION_NAME,
	CONVERT(VARCHAR(10),DATE_OF_BIRTH,121)  DATE_OF_BIRTH,
	ISNULL(DT.NEP_DATE,'') DATE_OF_BIRTH_NEP,
	ISNULL(R.GENDER_CODE,'') GENDER_CODE, ISNULL(GENDER_NAME,'') GENDER_NAME, ISNULL(CITIZENSHIP_NO,'') CITIZENSHIP_NO, 
	ISNULL(CONVERT(VARCHAR(10),CITIZENSHIP_ISSUE_DATE,121),'') CITIZENSHIP_ISSUE_DATE,
	ISNULL(DT1.NEP_DATE,'') CITIZENSHIP_ISSUE_DATE_NEP,
	ISNULL(CITIZENSHIP_ISSUE_DISTRICT_CODE,'') CITIZENSHIP_ISSUE_DISTRICT_CODE,
	ISNULL(D.DISTRICT_NAME,'') CITIZENSHIP_ISSUE_DISTRICT_NAME
	FROM #RESULT R
	INNER JOIN RELATION RL ON RL.RELATION_CODE=@RELATION_CODE
	LEFT JOIN DISTRICT D ON D.DISTRICT_CODE=R.CITIZENSHIP_ISSUE_DISTRICT_CODE
	LEFT JOIN DATE_TABLE DT ON DT.ENG_DATE= R.DATE_OF_BIRTH
	LEFT JOIN DATE_TABLE DT1 ON DT1.ENG_DATE= R.CITIZENSHIP_ISSUE_DATE
END
--GO
--EXEC USP_CBS_LoanDisbursement_Get_CustomerFamilyMemberDetails @CUSTOMER_CODE='001000012',@RELATION_CODE='02'