CREATE  PROCEDURE USP_CBS_Get_CenterGroup
(
    @BR_CODE VARCHAR(50),
    @INPUT VARCHAR(100),
    @CENTER_CODE VARCHAR(50)='',
    @TYPE VARCHAR(50)
)
AS
BEGIN
    IF @TYPE='CENTER'
    BEGIN
        SELECT TOP 30 CENTER_CODE,CENTER_NAME FROM (
                                        SELECT C.CENTER_CODE,C.CENTER_NAME,ROW_NUMBER() OVER (PARTITION BY CSH.CENTER_CODE ORDER BY CSH.TRAN_ID DESC) RN FROM CENTER C WITH(NOLOCK)
                                        INNER JOIN CENTER_STATUS_HIST CSH WITH(NOLOCK) ON C.CENTER_CODE = CSH.CENTER_CODE AND C.BR_CODE = CSH.BR_CODE 
                                        WHERE C.APPROVED = 'YES' AND CSH.STATUS_CODE = '02' AND CSH.BR_CODE = @BR_CODE AND 
                                        (C.CENTER_CODE = @INPUT OR C.CENTER_NAME LIKE @INPUT+'%')) T WHERE T.RN = 1

    END
    ELSE --GROUP
    BEGIN
         SELECT TOP 30 GROUP_CODE,GROUP_NAME FROM (
                 SELECT CG.GROUP_CODE,CG.GROUP_NAME,ROW_NUMBER() OVER (PARTITION BY CGSH.GROUP_CODE ORDER BY CGSH.TRAN_ID DESC) RN FROM CENTER_GROUP CG WITH(NOLOCK)
                 INNER JOIN CENTER_GROUP_STATUS_HIST CGSH WITH(NOLOCK) ON CG.CENTER_CODE = CGSH.CENTER_CODE AND CG.GROUP_CODE = CGSH.GROUP_CODE
                 AND CG.BR_CODE = CGSH.BR_CODE WHERE CG.APPROVED = 'YES' AND CGSH.STATUS_CODE = '02' AND CGSH.BR_CODE = @BR_CODE 
                 AND CG.CENTER_CODE = @CENTER_CODE AND (CG.GROUP_CODE = @INPUT OR CG.GROUP_NAME LIKE @INPUT+'%')) T WHERE T.RN = 1
    END

END
--GO
--EXEC USP_GET_CENTER_GROUP '001','','0005',@TYPE='GROUP'