CREATE  PROC USP_CBS_Global_Get_DocTypes
AS    
BEGIN    

	SELECT DOC_CODE AS DOC_TYPE_ID ,DOC_TYPE_NAME, ISNULL(MAX_FILE_SIZE_IN_KB, 0) MAX_FILE_SIZE_IN_KB 
	FROM DOC_TYPE DT
	INNER JOIN (
	SELECT DOC_CODE_ID,IS_REQD_FOR_KYC,[STATUS],ROW_NUMBER() OVER(PARTITION BY  DOC_CODE_ID ORDER BY TRAN_ID DESC) RN 
	FROM DOC_TYPE_REQ_DETL) DD ON DD.DOC_CODE_ID = DT.DOC_CODE AND RN =1
	WHERE DD.[STATUS]=1 

END