CREATE  PROCEDURE USP_CBS_LoanDisbursement_Get_LoanAccountList
(
	@BR_CODE VARCHAR(50),
	@AC_GROUP_CODE VARCHAR(50),
	@CENTER_CODE VARCHAR(50),
	@GROUP_CODE VARCHAR(50),
	@SEARCH_BY VARCHAR(50)='',
	@INPUT VARCHAR(25),
	@ROW_COUNT INT,
	@SKIP_COUNT INT,
	@TOTAL_COUNT INT = 0 OUTPUT
)
AS
BEGIN
	IF ISNULL(@SEARCH_BY,'')=''
		SET @SEARCH_BY='FULL_NAME'

	DECLARE @TRAN_DATE DATE=(SELECT TOP 1 DATE FROM DAYEND WHERE BR_CODE=@BR_CODE ORDER BY DATE DESC)
	DROP TABLE IF EXISTS #LOAN_AC_TEMP;
	DROP TABLE IF EXISTS #TEMP_CUSTOMER_DETAIL_SEARCH

	SELECT  * INTO #TEMP_CUSTOMER_DETAIL_SEARCH FROM (
	SELECT  AHHM.AC_NO,CM.FULL_NAME,CM.CUSTOMER_CODE
			,ISNULL(CM_F.FULL_NAME, CFT_FATHER.FULL_NAME) FATHER_NAME 
		,CA.[ADDRESS] [ADDRESS]
		,DL.OLD_AC_NO
		,CENTER_CODE
		,GROUP_CODE
	FROM CUSTOMER_MAST CM WITH(NOLOCK)
		LEFT JOIN CUSTOMER_FAMILY_TREE CFT_FATHER WITH(NOLOCK) ON CFT_FATHER.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT_FATHER.RELATION_CODE= '06' and CFT_FATHER.STATUS=1
			LEFT OUTER JOIN CUSTOMER_MAST CM_F WITH(NOLOCK) ON CM_F.CUSTOMER_CODE = CFT_FATHER.FAMILY_CUSTOMER_CODE
		LEFT OUTER JOIN CUSTOMER_ADDRESS_VIEW CA WITH(NOLOCK) ON CM.CUSTOMER_CODE = CA.CUSTOMER_CODE AND CA.ADDRESS_TYPE = 4

		LEFT OUTER JOIN
			(SELECT BR_CODE,CUSTOMER_CODE,STATUS_CODE,CENTER_CODE,GROUP_CODE,ROW_NUMBER()OVER(PARTITION BY BR_CODE,CUSTOMER_CODE ORDER BY STATUS_CHG_DATE DESC,TRAN_ID DESC) RN
				FROM CUST_STATUS_HIST WITH(NOLOCK)
				WHERE STATUS_CHG_DATE<=@TRAN_DATE
			)CSH		 ON CSH.RN='1' AND CSH.BR_CODE=@BR_CODE AND CSH.CUSTOMER_CODE=CM.CUSTOMER_CODE
									   AND CSH.CENTER_CODE=(CASE WHEN @CENTER_CODE='' THEN CSH.CENTER_CODE ELSE @CENTER_CODE END)
									   AND CSH.GROUP_CODE=(CASE WHEN @GROUP_CODE='' THEN CSH.GROUP_CODE ELSE @GROUP_CODE END)
		INNER JOIN (
					SELECT AC_HOLDER_MAST_ID, CUSTOMER_CODE, ROW_NUMBER() OVER (PARTITION BY AC_HOLDER_MAST_ID ORDER BY IS_MASTER_AC_HOLDER DESC) RN FROM AC_HOLDER_DETL WITH(NOLOCK)
				) AHHD ON AHHD.RN = 1 AND AHHD.CUSTOMER_CODE = CM.CUSTOMER_CODE 
		INNER JOIN (
					SELECT BR_CODE, AC_NO, TRAN_ID, STATUS, ROW_NUMBER() OVER (PARTITION BY BR_CODE, AC_NO ORDER BY TRAN_DATE DESC) RN 
					FROM AC_HOLDER_MAST WITH(NOLOCK) WHERE ((STATUS_CHANGE_DATE IS NULL OR STATUS_CHANGE_DATE > @TRAN_DATE) OR [STATUS] = 1) and [STATUS] > 0 
				) AHHM ON AHHM.RN = 1 AND AHHM.TRAN_ID = AHHD.AC_HOLDER_MAST_ID 
		INNER JOIN 
			(
			 SELECT BR_CODE,AC_NO, OLD_AC_NO, AC_GROUP_CODE FROM LOAN_MAST WITH(NOLOCK) WHERE LOAN_STATUS='02' and  BR_CODE=@BR_CODE AND AC_GROUP_CODE=(CASE WHEN @AC_GROUP_CODE='' THEN AC_GROUP_CODE ELSE @AC_GROUP_CODE END)--ADD IF REQ
			)DL ON DL.BR_CODE=@BR_CODE AND AHHM.AC_NO=DL.AC_NO
	)T

	CREATE TABLE #LOAN_AC_TEMP(AC_NO VARCHAR(50),FULL_NAME VARCHAR(500), CUSTOMER_CODE VARCHAR(50),  FATHER_NAME VARCHAR(500), [ADDRESS] VARCHAR(800), OLD_AC_NO VARCHAR(50),CENTER_CODE VARCHAR(50),GROUP_CODE VARCHAR(50))

	INSERT INTO #LOAN_AC_TEMP
	EXEC('SELECT * FROM #TEMP_CUSTOMER_DETAIL_SEARCH WHERE '+@SEARCH_BY+' LIKE '''+@INPUT+'%''');

	SELECT AC_NO, DAM.FULL_NAME, DAM.CUSTOMER_CODE, ISNULL(FATHER_NAME,'') FATHER_NAME, ISNULL([ADDRESS],'') [ADDRESS], ISNULL(OLD_AC_NO,'') OLD_AC_NO, ISNULL(DAM.CENTER_CODE,'') CENTER_CODE, ISNULL(DAM.GROUP_CODE,'') GROUP_CODE,
	ISNULL(C.CENTER_NAME,'') CENTER_NAME, ISNULL(CG.GROUP_NAME,'') GROUP_NAME,
	ISNULL(CM.GENDER_CODE,'') GENDER_CODE, IS_MARRIED = CAST(CASE CM.MARITAL_STATUS_CODE WHEN '02' THEN 1 ELSE 0 END AS BIT)
	, ISNULL(CM.MARITAL_STATUS_CODE, '') MARITAL_STATUS
	, DATEDIFF(YY,BIRTH_DATE,@TRAN_DATE) AGE
	FROM #LOAN_AC_TEMP DAM
	LEFT OUTER JOIN CENTER C  ON C.BR_CODE=@BR_CODE AND C.CENTER_CODE=DAM.CENTER_CODE
	LEFT OUTER JOIN CENTER_GROUP CG  ON CG.BR_CODE=C.BR_CODE AND CG.CENTER_CODE=C.CENTER_CODE AND CG.GROUP_CODE=DAM.GROUP_CODE
	INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE=DAM.CUSTOMER_CODE
	ORDER BY DAM.CUSTOMER_CODE
	OFFSET @SKIP_COUNT ROWS
	FETCH NEXT @ROW_COUNT ROWS ONLY

	SET @TOTAL_COUNT =  (SELECT COUNT(1) FROM #LOAN_AC_TEMP)

	DROP TABLE #TEMP_CUSTOMER_DETAIL_SEARCH;
	DROP TABLE #LOAN_AC_TEMP;
END
--GO
--DECLARE @TOTAL_COUNT INT
--EXEC USP_CBS_LoanDisbursement_Get_LoanAccountList
--@BR_CODE ='001',@CENTER_CODE ='', @GROUP_CODE ='',
--@AC_GROUP_CODE ='',	@INPUT ='',@ROW_COUNT =100,@SKIP_COUNT =0, @SEARCH_BY='FULL_NAME',@TOTAL_COUNT=@TOTAL_COUNT OUTPUT
--SELECT @TOTAL_COUNT

