CREATE  PROCEDURE USP_CBS_TellerTransaction_Get_AccountList(

	@BR_CODE VARCHAR(50),
	@AC_GROUP_CODE VARCHAR(50),
	@CENTER_CODE VARCHAR(50),
	@GROUP_CODE VARCHAR(50),
	@SEARCH_BY VARCHAR(50)='',
	@INPUT VARCHAR(100),
	@ROW_COUNT INT,
	@SKIP_COUNT INT,
	@TOTAL_COUNT INT = 0 OUTPUT
)
AS
BEGIN
	SET ARITHABORT ON;
	DROP TABLE IF EXISTS #DAM_LM 
	DECLARE @EDATE DATE=(SELECT TOP 1 DATE FROM DAYEND WHERE BR_CODE=@BR_CODE ORDER  BY DATE DESC)

	IF ISNULL(@SEARCH_BY,'')=''
		SET @SEARCH_BY='FULL_NAME'

	CREATE TABLE #DAM_LM (
		AC_NO VARCHAR(50),
		BR_CODE VARCHAR(20),
		AC_NAME VARCHAR(500),
		MOBILE_NO VARCHAR(50),
		CUSTOMER_CODE VARCHAR(50),
		AC_GROUP_CODE VARCHAR(50),
		AC_GROUP_NAME VARCHAR(500),
		OLD_AC_NO Varchar(100)	
	);

	IF @SEARCH_BY ='FULL_NAME'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT TOP 500 DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
					FROM DEPOSIT_AC_MAST DAM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
					WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02'	
						AND DAM.AC_NAME LIKE @INPUT +'%'
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
				
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO, T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT TOP 500 LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
					FROM LOAN_MAST LM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
						AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
					WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02'
							AND Lm.AC_NAME LIKE @INPUT +'%'
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END 
	ELSE IF @SEARCH_BY ='OLD_AC_NO'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO, T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT TOP 500 DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
					FROM DEPOSIT_AC_MAST DAM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
					WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02'				
							AND DAM.OLD_AC_NO  LIKE  @INPUT +'%'
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT TOP 5000 LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
					FROM LOAN_MAST LM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
						AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
					WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02'
						AND LM.OLD_AC_NO  LIKE  @INPUT +'%'
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END
	ELSE IF @SEARCH_BY ='AC_NO'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
					FROM DEPOSIT_AC_MAST DAM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
					WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02' AND DAM.AC_NO = @INPUT			
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN 
					(SELECT LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
					FROM LOAN_MAST LM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
						AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
					WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02' AND LM.AC_NO = @INPUT
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END 
	ELSE IF @SEARCH_BY ='CUSTOMER_CODE'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO, T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID 
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE 
				INNER JOIN 
					(SELECT DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
					FROM DEPOSIT_AC_MAST DAM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
					WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02' 
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 and  CM.CUSTOMER_CODE = @INPUT
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID 
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE AND CM.CUSTOMER_CODE = @INPUT
				INNER JOIN 
					(SELECT LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
					FROM LOAN_MAST LM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
						AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
					WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02' 
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END 
	ELSE IF @SEARCH_BY ='MOBILE_NO'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID 
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE AND CM.MOBILE_NO = @INPUT
				INNER JOIN 
					(SELECT DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
					FROM DEPOSIT_AC_MAST DAM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
					WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02' 
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID
				INNER JOIN CUSTOMER_MAST CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE AND CM.MOBILE_NO = @INPUT
				INNER JOIN 
					(SELECT LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
					FROM LOAN_MAST LM
						INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
						AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
					WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02' 
					) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END
	ELSE IF @SEARCH_BY ='GRAND_FATHER_NAME'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO, T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID --AND AHHD.CUSTOMER_CODE = @INPUT
				INNER JOIN (SELECT TOP 500 CM.MOBILE_NO,CM.CUSTOMER_CODE ,ISNULL(CM_GF.FULL_NAME,CFT_GRANDFATHER.FULL_NAME) GRAND_FATHER_NAME
									FROM CUSTOMER_MAST CM 
									INNER JOIN CUSTOMER_FAMILY_TREE CFT_GRANDFATHER  ON CFT_GRANDFATHER.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT_GRANDFATHER.RELATION_CODE= '10'
										AND CFT_GRANDFATHER.STATUS=1
									LEFT OUTER JOIN CUSTOMER_MAST CM_GF  ON CM_GF.CUSTOMER_CODE = CFT_GRANDFATHER.FAMILY_CUSTOMER_CODE
							WHERE COALESCE(CM_GF.FULL_NAME,CFT_GRANDFATHER.FULL_NAME,@INPUT) LIKE @INPUT +'%'
							)CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
				INNER JOIN  (SELECT DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME,DAM.OLD_AC_NO
								FROM DEPOSIT_AC_MAST DAM
								INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE 
									AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
								WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02' 
								) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID-- AND AHHD.CUSTOMER_CODE = @INPUT
				INNER JOIN (SELECT TOP 500 CM.MOBILE_NO,CM.CUSTOMER_CODE ,ISNULL(CM_GF.FULL_NAME,CFT_GRANDFATHER.FULL_NAME) GRAND_FATHER_NAME
								FROM CUSTOMER_MAST CM 
								INNER JOIN CUSTOMER_FAMILY_TREE CFT_GRANDFATHER  ON CFT_GRANDFATHER.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT_GRANDFATHER.RELATION_CODE= '10'
									AND CFT_GRANDFATHER.STATUS=1
								LEFT OUTER JOIN CUSTOMER_MAST CM_GF  ON CM_GF.CUSTOMER_CODE = CFT_GRANDFATHER.FAMILY_CUSTOMER_CODE
							WHERE COALESCE(CM_GF.FULL_NAME,CFT_GRANDFATHER.FULL_NAME,@INPUT) LIKE @INPUT +'%'
							)CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE		
				INNER JOIN (SELECT LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
							FROM LOAN_MAST LM
								INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
								AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
							WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02' 
							) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END 
	ELSE IF @SEARCH_BY ='CITIZENSHIP_NO'
	BEGIN
		INSERT INTO #DAM_LM(AC_NO,BR_CODE,AC_NAME,MOBILE_NO,CUSTOMER_CODE,AC_GROUP_CODE,AC_GROUP_NAME,OLD_AC_NO)
		SELECT
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO, T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO,DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID --AND AHHD.CUSTOMER_CODE = @INPUT
				INNER JOIN (SELECT TOP 500 CM.MOBILE_NO,CM.CUSTOMER_CODE
							FROM CUSTOMER_MAST CM 
							INNER JOIN CUSTOMER_IDENTITY CI_C  ON CI_C.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CI_C.IDENTITY_TYPE_ID=1 AND CI_C.STATUS=1 and CI_C.IDENTITY_NO LIKE @INPUT +'%'
							)CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE
				INNER JOIN  (SELECT DAM.BR_CODE, DAM.AC_NO, DAM.AC_NAME, DAM.AC_GROUP_CODE, AG.AC_GROUP_NAME, DAM.OLD_AC_NO
								FROM DEPOSIT_AC_MAST DAM
								INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=DAM.AC_GROUP_CODE 
									AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
								WHERE DAM.BR_CODE=@BR_CODE AND DAM.APPROVED='YES' AND  DAM.RENEW='NO' AND DAM.AC_STATUS ='02' 
								) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
			WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
		UNION ALL
		SELECT 
			T.AC_NO,T.BR_CODE,T.AC_NAME,T.MOBILE_NO,T.CUSTOMER_CODE,T.AC_GROUP_CODE,T.AC_GROUP_NAME,T.OLD_AC_NO
		FROM (
			SELECT 
				DM.AC_NO,DM.BR_CODE,DM.AC_NAME,AHHD.CUSTOMER_CODE,DM.AC_GROUP_CODE,DM.AC_GROUP_NAME,
				ROW_NUMBER()OVER(PARTITION BY AHHM.AC_NO ORDER BY AHHM.TRAN_ID DESC)RN
				,CM.MOBILE_NO, DM.OLD_AC_NO
			FROM AC_HOLDER_MAST AHHM
				INNER JOIN AC_HOLDER_DETL AHHD ON AHHD.AC_HOLDER_MAST_ID=AHHM.TRAN_ID-- AND AHHD.CUSTOMER_CODE = @INPUT
				INNER JOIN (SELECT TOP 500 CM.MOBILE_NO,CM.CUSTOMER_CODE
							FROM CUSTOMER_MAST CM 
							INNER JOIN CUSTOMER_IDENTITY CI_C  ON CI_C.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CI_C.IDENTITY_TYPE_ID=1 AND CI_C.STATUS=1 and CI_C.IDENTITY_NO LIKE @INPUT +'%'
							)CM ON CM.CUSTOMER_CODE = AHHD.CUSTOMER_CODE		
				INNER JOIN (SELECT LM.BR_CODE, LM.AC_NO, LM.AC_NAME, LM.AC_GROUP_CODE, AG.AC_GROUP_NAME,LM.OLD_AC_NO
							FROM LOAN_MAST LM
								INNER JOIN AC_GROUP AG  ON AG.AC_GROUP_CODE=LM.AC_GROUP_CODE AND (CASE WHEN @AC_GROUP_CODE='' THEN @AC_GROUP_CODE ELSE AG.AC_GROUP_CODE END)=@AC_GROUP_CODE
								AND AG.AC_TYPE_SUB_TYPE_CODE='0401'
							WHERE  BR_CODE = @BR_CODE AND LM.APPROVED = 'YES' AND LOAN_STATUS='02' 
							) DM ON DM.AC_NO=AHHM.AC_NO AND DM.BR_CODE=AHHM.BR_CODE
				WHERE AHHM.[STATUS]=1 
		)T WHERE T.RN=1
	END 

	SELECT  CM.AC_NO,CM.AC_NAME AS FULL_NAME, CM.CUSTOMER_CODE
		,ISNULL(CM.MOBILE_NO,'') MOBILE_NO
		--,CITIZENSHIP_NO
		,COALESCE(CM_F.FULL_NAME, CFT_FATHER.FULL_NAME) FATHER_NAME
		,''MOTHER_NAME
		,ISNULL(CM_GF.FULL_NAME,CFT_GRANDFATHER.FULL_NAME) GRAND_FATHER_NAME
		,TEMPORARY_ADDRESS.[ADDRESS] AC_ADDRESS 
		,CM.OLD_AC_NO
		,AC_GROUP_CODE
		,AC_GROUP_NAME
	INTO #FINAL
	FROM #DAM_LM CM
	INNER JOIN (SELECT BR_CODE,CENTER_CODE,GROUP_CODE,STATUS_CODE,CUSTOMER_CODE
					,ROW_NUMBER()OVER(PARTITION BY CUSTOMER_CODE ORDER BY STATUS_CHG_DATE DESC,TRAN_ID DESC) RN
				FROM CUST_STATUS_HIST 
				WHERE STATUS_CHG_DATE<=@EDATE
				)CSH ON CSH.RN='1' AND CSH.STATUS_CODE='02' AND CSH.BR_CODE=CM.BR_CODE AND CSH.CUSTOMER_CODE=CM.CUSTOMER_CODE
					AND ISNULL(CSH.CENTER_CODE,'')=(CASE WHEN LEN(@CENTER_CODE)<=0 THEN ISNULL(CSH.CENTER_CODE,'') ELSE @CENTER_CODE END)
					AND ISNULL(CSH.GROUP_CODE,'')=(CASE WHEN LEN(@GROUP_CODE)<=0 THEN ISNULL(CSH.GROUP_CODE,'') ELSE @GROUP_CODE END)
	LEFT OUTER JOIN CUSTOMER_FAMILY_TREE CFT_FATHER  ON CFT_FATHER.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT_FATHER.RELATION_CODE= '06' AND CFT_FATHER.STATUS=1
	LEFT OUTER JOIN CUSTOMER_MAST CM_F  ON CM_F.CUSTOMER_CODE = CFT_FATHER.FAMILY_CUSTOMER_CODE
	LEFT OUTER JOIN CUSTOMER_ADDRESS_VIEW TEMPORARY_ADDRESS  ON CM.CUSTOMER_CODE = TEMPORARY_ADDRESS.CUSTOMER_CODE AND TEMPORARY_ADDRESS.ADDRESS_TYPE = 4
	LEFT OUTER JOIN CUSTOMER_FAMILY_TREE CFT_GRANDFATHER  ON CFT_GRANDFATHER.CUSTOMER_CODE= CM.CUSTOMER_CODE AND CFT_GRANDFATHER.RELATION_CODE= '10' AND CFT_GRANDFATHER.STATUS=1
	LEFT OUTER JOIN CUSTOMER_MAST CM_GF  ON CM_GF.CUSTOMER_CODE = CFT_GRANDFATHER.FAMILY_CUSTOMER_CODE

	SELECT ISNULL(AC_NO,'') AC_NO,	ISNULL(FULL_NAME,'') FULL_NAME,	ISNULL(CUSTOMER_CODE,'') CUSTOMER_CODE,	
	ISNULL(MOBILE_NO,'') MOBILE_NO,	ISNULL(FATHER_NAME,'') FATHER_NAME,	ISNULL(MOTHER_NAME,'') MOTHER_NAME,
	ISNULL(GRAND_FATHER_NAME,'') GRAND_FATHER_NAME,	ISNULL(AC_ADDRESS,'') AC_ADDRESS,	ISNULL(OLD_AC_NO,'') OLD_AC_NO,	AC_GROUP_CODE,AC_GROUP_NAME
	FROM #FINAL
	ORDER BY AC_NO
	OFFSET @SKIP_COUNT ROWS
	FETCH NEXT @ROW_COUNT ROWS ONLY

	SET @TOTAL_COUNT =  (SELECT COUNT(1) FROM #FINAL)


	DROP TABLE IF EXISTS #DAM_LM 
	DROP TABLE IF EXISTS #FINAL 

END
--GO
--DECLARE @TOTAL_COUNT INT
--EXEC USP_CBS_TellerTransaction_Get_AccountList
--	@BR_CODE ='001',
--	@CENTER_CODE ='',
--	@GROUP_CODE='',
--	@AC_GROUP_CODE ='',
--	@SEARCH_BY='MOBILE_NO',
--	@INPUT ='9841692786',
--	@ROW_COUNT =10,
--	@SKIP_COUNT =0,
--	@TOTAL_COUNT=@TOTAL_COUNT OUTPUT
--SELECT @TOTAL_COUNT