CREATE  PROCEDURE [dbo].[USP_CBS_TellerTransaction_Update]
(
	@TRAN_ID INT,
	@STATUS INT,
	@PREVIEW_ONLY BIT,
	@CENTER_CODE VARCHAR(30)=NULL,
	@GROUP_CODE VARCHAR(30)=NULL,
	@CUSTOMER_CODE VARCHAR(30),
	@BR_CODE VARCHAR(50),
	@AC_NO VARCHAR(50),
	@OPR_CODE VARCHAR(50),
	@TRAN_USER_ID VARCHAR(50),
	@TRAN_AMT DECIMAL(18,2),
	-- BANK
	@BANK_ALIAS VARCHAR(100) = NULL,
	@BANK_NOSTRO_AC_NO VARCHAR(50) = NULL,
	-- JOURNAL
	@JOURNAL_GL_CODE VARCHAR(50) = NULL,
	@JOURNAL_AC_NO VARCHAR(50) = NULL,
	-- INSTRUMENT
	@INST_NO VARCHAR(50) = NULL,
	@INST_CODE VARCHAR(50) = NULL,
	@INST_DATE DATE=NULL,

	@CHARGE_LIST AS TYPE_CBS_TellerTransaction_Charge READONLY,
	@DENO AS TYPE_CBS_TellerTransaction_Deno READONLY,
	--UI FIELDS
	@DESCRIPTION VARCHAR(256),
	@SOURCE_OF_FUND_ID INT = NULL, 
	@WDR_DEPOSITOR_NAME NVARCHAR(100),
	-- ABBS FIELDS
	@IS_ABBS BIT,
	@REF_BR_CODE VARCHAR(50),
	@BANK_BR_CODE VARCHAR(50)='',
	--source
	@SOURCE_BANK_BRCODE  VARCHAR(50)='',
	@SOURCE_AC_NO  VARCHAR(50)='',
	@SOURCE_CHQ_NO  VARCHAR(50)='',
	@SOURCE_CHQ_DATE DATE=null,
	@PURPOSE_OF_TRANSACTION  VARCHAR(250)='',
	--AML FIELDS
	@DRAWEE_FIRST_NAME varchar(50) = NULL,
	@DRAWEE_MIDDLE_NAME varchar(50) = NULL,
	@DRAWEE_LAST_NAME varchar(50) = NULL, 
	@DRAWEE_CUSTOMER_CODE varchar(50) = NULL,
	@CONDUCTOR_FIRST_NAME varchar(50) = NULL,
	@CONDUCTOR_MIDDLE_NAME varchar(50) = NULL,
	@CONDUCTOR_LAST_NAME varchar(50) = NULL,
	@CONDUCTOR_CONTACT_NO varchar(50) = NULL,
	@CONDUCTOR_CUSTOMER_CODE varchar(50) = NULL,
	@CONDUCTOR_MOTHER_NAME Varchar(50) = NULL,
	@CONDUCTOR_FATHER_NAME Varchar(50) = NULL,
	@CONDUCTOR_GRAND_FATHER_NAME Varchar(50) = NULL,
	@CONDUCTOR_DISTRICT_CODE Varchar(50) = NULL,
	@CONDUCTOR_TOLE_NAME Varchar(50) = NULL,
	@CONDUCTOR_BIRTH_DATE date = NULL,
	@CONDUCTOR_LOCAL_BODY_TYPE_ID int = NULL,
	@CONDUCTOR_LOCAL_BODY_CODE Varchar(50) = NULL,
	@CONDUCTOR_GENDER_CODE Varchar(10) = NULL,
	@CONDUCTOR_OCCUPATION_CODE Varchar(50) = NULL,
	@CONDUCTOR_IDENTITY_TYPE_ID int = NULL,
	@CONDUCTOR_IDENTITY_NO varchar(50) = NULL,
	@CONDUCTOR_IDENTITY_ISSUE_DATE date = NULL,
	@CONDUCTOR_IDENTITY_EXPIRY_DATE date = NULL,
	@CONDUCTOR_IDENTITY_ISSUE_PLACE varchar(100) = NULL,
	-- OUTPUT FIELDS
	@UPDATED_TRAN_ID INT = 0 OUTPUT,
	@NEW_VCH_NO VARCHAR(50) = NULL OUTPUT,
	@NEW_BAL DECIMAL(18,2) = NULL OUTPUT,
	@IS_APPROVAL BIT=0 OUTPUT,
	@REMAINING_APPROVAL_COUNT INT=0 OUTPUT,
	@MSG VARCHAR(250) = NULL OUTPUT
	
)
AS 
BEGIN
	SET NOCOUNT ON;
	SET ANSI_WARNINGS OFF;
	SET ARITHABORT ON;
	SET XACT_ABORT ON;
	BEGIN TRY
	SET @UPDATED_TRAN_ID=0;
	DECLARE @VALIDATE_KYC_FOR_TELLER_TRANSACTION BIT = 0;
	DECLARE @MENU_CODE BIGINT = 701;
	DECLARE @BANK_CODE VARCHAR(50) = (SELECT TOP 1 BANK_CODE FROM BANK WHERE BANK_ALIAS = @BANK_ALIAS);
	DECLARE @TRAN_DATE DATE=(SELECT TOP 1 DATE FROM DAYEND WHERE BR_CODE=@BR_CODE ORDER BY DATE DESC)
	DECLARE @SOURCE_TYPE_ID TINYINT, @SOURCE_TRAN_ID INT
	DECLARE @ENTRY_USER_ID VARCHAR(50)=(SELECT TOP 1 [USER_ID] FROM USERS WHERE LOGIN_NAME=@TRAN_USER_ID)
	
	IF @OPR_CODE NOT IN (SELECT OP_CODE FROM OPERATION_LIST)
	BEGIN
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_OPERATION'
	END
	SET @INST_DATE = NULLIF(@INST_DATE,'0001-01-01')
	SET @CONDUCTOR_IDENTITY_ISSUE_DATE = NULLIF(@CONDUCTOR_IDENTITY_ISSUE_DATE,'0001-01-01')
	SET @CONDUCTOR_IDENTITY_EXPIRY_DATE = NULLIF(@CONDUCTOR_IDENTITY_EXPIRY_DATE,'0001-01-01')
	SET @CONDUCTOR_BIRTH_DATE = NULLIF(@CONDUCTOR_BIRTH_DATE,'0001-01-01')
	
	SET @INST_DATE = NULLIF(@INST_DATE,'1900-01-01')
	SET @CONDUCTOR_IDENTITY_ISSUE_DATE = NULLIF(@CONDUCTOR_IDENTITY_ISSUE_DATE,'1900-01-01')
	SET @CONDUCTOR_IDENTITY_EXPIRY_DATE = NULLIF(@CONDUCTOR_IDENTITY_EXPIRY_DATE,'1900-01-01')
	SET @CONDUCTOR_BIRTH_DATE = NULLIF(@CONDUCTOR_BIRTH_DATE,'0001-01-01')

	DECLARE @DR_CR VARCHAR(2);
	SET @DR_CR=(SELECT TOP 1 DR_CR FROM OPERATION_LIST WHERE OP_CODE=@OPR_CODE)
	IF @DR_CR NOT IN ('DR', 'CR')
	BEGIN
		--THROW 50000, 'Warning - ! Invalid Operation...!!!', 1 ;
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_OPERATION'
	END
	DECLARE @AC_NAME VARCHAR(50);

	SELECT TOP 1 @AC_NAME = AC_NAME
	FROM (
		SELECT TOP 1 AC_NAME FROM LOAN_MAST WHERE AC_NO = @AC_NO
		UNION ALL
		SELECT TOP 1 AC_NAME FROM DEPOSIT_AC_MAST WHERE AC_NO = @AC_NO
	) AS AC;
	--START VALIDATION	

	-------------------------------------limit validation -----------------------------------------------
	DECLARE @DR_AMT DECIMAL(18,2) , @CR_AMT DECIMAL(18,2),@AGAINST_AC VARCHAR(50) = CASE WHEN @SOURCE_AC_NO IS NULL OR @SOURCE_AC_NO = '' THEN   @JOURNAL_AC_NO ELSE   @SOURCE_AC_NO END 	
	SELECT @DR_AMT= CASE WHEN @DR_CR = 'DR' THEN @TRAN_AMT ELSE 0 END, @CR_AMT= CASE WHEN @DR_CR = 'CR' THEN @TRAN_AMT ELSE 0 END	
	
	EXEC USP_TELLER_TRANSACTION_DEPOSIT_WITHDRAW_LIMIT_VALIDATION @AC_NO =@AC_NO,@TRAN_DATE =@TRAN_DATE,@DR_TRAN_AMT=@DR_AMT,@CR_TRAN_AMT=@CR_AMT
	
	IF @OPR_CODE = '12' OR @OPR_CODE='14' OR @OPR_CODE='15'
	BEGIN 
	SELECT @CR_AMT= CASE WHEN @DR_CR = 'DR' THEN @TRAN_AMT ELSE 0 END, @DR_AMT= CASE WHEN @DR_CR = 'CR' THEN @TRAN_AMT ELSE 0 END		
	EXEC USP_TELLER_TRANSACTION_DEPOSIT_WITHDRAW_LIMIT_VALIDATION @AC_NO =@AGAINST_AC,@TRAN_DATE =@TRAN_DATE,@DR_TRAN_AMT=@DR_AMT,@CR_TRAN_AMT=@CR_AMT
	END 
   ----------------------------------------------------------------------------------------------------------
	--ACTION_OPT C:CURRENT,D:DAYEND,R:READINESS,P:POSTPONE
	IF ISNULL((SELECT COUNT(BR_CODE) FROM DAYEND WHERE (BR_CODE=@BR_CODE) AND DATE=@TRAN_DATE AND DAYEND.ACTION_OPT IN ('C','P')),0)<>1
	BEGIN
		--THROW 50000, 'Warning - ! Invalid Transaction Date...!!!', 1;
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_DATE'
	END

	--LENGTH VALIDATION FOR DESCRIPTION
	DECLARE @DESC_LEN_COUNT INT = (SELECT LEN(@DESCRIPTION));
	IF @DESC_LEN_COUNT > 200
	BEGIN
		--THROW 50000, 'Warning - ! Description length exceeded, must be less or equal to 200...!!!', 1;
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_DESC_LENGTH'
	END
	
    IF @TRAN_ID > 0 AND @PREVIEW_ONLY = 1
	BEGIN
		SET @BR_CODE = (SELECT TOP 1 BR_CODE FROM TELLER_TRAN_DETL WHERE TRAN_ID = @TRAN_ID);
		SET @IS_ABBS = CASE WHEN @BR_CODE <> @REF_BR_CODE THEN 1 ELSE 0 END;
	END

	IF @REF_BR_CODE<>'' AND @IS_ABBS=1 AND ISNULL((SELECT COUNT(BR_CODE) FROM DAYEND WHERE (BR_CODE=@REF_BR_CODE) AND [DATE]=@TRAN_DATE AND DAYEND.ACTION_OPT IN ('C','P')),0)<>1
	BEGIN
		--THROW 50000, 'Warning - ! Invalid Reference Branch Transaction Date...!!!', 1;
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_REF_BR_DATE'
	END
	
	--VALIDATION FOR KYC FAILED BLOCK--
	IF((SELECT DBO.GET_KYC_TRANSACTION_BLOCK_STATUS(@TRAN_DATE,@CUSTOMER_CODE))=1)
	BEGIN
		--THROW 50000, 'Warning - ! KYC Update Failed. Transaction Blocked. Please update KYC information before proceeding ...!!!', 1;
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_KYC_BLOCK'
	END


	IF (SELECT IS_AML_MODULE_USED FROM GLOBAL_SETUP	 )=1
	BEGIN
		IF ( ISNULL(@CONDUCTOR_FIRST_NAME,'')<>'') AND @OPR_CODE IN ('06','07','08')
				AND (ISNULL(@DRAWEE_FIRST_NAME,'')='') and (SELECT CUSTOMER_LEGAL_SCOPE FROM CUSTOMER_MAST WHERE CUSTOMER_CODE=@CUSTOMER_CODE) = 2 
		BEGIN
			--THROW 50000, 'Warning - ! Drawee is mandatory for corporate customers in withdrawal operations...!!!', 1;
			EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_DRAWEE_MANDATORY'
		END

		DECLARE @ERR_CONDUCTOR VARCHAR(100);
		IF(SELECT CUSTOMER_LEGAL_SCOPE FROM CUSTOMER_MAST WHERE CUSTOMER_CODE=@CONDUCTOR_CUSTOMER_CODE) = 2  
		BEGIN
			--;THROW 50000, 'Warning - ! Corporate Cannot Be Conductor...!!!', 1;
			EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_CORPORATE', @PARAM0='Conductor'
		END

		IF(SELECT CUSTOMER_LEGAL_SCOPE FROM CUSTOMER_MAST WHERE CUSTOMER_CODE=@DRAWEE_CUSTOMER_CODE) = 2  and @OPR_CODE in ('06','07','08')	
		BEGIN
			--;THROW 50000, 'Warning - ! Corporate Cannot Be Drawee for withdrawal operations...!!!', 1;		
			EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_CORPORATE', @PARAM0='Drawee for withdrawal operations'
		END
	END

	-----------------------CUSTOMER KYC VALIDATION----------------------------------------------

	SELECT @VALIDATE_KYC_FOR_TELLER_TRANSACTION = VALIDATE_KYC_FOR_TELLER_TRANSACTION FROM GLOBAL_SETUP

	IF @VALIDATE_KYC_FOR_TELLER_TRANSACTION =1 AND @PREVIEW_ONLY = 0
	BEGIN
		-- VALIDATE KYC 
		EXEC USP_VERIFY_KYC_CUSTOMERWISE @CUSTOMER_CODE=@CUSTOMER_CODE

	END
 
	DECLARE @CURRENT_STATUS INT = (SELECT TOP 1 [STATUS] FROM TELLER_TRAN_DETL WHERE TRAN_ID = @TRAN_ID);
	DECLARE @VCH AS TYPE_CBS_Voucher, @MAX_APPROVAL_COUNT INT;
	DROP TABLE IF EXISTS #VCH
	CREATE TABLE #VCH (GL_CODE VARCHAR(50),AC_NO VARCHAR(50),DESC1 VARCHAR(8000),AMT DECIMAL(18,2),BR_CODE VARCHAR(50),INST_CODE VARCHAR(50),INST_NO VARCHAR(50),INST_DATE DATE, VCH_TYPE INT,SOURCE_TYPE_ID TINYINT,SOURCE_TRAN_ID INT)
	
	IF @PREVIEW_ONLY = 1
	BEGIN	
		EXEC USP_CBS_TellerTransaction_GenerateVoucher @TRAN_ID, @STATUS, @PREVIEW_ONLY, @CENTER_CODE, @GROUP_CODE, @CUSTOMER_CODE, @BR_CODE, @AC_NO, @AC_NAME, @OPR_CODE, @TRAN_DATE, @ENTRY_USER_ID, @TRAN_AMT, @BANK_CODE, @BANK_NOSTRO_AC_NO, @JOURNAL_GL_CODE, @JOURNAL_AC_NO, @INST_NO, @INST_CODE, @INST_DATE, @DENO, @CHARGE_LIST, @DESCRIPTION, @SOURCE_OF_FUND_ID, @WDR_DEPOSITOR_NAME, @IS_ABBS, @REF_BR_CODE,@BANK_BR_CODE,@SOURCE_BANK_BRCODE,@SOURCE_AC_NO,@SOURCE_CHQ_NO,@SOURCE_CHQ_DATE, @ENTRY_USER_ID, @BR_CODE, @NEW_VCH_NO, @NEW_BAL OUTPUT, @IS_APPROVAL OUTPUT, @MAX_APPROVAL_COUNT OUTPUT
	END
	IF @PREVIEW_ONLY = 0
	BEGIN
		IF EXISTS (SELECT TOP 1 1 FROM OPERATION_LIST WHERE OP_CODE=@OPR_CODE AND CASH_CONTRA=1)
		BEGIN
			IF (SELECT TOP 1 IS_DENO_MANDATORY_IN_TELLER FROM GLOBAL_SETUP) = 1 AND NOT EXISTS (SELECT TOP 1 1 FROM @DENO)
			BEGIN
				--;THROW 50000, 'Warning - ! Denomination is mandatory. Please enter the denomination before proceeding...!!!', 1;
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_DENO_MANDATORY'				
			END
		END
		DECLARE @SOURCE_OF_FUND_MANDATORY_AMOUNT DECIMAL(18,2) = ISNULL((SELECT MINIMUM_TRAN_AMOUNT_FOR_MANDATORY_SOURCE_OF_FUND FROM GLOBAL_SETUP ),0)
	
		IF @SOURCE_OF_FUND_MANDATORY_AMOUNT>0 AND @SOURCE_OF_FUND_MANDATORY_AMOUNT<@TRAN_AMT AND ISNULL(@SOURCE_OF_FUND_ID,0)<=0 AND @OPR_CODE in ('01','09','10','12')
		BEGIN 
			--;THROW 50000, 'Warning - ! Source of Fund is not defined...!!!', 1;
			EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_SOURCE_FUND'	
		END

		EXEC USP_CBS_TellerTransaction_GenerateVoucher @TRAN_ID, @STATUS, @PREVIEW_ONLY, @CENTER_CODE, @GROUP_CODE, @CUSTOMER_CODE, @BR_CODE, @AC_NO, @AC_NAME, @OPR_CODE, @TRAN_DATE, @ENTRY_USER_ID, @TRAN_AMT, @BANK_CODE, @BANK_NOSTRO_AC_NO, @JOURNAL_GL_CODE, @JOURNAL_AC_NO, @INST_NO, @INST_CODE, @INST_DATE, @DENO, @CHARGE_LIST, @DESCRIPTION, @SOURCE_OF_FUND_ID, @WDR_DEPOSITOR_NAME, @IS_ABBS, @REF_BR_CODE,@BANK_BR_CODE,@SOURCE_BANK_BRCODE,@SOURCE_AC_NO,@SOURCE_CHQ_NO,@SOURCE_CHQ_DATE, @ENTRY_USER_ID, @BR_CODE, @NEW_VCH_NO, @NEW_BAL OUTPUT, @IS_APPROVAL OUTPUT, @MAX_APPROVAL_COUNT OUTPUT
		
		INSERT INTO @VCH(GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE,VCH_TYPE)
		SELECT AC.GL_CODE,AC_NO,DESC1,AMT,BR_CODE,INST_CODE,INST_NO,INST_DATE,VCH_TYPE
		FROM #VCH VCH 
			INNER JOIN AC_CHART AC ON VCH.GL_CODE=AC.GL_CODE AND AC.APPROVED='YES' AND AC.LEDGER='YES' 
		

		DECLARE @TXN_LIST AS TYPE_CBS_GlTransaction;
		INSERT INTO @TXN_LIST (GL_CODE, AMOUNT)
		SELECT AC.GL_CODE, VCH.AMT AMOUNT
		FROM #VCH VCH
			INNER JOIN AC_CHART AC ON VCH.GL_CODE=AC.GL_CODE AND AC.APPROVED='YES' AND AC.LEDGER='YES' 
		
		DECLARE @IN_OUT VARCHAR(50),@CASH_AMT DECIMAL(18,2)=0
			
		DECLARE @COA_TRAN_ID VARCHAR(50), @AC_GROUP_CODE VARCHAR(50), @IS_LOAN_AC BIT = 0;
		SELECT @AC_GROUP_CODE=AC_GROUP_CODE,@IS_LOAN_AC=1 FROM LOAN_MAST WHERE AC_NO=@AC_NO AND BR_CODE=@REF_BR_CODE
		IF @IS_LOAN_AC=0 AND (@AC_GROUP_CODE='' OR @AC_GROUP_CODE IS NULL)
		BEGIN
			SELECT @AC_GROUP_CODE=AC_GROUP_CODE FROM DEPOSIT_AC_MAST WHERE BR_CODE=@REF_BR_CODE AND AC_NO=@AC_NO
		END
		
		--CHECK USER GROUP RIGHTS AND AC GROUP RIGHTS  -- FOR SAVE ONLY
		IF @PREVIEW_ONLY = 0 
		BEGIN
			EXEC USP_CHECK_MENU_AC_RIGHTS @BR_CODE =@BR_CODE , @AC_GROUP_CODE = @AC_GROUP_CODE
										, @MENU_CODE =@MENU_CODE, @TRAN_DATE =@TRAN_DATE , @TRAN_USER_ID =@ENTRY_USER_ID
										, @IS_SAVE= 1 , @IS_APPROVE= 0
		END

		IF (@OPR_CODE='06'OR @OPR_CODE='07'OR @OPR_CODE='08'OR @OPR_CODE='11' )
		BEGIN
            
			--=================BLOCK DEBIT TRANSACTION ON STAFF DEPOSIT IF LOAN OVERDUE ==============================================
			DECLARE @CHECK_LOAN_DUE BIT = (SELECT BLOCK_DEBIT_TRANSACTION_ON_STAFF_DEPOSIT_IF_LOAN_OVERDUE FROM GLOBAL_SETUP)
			IF @CHECK_LOAN_DUE = 1
			BEGIN
				-- Pass Branch Code, Account Number and Amount to validation procedure using Table Type
				-- Declare @Table Type and Insert Values to it
				DECLARE @TT TYPE_CBS_BrCodeAcNoDrAmt
				INSERT INTO @TT(BR_CODE, AC_NO, DR_AMT)
				SELECT @BR_CODE, @AC_NO ,@TRAN_AMT 

				DECLARE @IS_DUE BIT  
				EXEC USP_CHECK_LOAN_DUE @TO_EDATE=@TRAN_DATE, @PREVIOUS_DUE = N'1', @TT = @TT, @IS_DUE = @IS_DUE OUTPUT
				IF @IS_DUE = 1
				BEGIN
					--RAISERROR('Warning - ! Kindly Settle The Due Loan Amount to Proceed For Withdrawal.',16,1);
					EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_LOAN_DUE_SETTLE'	
				END
			END


			DECLARE @ID INT = ISNULL((SELECT TOP 1 TRAN_ID 
				FROM TELLER_TRAN_DETL
				WHERE AC_NO =@AC_NO AND [STATUS] IN (0,7)),0)
			IF ISNULL(@ID,'')<> '' AND @PREVIEW_ONLY=0
			BEGIN
				DECLARE @BR_NAME VARCHAR(500)=ISNULL((SELECT B.BR_NAME FROM TELLER_TRAN_DETL TD 
						INNER JOIN BRANCH B ON TD.BR_CODE=B.BR_CODE WHERE TD.TRAN_ID=@ID),'');
				--SET @MSG ='Warning - ! Account no already exist in approval flow in ' +@BR_NAME+ ' branch ...!!!';
				--RAISERROR (@MSG,16,1); --XX TO DO CHECK STATUS FOR 
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_AC_IN_APPROVAL_FLOW', @PARAM0 = @BR_NAME	
				--RETURN
			END
		END
		IF (@OPR_CODE='14' OR @OPR_CODE='15')
		BEGIN
			DECLARE @ID1 INT = ISNULL((SELECT TOP 1 TRAN_ID 
				FROM TELLER_TRAN_DETL
				WHERE SOURCE_AC_NO =@SOURCE_AC_NO AND [STATUS] IN (0,7)),0)
			IF ISNULL(@ID1,'')<> '' AND @PREVIEW_ONLY=0
			BEGIN
				DECLARE @BR_NAME1 VARCHAR(500)=ISNULL((SELECT B.BR_NAME FROM TELLER_TRAN_DETL TD 
						INNER JOIN BRANCH B ON TD.BR_CODE=B.BR_CODE WHERE TD.TRAN_ID=@ID1),'');
				--DECLARE @MSG1 VARCHAR(5000)='Warning - ! Account no already exist in approval flow in ' +@BR_NAME1+ ' branch ...!!!';
				--RAISERROR (@MSG1,16,1); --XX TO DO CHECK STATUS FOR 
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_AC_IN_APPROVAL_FLOW', @PARAM0 = @BR_NAME1	
				RETURN
			END
			
			IF EXISTS(SELECT TOP 1 1 FROM DEPOSIT_AC_MAST  DAM
					  INNER JOIN AC_GROUP AG ON AG.AC_GROUP_CODE= DAM.AC_GROUP_CODE AND AC_TYPE_CODE ='03' AND AC_TYPE_SUB_TYPE_CODE ='0303'
					  WHERE AC_NO=@SOURCE_AC_NO)
			BEGIN
				--DECLARE @MSG0 VARCHAR(5000)='Warning - ! Invalid withdraw of Recurring Deposit Account. Account No: ' + @SOURCE_AC_NO + ' ...!!!';
				--RAISERROR (@MSG0,16,1);
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_RD_WITHDRAW', @PARAM0 = @SOURCE_AC_NO	
				RETURN
			END
		END

		IF (@OPR_CODE='12') 
		BEGIN
			DECLARE @ID2 INT = ISNULL((SELECT TOP 1 TRAN_ID 
				FROM TELLER_TRAN_DETL
				WHERE (REF_AC_NO = @JOURNAL_AC_NO OR AC_NO = @JOURNAL_AC_NO) AND [STATUS] IN (0,7)),0)
			IF ISNULL(@ID2,'')<> '' AND @PREVIEW_ONLY=0
			BEGIN
				DECLARE @BR_NAME2 VARCHAR(500)=ISNULL((SELECT B.BR_NAME FROM TELLER_TRAN_DETL TD 
						INNER JOIN BRANCH B ON TD.BR_CODE=B.BR_CODE WHERE TD.TRAN_ID=@ID2),'');
				--DECLARE @MSG2 VARCHAR(5000)='Warning - ! Account no already exist in approval flow in ' +@BR_NAME2+ ' branch ...!!!';
				--RAISERROR (@MSG2,16,1);
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_AC_IN_APPROVAL_FLOW', @PARAM0 = @BR_NAME2	
				RETURN
			END
		END
		
		SELECT @SOURCE_TYPE_ID = SOURCE_TYPE_ID, @SOURCE_TRAN_ID = SOURCE_TRAN_ID
		FROM (
				SELECT 3 AS SOURCE_TYPE_ID, ID AS SOURCE_TRAN_ID FROM DEPOSIT_AC_MAST WHERE AC_NO = @AC_NO AND BR_CODE = @BR_CODE
				UNION ALL
				SELECT 4 AS SOURCE_TYPE_ID, ID AS SOURCE_TRAN_ID FROM LOAN_MAST WHERE AC_NO = @AC_NO AND BR_CODE = @BR_CODE
			)AC


		BEGIN TRANSACTION
			DECLARE @BANK_GL_CODE_TTD varchar(100);
			SET @BANK_GL_CODE_TTD = (SELECT TOP 1 GL_CODE FROM AC_CHART WHERE BANK_GL_CODE=@JOURNAL_GL_CODE)

			IF @TRAN_ID = 0
			BEGIN
				INSERT INTO TELLER_TRAN_DETL (BR_CODE,VALUE_DATE,REF_BR_CODE,OPR_CODE,CENTER_CODE,GROUP_CODE,CUSTOMER_CODE,COA_TRAN_ID,AC_GROUP_CODE,GL_CODE,BANK_CODE,AC_NO, REF_AC_NO
												,TRAN_AMOUNT,DESC1,INST_DATE,INST_CODE,INST_NO,SOURCE_OF_FUND_ID,WDR_DEPOSITOR_NAME,VCH_NO,TRAN_USER_ID,TRAN_DATE,STATUS,STATUS_CHANGE_DATE
												,STATUS_CHANGE_USER_ID,SOURCE_AC_NO,SOURCE_CHQ_NO,SOURCE_CHQ_DATE, 
												--PURPOSE_OF_TRANSACTION,
												SOURCE_TYPE_ID, SOURCE_TRAN_ID)
				VALUES (@BR_CODE,@TRAN_DATE,@REF_BR_CODE,@OPR_CODE,@CENTER_CODE,@GROUP_CODE,@CUSTOMER_CODE,@COA_TRAN_ID,@AC_GROUP_CODE,isnull(@BANK_GL_CODE_TTD, ''),@BANK_CODE,@AC_NO, (CASE WHEN @OPR_CODE IN ('08','09','13') THEN  @BANK_NOSTRO_AC_NO ELSE ISNULL(@JOURNAL_AC_NO,@BANK_NOSTRO_AC_NO) END),@TRAN_AMT,@DESCRIPTION
					,(CASE WHEN @OPR_CODE ='06' OR @OPR_CODE ='08' OR @OPR_CODE ='09' OR @OPR_CODE ='12' THEN  @INST_DATE ELSE NULL END)
					,@INST_CODE
					,(CASE WHEN @OPR_CODE ='14' OR @OPR_CODE ='15' THEN  ''  ELSE @INST_NO END)
					,@SOURCE_OF_FUND_ID,@WDR_DEPOSITOR_NAME,@NEW_VCH_NO,@ENTRY_USER_ID,@TRAN_DATE,@STATUS,@TRAN_DATE,@ENTRY_USER_ID
					,@SOURCE_AC_NO
					,(CASE WHEN @OPR_CODE ='14'   THEN  @INST_NO  
							WHEN @OPR_CODE ='08' OR @OPR_CODE ='15' THEN  @SOURCE_CHQ_NO  ELSE NULL END)
					,(CASE WHEN @OPR_CODE ='14'  OR @OPR_CODE ='15' THEN  @INST_DATE  
							WHEN @OPR_CODE ='08'THEN  @SOURCE_CHQ_DATE  ELSE NULL END)
					--,@PURPOSE_OF_TRANSACTION
					, @SOURCE_TYPE_ID, @SOURCE_TRAN_ID
					)
				SET @TRAN_ID = SCOPE_IDENTITY();
				IF @STATUS = 0
				BEGIN
					EXEC USP_CREATE_TRANSACTION_LOG @MENU_CODE = @MENU_CODE, @BR_CODE = @BR_CODE, @TRAN_OPTION = 'N', @SOURCE_TABLE_NAME = 'TELLER_TRAN_DETL', @SOURCE_TABLE_TRAN_ID = @TRAN_ID, @TRAN_USER_ID = @ENTRY_USER_ID, @TRAN_DATE = @TRAN_DATE,@TXN_LIST=@TXN_LIST
				END
			END
			ELSE
			BEGIN
				UPDATE TELLER_TRAN_DETL
				SET 
					BR_CODE = @BR_CODE,
					VALUE_DATE = @TRAN_DATE,
					REF_BR_CODE = @REF_BR_CODE,
					OPR_CODE = @OPR_CODE,
					CENTER_CODE = @CENTER_CODE,
					GROUP_CODE = @GROUP_CODE,
					CUSTOMER_CODE = @CUSTOMER_CODE,
					AC_GROUP_CODE = @AC_GROUP_CODE,
					AC_NO = @AC_NO,
					COA_TRAN_ID = @COA_TRAN_ID,
					GL_CODE = ISNULL(@BANK_GL_CODE_TTD, ''),
					BANK_CODE = @BANK_CODE,
					REF_AC_NO = (CASE WHEN @OPR_CODE IN ('08','09','13') THEN  @BANK_NOSTRO_AC_NO ELSE ISNULL(@JOURNAL_AC_NO,@BANK_NOSTRO_AC_NO) END),--ISNULL(@JOURNAL_AC_NO, @BANK_NOSTRO_AC_NO),
					TRAN_AMOUNT = @TRAN_AMT,
					DESC1 = @DESCRIPTION,
					INST_DATE = (CASE WHEN @OPR_CODE ='06' OR @OPR_CODE ='08' OR @OPR_CODE ='09' OR @OPR_CODE ='12' THEN  @INST_DATE ELSE NULL END),
					INST_CODE = @INST_CODE,
					INST_NO = @INST_NO,
					SOURCE_OF_FUND_ID = @SOURCE_OF_FUND_ID,
					WDR_DEPOSITOR_NAME = @WDR_DEPOSITOR_NAME,
					[STATUS] = @STATUS,
					SOURCE_CHQ_DATE = (CASE WHEN @OPR_CODE ='14'  OR @OPR_CODE ='15' THEN  @INST_DATE   WHEN @OPR_CODE ='08'THEN  @SOURCE_CHQ_DATE  ELSE NULL END),
					SOURCE_CHQ_NO = (CASE WHEN @OPR_CODE ='14'   THEN  @INST_NO   WHEN @OPR_CODE ='08' OR @OPR_CODE ='15' THEN  @SOURCE_CHQ_NO  ELSE NULL END),
					SOURCE_AC_NO= @SOURCE_AC_NO,
					--PURPOSE_OF_TRANSACTION= @PURPOSE_OF_TRANSACTION,
					SOURCE_TYPE_ID = @SOURCE_TYPE_ID,
					SOURCE_TRAN_ID = @SOURCE_TRAN_ID
				WHERE TRAN_ID = @TRAN_ID
					AND [STATUS] IN (-2,-1,0)

				DELETE FROM TELLER_TRAN_DETL_CHARGE WHERE TELLER_TRAN_DETL_ID = @TRAN_ID
				DELETE FROM TELLER_TRAN_DETL_DENO WHERE TELLER_TRAN_DETL_ID = @TRAN_ID
				DELETE FROM TELLER_TRAN_AML_INFO WHERE TELLER_TRAN_DETL_ID = @TRAN_ID

				IF @CURRENT_STATUS IN (-2,-1) AND @STATUS = 0
					EXEC USP_CREATE_TRANSACTION_LOG @MENU_CODE = @MENU_CODE, @BR_CODE = @BR_CODE, @TRAN_OPTION = 'N', @SOURCE_TABLE_NAME = 'TELLER_TRAN_DETL', @SOURCE_TABLE_TRAN_ID = @TRAN_ID, @TRAN_USER_ID = @ENTRY_USER_ID, @TRAN_DATE = @TRAN_DATE,@TXN_LIST=@TXN_LIST
			END

			INSERT INTO TELLER_TRAN_DETL_CHARGE (TELLER_TRAN_DETL_ID,CHARGE_CODE,FLAT_PCT,CHARGE_VALUE,CHARGE_AMT)
			SELECT @TRAN_ID,CL.Charge_Code,D1.FLAT_PCT,D1.CHARGE_VALUE,CL.Charge_Amt
			FROM @CHARGE_LIST CL
				INNER JOIN AC_GROUP_CHARGE_HIST_DETL D ON D.CHARGE_CODE=CL.Charge_Code
				INNER JOIN AC_GROUP_CHARGE_HIST_DETL_1 D1 ON D1.AC_GROUP_CHARGE_HIST_DETL_ID=D.TRAN_ID
				INNER JOIN (SELECT AGCHM.TRAN_ID,AGCHM.AC_GROUP_CODE,ROW_NUMBER() OVER(PARTITION BY AGCHM.AC_GROUP_CODE ORDER BY AGCHM.EFFECT_DATE DESC)RN FROM AC_GROUP_CHARGE_HIST_MAST AGCHM WHERE AGCHM.EFFECT_DATE<=@TRAN_DATE AND AGCHM.STATUS=1)AGCHM ON AGCHM.TRAN_ID=D.AC_GROUP_CHARGE_HIST_MAST_ID AND AGCHM.AC_GROUP_CODE=@AC_GROUP_CODE AND AGCHM.RN=1
			WHERE CL.Charge_Amt>0

			INSERT INTO TELLER_TRAN_DETL_DENO (TELLER_TRAN_DETL_ID,DENO_VALUE,DENO_COUNT)
			SELECT @TRAN_ID,T.DENO,T.DENO_CNT
			FROM @DENO T

			--INSERT INTO TELLER_TRAN_DETL_DOC (TELLER_TRAN_ID,DOC_TYPE_ID,DOC_TITLE,DOC_NO,DOC_GUID,FILE_EXTENSION,MIME_TYPE)
			--SELECT @TRAN_ID,DOC_TYPE_ID, DOC_TITLE, DOC_NO, DOC_GUID, FILE_EXTENSION, MIME_TYPE
			--FROM @DOC
			
			DECLARE @IS_AML_MODULE_USED BIT = ISNULL((SELECT IS_AML_MODULE_USED FROM GLOBAL_SETUP),1)

			IF @IS_AML_MODULE_USED = 1 AND (@TRAN_AMT >= @SOURCE_OF_FUND_MANDATORY_AMOUNT AND @SOURCE_OF_FUND_MANDATORY_AMOUNT > 0) AND
				(RTRIM(LTRIM(ISNULL(@CONDUCTOR_FIRST_NAME ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_LAST_NAME ,'')))='' OR
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_GENDER_CODE ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_CONTACT_NO ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_GRAND_FATHER_NAME ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_FATHER_NAME ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_LOCAL_BODY_CODE ,'')))='' OR
					ISNULL(@CONDUCTOR_LOCAL_BODY_TYPE_ID ,'')='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_OCCUPATION_CODE ,'')))='' OR 
					RTRIM(LTRIM(ISNULL(@CONDUCTOR_TOLE_NAME ,'')))='' OR 
					ISNULL(@CONDUCTOR_BIRTH_DATE ,'')=''  OR 
					ISNULL(@CONDUCTOR_DISTRICT_CODE ,'')=''
					)
			BEGIN
				--;THROW 50000, 'Warning - ! All AML Information is Mandatory...!!!', 1;
				EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_AML_INFO_MANDATORY'
			END

			IF RTRIM(LTRIM(ISNULL(@DRAWEE_FIRST_NAME,''))) <>'' OR RTRIM(LTRIM(ISNULL(@CONDUCTOR_FIRST_NAME ,''))) <>'' 
			--IF (LTRIM(ISNULL(@DRAWEE_FIRST_NAME,'') IS NOT NULL OR @CONDUCTOR_FIRST_NAME IS NOT NULL)
			BEGIN
				--IF RTRIM(LTRIM(ISNULL(@CONDUCTOR_FIRST_NAME ,''))) <> ''  AND ISNULL(@CONDUCTOR_IDENTITY_TYPE_ID ,0)<=0 AND RTRIM(LTRIM(ISNULL(@CONDUCTOR_IDENTITY_NO ,''))) =''
				 IF RTRIM(LTRIM(ISNULL(@CONDUCTOR_CUSTOMER_CODE ,''))) <> ''  AND ISNULL(@CONDUCTOR_IDENTITY_TYPE_ID ,0)<=0 AND RTRIM(LTRIM(ISNULL(@CONDUCTOR_IDENTITY_NO ,''))) ='' AND @TRAN_AMT>100000

				BEGIN
					--;THROW 50000, 'Warning - ! Invalid Conductor Identity Details...!!!', 1;
					EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_CONDUCTOR_IDENTITY'
				END

				IF RTRIM(LTRIM(ISNULL(@DRAWEE_FIRST_NAME,''))) <>'' AND RTRIM(LTRIM(ISNULL(@CONDUCTOR_FIRST_NAME ,''))) = '' 
				BEGIN
					--;THROW 50000, 'Warning - ! Invalid Conductor Details...!!!', 1;
					EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_CONDUCTOR'
				END
				  
				IF (ISNULL(@DRAWEE_CUSTOMER_CODE,'') <> '')
				BEGIN 
					SET @DRAWEE_FIRST_NAME= NULL
					SET @DRAWEE_MIDDLE_NAME=NULL
					SET @DRAWEE_LAST_NAME=NULL
				END

				IF (ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') <> '')
				BEGIN
					SET @CONDUCTOR_FIRST_NAME= NULL
					SET @CONDUCTOR_MIDDLE_NAME= NULL
					SET @CONDUCTOR_LAST_NAME= NULL
					SET @CONDUCTOR_CONTACT_NO= NULL
				END
				
				DECLARE @AML_TRAN_CODE VARCHAR(50),@CUSTOMER_LEGAL_SCOPE INT;
					--GENERATE AML TRAN CODE
					--SET @AML_TRAN_CODE = (SELECT TOP 1 @OPR_CODE + '0' + (CASE WHEN ISNULL(@CUSTOMER_CODE,'')=ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') THEN '1'
					--															WHEN ISNULL(@CUSTOMER_CODE,'')<>ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') THEN '2'
					--															WHEN ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') = '' THEN '3'))
				
				SET @CUSTOMER_LEGAL_SCOPE= (SELECT CUSTOMER_LEGAL_SCOPE FROM CUSTOMER_MAST WHERE CUSTOMER_CODE=@CUSTOMER_CODE)
				SET @AML_TRAN_CODE =(SELECT TOP 1 TRAN_CODE FROM AML_TRAN_PROCESS 
										WHERE ENTITY_RELATION =(CASE WHEN ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') = '' or ISNULL(@DRAWEE_CUSTOMER_CODE,'') = ''  THEN 3																	
																	 WHEN ISNULL(@CUSTOMER_CODE,'')=ISNULL(@CONDUCTOR_CUSTOMER_CODE,'') THEN 1
																	 WHEN ISNULL(@CONDUCTOR_CUSTOMER_CODE,'')<>'' AND ISNULL(@CONDUCTOR_CUSTOMER_CODE,'')<>ISNULL(@CUSTOMER_CODE,'') THEN 2
																END) 
											AND OPERATION_CODE = @OPR_CODE AND CUSTOMER_LEGAL_SCOPE=@CUSTOMER_LEGAL_SCOPE)

				IF ISNULL(@AML_TRAN_CODE,'') =''
				BEGIN
					--;THROW 50000, 'Warning - ! Invalid AML Process Code...!!!', 1;
					EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_AML_CODE'
				END
			
				INSERT INTO TELLER_TRAN_AML_INFO(TELLER_TRAN_DETL_ID,DRAWEE_FIRST_NAME,DRAWEE_MIDDLE_NAME,DRAWEE_LAST_NAME,DRAWEE_CUSTOMER_CODE,CONDUCTOR_FIRST_NAME,CONDUCTOR_MIDDLE_NAME,CONDUCTOR_LAST_NAME,CONDUCTOR_CONTACT_NO,CONDUCTOR_CUSTOMER_CODE,CONDUCTOR_IDENTITY_TYPE_ID,CONDUCTOR_IDENTITY_NO,CONDUCTOR_IDENTITY_ISSUE_DATE,CONDUCTOR_IDENTITY_EXPIRY_DATE,CONDUCTOR_IDENTITY_ISSUE_PLACE,AML_TRAN_CODE,CONDUCTOR_FATHER_NAME,CONDUCTOR_MOTHER_NAME,CONDUCTOR_GRAND_FATHER_NAME,CONDUCTOR_BIRTH_DATE,CONDUCTOR_GENDER_CODE,CONDUCTOR_DISTRICT_CODE,CONDUCTOR_LOCAL_BODY_TYPE_ID,CONDUCTOR_LOCAL_BODY_CODE,CONDUCTOR_TOLE_NAME,CONDUCTOR_OCCUPATION_CODE)
				VALUES (@TRAN_ID,@DRAWEE_FIRST_NAME,@DRAWEE_MIDDLE_NAME,@DRAWEE_LAST_NAME,@DRAWEE_CUSTOMER_CODE,@CONDUCTOR_FIRST_NAME,@CONDUCTOR_MIDDLE_NAME,@CONDUCTOR_LAST_NAME,@CONDUCTOR_CONTACT_NO,@CONDUCTOR_CUSTOMER_CODE,NULLIF(@CONDUCTOR_IDENTITY_TYPE_ID,0),@CONDUCTOR_IDENTITY_NO,@CONDUCTOR_IDENTITY_ISSUE_DATE,@CONDUCTOR_IDENTITY_EXPIRY_DATE,@CONDUCTOR_IDENTITY_ISSUE_PLACE,@AML_TRAN_CODE,@CONDUCTOR_FATHER_NAME,@CONDUCTOR_MOTHER_NAME,@CONDUCTOR_GRAND_FATHER_NAME,@CONDUCTOR_BIRTH_DATE,@CONDUCTOR_GENDER_CODE,@CONDUCTOR_DISTRICT_CODE,@CONDUCTOR_LOCAL_BODY_TYPE_ID,@CONDUCTOR_LOCAL_BODY_CODE,@CONDUCTOR_TOLE_NAME,@CONDUCTOR_OCCUPATION_CODE)
			END
		SET @UPDATED_TRAN_ID = @TRAN_ID;

		IF @IS_APPROVAL = 1
		BEGIN -- CHECK LEVELS
			--approval
			EXEC USP_CHECK_GLOBAL_APPROVAL_RIGHTS @BR_CODE, @TRAN_DATE, @MENU_CODE, @TRAN_ID, @ENTRY_USER_ID, 1, @MAX_APPROVAL_COUNT OUTPUT, @TXN_LIST -- CHECK 
			
			DECLARE  @IS_FINAL_APPROVAL INT=0
			EXEC USP_TRANSACTION_LOG_APPROVAL_ACTION @MENU_CODE = @MENU_CODE,
														@BR_CODE = @BR_CODE,
														@SOURCE_TABLE_TRAN_ID = @TRAN_ID,
														@TRAN_USER_ID = @ENTRY_USER_ID,
														@TRAN_DATE = @TRAN_DATE,
														@ACTION_OPTION = 3, --1. Review, 2.Reject, 3.Approved@DESCRIPTION
														@MAX_APPROVAL_LEVEL = @MAX_APPROVAL_COUNT,
														@REMAINING_APPROVAL_COUNT = @REMAINING_APPROVAL_COUNT OUTPUT,
														@IS_FINAL_APPROVAL = @IS_FINAL_APPROVAL OUTPUT
			IF  @IS_FINAL_APPROVAL = 1
			BEGIN
				DECLARE @NEW_VCH_NO_2 VARCHAR(50)='';
				
				EXEC USP_TELLER_TRAN_SAVE_VOUCHER @TRAN_ID, @STATUS, @PREVIEW_ONLY, @BR_CODE, @AC_NO, @OPR_CODE, @TRAN_DATE, @ENTRY_USER_ID, @TRAN_AMT, @JOURNAL_AC_NO, @INST_NO, @INST_CODE, @INST_DATE, @DENO, @CHARGE_LIST, @DESCRIPTION, @SOURCE_OF_FUND_ID, @WDR_DEPOSITOR_NAME, @IS_ABBS, @REF_BR_CODE,@BANK_BR_CODE,@SOURCE_BANK_BRCODE,@SOURCE_AC_NO,@SOURCE_CHQ_NO,@SOURCE_CHQ_DATE, @ENTRY_USER_ID, @BR_CODE, @NEW_VCH_NO OUTPUT, @VCH , @NEW_VCH_NO_2 OUTPUT
				
				UPDATE MAST
				SET [STATUS] = 1,
					STATUS_CHANGE_DATE = @TRAN_DATE,
					STATUS_CHANGE_USER_ID = @ENTRY_USER_ID,
					VCH_NO = @NEW_VCH_NO
				FROM TELLER_TRAN_DETL MAST
				WHERE MAST.TRAN_ID = @TRAN_ID
					AND ISNULL([VCH_NO],'') =''
				
				--IF ISNULL(@NEW_VCH_NO_2,'')<>''
				--BEGIN
				--	INSERT INTO TELLER_TRAN_DETL_MULTIPLE_VOUCHER (TELLER_TRAN_DETL_ID,VCH_NO)
				--	VALUES (@TRAN_ID,@NEW_VCH_NO), (@TRAN_ID,@NEW_VCH_NO_2)
				--END

				IF EXISTS(SELECT TOP  1 1 FROM TELLER_TRAN_DETL  TTD 
							INNER JOIN TELLER_TRAN_AML_INFO TTAI ON TTAI.TELLER_TRAN_DETL_ID = TTD.TRAN_ID
							WHERE TTD.TRAN_ID=@TRAN_ID)
				BEGIN
					INSERT INTO GLTRAN_AML_INFO(VCH_NO,AML_TRAN_CODE, DRAWEE_FIRST_NAME,DRAWEE_MIDDLE_NAME,DRAWEE_LAST_NAME,DRAWEE_CUSTOMER_CODE,CONDUCTOR_FIRST_NAME,CONDUCTOR_MIDDLE_NAME,CONDUCTOR_LAST_NAME,CONDUCTOR_CONTACT_NO,CONDUCTOR_CUSTOMER_CODE,CONDUCTOR_IDENTITY_TYPE_ID,CONDUCTOR_IDENTITY_NO,CONDUCTOR_IDENTITY_ISSUE_DATE,
						CONDUCTOR_IDENTITY_EXPIRY_DATE,CONDUCTOR_IDENTITY_ISSUE_PLACE,CONDUCTOR_FATHER_NAME,CONDUCTOR_MOTHER_NAME,CONDUCTOR_GRAND_FATHER_NAME,CONDUCTOR_BIRTH_DATE,CONDUCTOR_GENDER_CODE,CONDUCTOR_DISTRICT_CODE,CONDUCTOR_LOCAL_BODY_TYPE_ID,CONDUCTOR_LOCAL_BODY_CODE,CONDUCTOR_TOLE_NAME,CONDUCTOR_OCCUPATION_CODE)
					SELECT TOP 1 @NEW_VCH_NO,AML_TRAN_CODE, DRAWEE_FIRST_NAME, DRAWEE_MIDDLE_NAME,DRAWEE_LAST_NAME, DRAWEE_CUSTOMER_CODE,CONDUCTOR_FIRST_NAME, CONDUCTOR_MIDDLE_NAME,CONDUCTOR_LAST_NAME,CONDUCTOR_CONTACT_NO,CONDUCTOR_CUSTOMER_CODE,CONDUCTOR_IDENTITY_TYPE_ID, CONDUCTOR_IDENTITY_NO, CONDUCTOR_IDENTITY_ISSUE_DATE, 
						CONDUCTOR_IDENTITY_EXPIRY_DATE, CONDUCTOR_IDENTITY_ISSUE_PLACE,@CONDUCTOR_FATHER_NAME,@CONDUCTOR_MOTHER_NAME,@CONDUCTOR_GRAND_FATHER_NAME,@CONDUCTOR_BIRTH_DATE,@CONDUCTOR_GENDER_CODE,@CONDUCTOR_DISTRICT_CODE,@CONDUCTOR_LOCAL_BODY_TYPE_ID,@CONDUCTOR_LOCAL_BODY_CODE,@CONDUCTOR_TOLE_NAME,@CONDUCTOR_OCCUPATION_CODE
					FROM TELLER_TRAN_AML_INFO WHERE TELLER_TRAN_DETL_ID=@TRAN_ID
				END

				SET @MSG = CONCAT('Transaction Saved Successfully With Voucher No ', @NEW_VCH_NO, ' . Current Balance : ', @NEW_BAL);	
			END
			SET @IS_APPROVAL = 1;
			--SET @UPDATED_TRAN_ID = @TRAN_ID;

		END
		ELSE
		BEGIN
			SET @IS_APPROVAL = 0;
			SET @MSG='The transaction has been saved and sent to approval dashboard ! ';
		END

		-- TELLER TRAN UPDATE --XX: MANAGE IN CASE OF UPDATE
		SET @IN_OUT= CASE WHEN @DR_CR='DR' THEN 'OUT' ELSE 'IN' END
		DECLARE @TOT_CHARGE_AMT DECIMAL(18,2)=ISNULL((SELECT SUM(CL.CHARGE_AMT) FROM @CHARGE_LIST CL),0)
		SET @CASH_AMT=@TRAN_AMT;
		BEGIN
			IF EXISTS(SELECT OP_CODE FROM OPERATION_LIST WHERE @OPR_CODE IN ('06','07'))
			BEGIN
				IF @IN_OUT='OUT' -- SAVE ONLY CASE -- UPDATE
				BEGIN
					EXEC USP_UPDATE_TELLER_TRANS @BR_CODE=@BR_CODE,@TRAN_DATE=@TRAN_DATE,@USER_ID=@ENTRY_USER_ID,@USER_AS='T',@IN_OUT=@IN_OUT,@CUR_CODE='01',@AMOUNT=@CASH_AMT,@IN_OUT_USER_ID='',@IN_OUT_USER_AS='',@REVERTED='NO',@ACCEPTED='YES',@COUNTER='YES'
				END
			END
				--select @IS_FINAL_APPROVAL app,@TOT_CHARGE_AMT amt ,@status stt
				--IF 1=0 AND @TOT_CHARGE_AMT>0 AND @OPR_CODE<>'12' -- APPROVE CASE
				IF EXISTS(SELECT OP_CODE FROM OPERATION_LIST WHERE @OPR_CODE ='01' and @IS_FINAL_APPROVAL=1 AND @TOT_CHARGE_AMT>0)  -- APPROVE CASE
				BEGIN
					EXEC USP_UPDATE_TELLER_TRANS @BR_CODE=@BR_CODE,@TRAN_DATE=@TRAN_DATE,@USER_ID=@ENTRY_USER_ID,@USER_AS='T',@IN_OUT='IN',@CUR_CODE='01',@AMOUNT=@TOT_CHARGE_AMT,@IN_OUT_USER_ID='',@IN_OUT_USER_AS='',@REVERTED='NO',@ACCEPTED='YES',@COUNTER='YES'
				END
		END
		--SET @UPDATED_TRAN_ID = @TRAN_ID;
		SET @NEW_BAL = ISNULL(@NEW_BAL, 0);
		COMMIT  TRANSACTION 
	END
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			DECLARE @AAA INT =ERROR_LINE() 
			ROLLBACK TRANSACTION;
		END
		;THROW;
	END CATCH
END
GO
