CREATE   PROC USP_CBS_Check_UserCredentials 
(  
    @USERNAME varchar(50)='',  
    @PASSWORD varchar(50)='',  
    @BRANCH_CODE varchar(50)=''
)  
AS
BEGIN  
    SET NOCOUNT ON;
    SET ARITHABORT ON;
     
    DECLARE @USER_ID VARCHAR(50);  
    DECLARE @DAYENDATE DATE;  
    DECLARE @IS_ADMIN VARCHAR(50);
	DECLARE @GLOBAL_LOGIN_GRACE INT = (SELECT TOP 1 ISNULL(LOGIN_GRACE_CNT,0) FROM GLOBAL_SETUP)
	SELECT TOP 1 *
	INTO #USERS
	FROM USERS
	WHERE LOGIN_NAME = @USERNAME

	 IF NOT EXISTS( SELECT TOP 1 'X' FROM #USERS WHERE (LOGIN_NAME = @USERNAME AND PWD = @PASSWORD) )  
	  BEGIN  
		--RAISERROR('WARNING - ! Invalid login attempt...!!!', 18, 1);
        --RETURN; 
        EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_LOGIN'

      END  
     ELSE  
      BEGIN  
		SELECT TOP 1 @USER_ID = [USER_ID], @IS_ADMIN = [ADMIN] FROM USERS WHERE LOGIN_NAME = @USERNAME;  
           SELECT TOP 1 @DAYENDATE = [DATE]  FROM BRANCH INNER JOIN DAYEND ON BRANCH.BR_CODE = DAYEND.BR_CODE  
            WHERE BRANCH.BR_CODE = @BRANCH_CODE AND BRANCH.APPROVED='YES'  
            ORDER BY DAYEND.TRAN_ID DESC;  
            IF (@IS_ADMIN <> 'YES')
            BEGIN
                DECLARE @TBL_USER_RIGHT AS TABLE (USER_GROUP_CODE VARCHAR(10), EFFECT_DATE DATE, TILL_DAYS INT, [USER_ID] VARCHAR(10) );
				; WITH ALIAS AS (
					SELECT DISTINCT ALIAS_USER_ID
					FROM USER_ALIAS
					WHERE OBTAIN_USER_ID = @USER_ID
						AND [STATUS] = 1
						AND @DAYENDATE < DATEADD(DAY, TILL_DAYS, EFFECT_DATE)
				)
                INSERT INTO @TBL_USER_RIGHT
                SELECT USER_GROUP_CODE, EFFECT_DATE, TILL_DAYS, [USER_ID]
                FROM (
                    SELECT USER_GROUP_CODE, EFFECT_DATE, ISNULL(DATEDIFF(DAY, @DAYENDATE, R.EFFECT_TILL_DATE), 0) TILL_DAYS, [USER_ID]
                    FROM USER_RIGHTS_ASSIGN_MAST MAST
                        INNER JOIN USER_RIGHTS_ASSIGN_BRANCH BR ON MAST.TRAN_ID = BR.USER_RIGHTS_ASSIGN_MAST_ID
                        INNER JOIN USER_RIGHTS_ASSIGN_ROLE R ON MAST.TRAN_ID = R.USER_RIGHTS_ASSIGN_MAST_ID
                    WHERE MAST.[USER_ID] = @USER_ID AND BR.BR_CODE = @BRANCH_CODE AND MAST.[STATUS] = 1
                ) A 
				UNION
				SELECT USER_GROUP_CODE, EFFECT_DATE, 0,  @USER_ID
				FROM (
					SELECT MAST.TRAN_ID, MAST.[USER_ID], UG.USER_GROUP_CODE, EFFECT_TILL_DATE, EFFECT_DATE, BR_CODE
					FROM USER_RIGHTS_ASSIGN_MAST MAST
						INNER JOIN ALIAS ON ALIAS.ALIAS_USER_ID = MAST.[USER_ID]
						INNER JOIN USER_RIGHTS_ASSIGN_BRANCH BR ON MAST.TRAN_ID = BR.USER_RIGHTS_ASSIGN_MAST_ID
						INNER JOIN USER_RIGHTS_ASSIGN_ROLE UG ON MAST.TRAN_ID = UG.USER_RIGHTS_ASSIGN_MAST_ID
					WHERE MAST.[STATUS] = 1 AND BR.BR_CODE = @BRANCH_CODE
				) UG
				CROSS APPLY (SELECT TOP 1 [DATE] FROM DAYEND WHERE BR_CODE = UG.BR_CODE ORDER BY [DATE] DESC, TRAN_ID DESC) DAYEND
                --- VALIDATION 0 : CHECK IF ASSIGNED TO BRANCH
                IF NOT EXISTS ( SELECT 'X' FROM @TBL_USER_RIGHT )
                BEGIN
                    --RAISERROR('WARNING - ! User rights not assigned to this branch...!!!', 18, 1);
                    --RETURN;
                    EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_USER_RIGHTS_NOT_ASSIGNED'
                END;
                --- VALIDATION 0 : CHECK USER RIGHTS DURATION
                IF  NOT EXISTS (
                    SELECT 'X' FROM @TBL_USER_RIGHT WHERE TILL_DAYS = 0 OR (DATEADD(DD, TILL_DAYS, @DAYENDATE) > @DAYENDATE)
                )
                BEGIN
                    --RAISERROR('WARNING - ! User rights have expired...!!!', 18, 1);
                    --RETURN;
                    EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_USER_RIGHTS_EXPIRED'
                END;
            END
        
      END  

      SELECT @USERNAME LOGIN_NAME, @PASSWORD PWD
END
--GO
--EXEC USP_CBS_Check_UserCredentials 'admin','Â;Â;ôSôÿ$a','900'