CREATE  PROCEDURE [dbo].[USP_CBS_TellerTransaction_Get_CustomerAML]
(
	@INPUT VARCHAR(200),
	@SEARCH_BY VARCHAR(50)='',
	@ROW_COUNT INT,
	@SKIP_COUNT INT,
	@TOTAL_COUNT INT = 0 OUTPUT
)
AS
BEGIN
	SET NOCOUNT ON;
	SET ANSI_WARNINGS OFF;
	SET ARITHABORT ON;
	SET XACT_ABORT ON;

	DROP TABLE IF EXISTS #CUST_AML

	IF ISNULL(@SEARCH_BY,'')=''
		SET @SEARCH_BY='MEMBER_NAME'

	SET @INPUT = CASE WHEN @SEARCH_BY IN ('MEMBER_CODE','MOBILE_NO') THEN @INPUT 
							 WHEN @SEARCH_BY ='MEMBER_NAME' THEN @INPUT+'%' ELSE NULL END

	SELECT DISTINCT CM.CUSTOMER_CODE,ISNULL(CM.MOBILE_NO,'') MOBILE_NO, CM.FULL_NAME AS CUSTOMER_NAME, CM.FIRST_NAME,ISNULL(CM.MIDDLE_NAME,'') MIDDLE_NAME,CM.LAST_NAME,
		ISNULL(CONVERT(VARCHAR(10),CM.BIRTH_DATE,121),'') AS BIRTH_DATE,
		ISNULL(DT.NEP_DATE,'') AS BIRTH_DATE_NEP,
		ISNULL(GF.FULL_NAME,'') AS GRAND_FATHER_NAME,ISNULL(F.FULL_NAME,'') AS FATHER_NAME
		,ISNULL(M.FULL_NAME,'') AS MOTHER_NAME,ISNULL(A.TOLE_NAME,'') AS TOLE_NAME,ISNULL(DISTRICT_CODE,'') AS DISTRICT_CODE,ISNULL(DISTRICT_NAME,'') AS DISTRICT_NAME,ISNULL(LOCAL_BODY_CODE,'') AS LOCAL_BODY_CODE,
		ISNULL(LOCAL_BODY_NAME,'') AS LOCAL_BODY_NAME,ISNULL(LOCAL_BODY_TYPE_ID,0) AS LOCAL_BODY_TYPE_ID,ISNULL(LOCAL_BODY_TYPE_NAME,'') AS LOCAL_BODY_TYPE_NAME, ISNULL(CM.GENDER_CODE,'') GENDER_CODE,ISNULL(cm.OCCUPATION_CODE,'') AS OCCUPATION_CODE  
	INTO #CUST_AML
	FROM CUSTOMER_MAST CM
	INNER JOIN DATE_TABLE DT ON DT.ENG_DATE = CM.BIRTH_DATE 
	INNER JOIN (SELECT BR_CODE, CUSTOMER_CODE, STATUS_CODE
					,ROW_NUMBER() OVER(PARTITION BY BR_CODE, CUSTOMER_CODE ORDER BY STATUS_CHG_DATE DESC , TRAN_ID DESC) RN 
				FROM CUST_STATUS_HIST 
				) CSH ON CSH.STATUS_CODE='02' AND CSH.RN=1 AND CSH.CUSTOMER_CODE = CM.CUSTOMER_CODE
	LEFT OUTER JOIN CUSTOMER_FAMILY_TREE GF ON GF.RELATION_CODE = '10' AND GF.CUSTOMER_CODE = CM.CUSTOMER_CODE AND GF.[STATUS] = 1
	LEFT OUTER JOIN CUSTOMER_FAMILY_TREE F ON F.RELATION_CODE = '06' AND F.CUSTOMER_CODE = CM.CUSTOMER_CODE AND GF.[STATUS] = 1
	LEFT OUTER JOIN CUSTOMER_FAMILY_TREE M ON M.RELATION_CODE = '05' AND M.CUSTOMER_CODE = CM.CUSTOMER_CODE AND GF.[STATUS] = 1
	LEFT OUTER JOIN ( SELECT CUSTOMER_CODE,TOLE_NAME,DISTRICT_CODE,DISTRICT_NAME,LOCAL_BODY_CODE,LOCAL_BODY_NAME,LOCAL_BODY_TYPE_ID,
						LOCAL_BODY_TYPE_NAME,ROW_NUMBER() OVER (PARTITION BY CUSTOMER_CODE ORDER BY ADDRESS_TYPE ASC) RN
					FROM CUSTOMER_ADDRESS_VIEW 
					) A ON A.CUSTOMER_CODE = CM.CUSTOMER_CODE AND A.RN = 1
	INNER JOIN GLOBAL_SETUP GS ON 1=1
	WHERE (CM.FULL_NAME LIKE @INPUT OR CM.CUSTOMER_CODE = @INPUT OR CM.MOBILE_NO=@INPUT)

	SELECT * FROM #CUST_AML
	ORDER BY CUSTOMER_CODE
	OFFSET @SKIP_COUNT ROWS
	FETCH NEXT @ROW_COUNT ROWS ONLY

	SET @TOTAL_COUNT =  (SELECT COUNT(1) FROM #CUST_AML)
	DROP TABLE IF EXISTS #CUST_AML

END
--GO
--EXEC USP_CBS_TellerTransaction_Get_CustomerAML '9849145549','MOBILE_NO',@ROW_COUNT =100,@SKIP_COUNT =0
