CREATE  PROC  [DBO].[USP_CBS_TellerTransaction_Get_AccountInformation] 
(
	@AC_NO VARCHAR(50),
	@SESSION_BR_CODE VARCHAR(50)
)
AS
BEGIN
	SET NOCOUNT ON ;
	SET ARITHABORT ON;

	DECLARE @BR_CODE VARCHAR(50)=(SELECT TOP 1 BR_CODE FROM DEPOSIT_AC_MAST WHERE AC_NO=@AC_NO 
										UNION ALL 
										SELECT TOP 1 BR_CODE FROM LOAN_MAST WHERE AC_NO=@AC_NO)

	  IF NOT EXISTS( SELECT TOP 1 'X' FROM DEPOSIT_AC_MAST WHERE AC_NO=@AC_NO AND BR_CODE=@BR_CODE
					UNION ALL 
					SELECT TOP 1 'X' FROM LOAN_MAST WHERE AC_NO=@AC_NO AND BR_CODE=@BR_CODE)  
	  BEGIN  
		--RAISERROR('WARNING - ! Invalid account number...!!!', 18, 1);
		--RETURN; 
		EXEC USP_CBS_Global_Get_ErrorMessage @MSG_CODE = 'ERR_INVALID_AC_NO'
      END 

	DECLARE @AC_GROUP_CODE VARCHAR(50),@AC_STATUS VARCHAR(50);

	SELECT TOP 1 
    @AC_GROUP_CODE = AC_GROUP_CODE,
    @AC_STATUS = AC.STAT_NAME
	FROM (
		SELECT AC_GROUP_CODE, AC_STATUS 
		FROM DEPOSIT_AC_MAST WHERE AC_NO = @AC_NO
		UNION ALL
		SELECT AC_GROUP_CODE, LOAN_STATUS 
		FROM LOAN_MAST WHERE AC_NO = @AC_NO
	) T
	INNER JOIN AC_STATUS AC ON AC.STAT_CODE=T.AC_STATUS

	DECLARE @AC_TYPE_SUB_TYPE_CODE VARCHAR(50)=(SELECT AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE AC_GROUP_CODE=@AC_GROUP_CODE)


	DECLARE @TRAN_DATE DATE=(SELECT TOP 1 DATE FROM DAYEND WHERE BR_CODE=@SESSION_BR_CODE ORDER BY DATE DESC)
	DROP TABLE IF EXISTS #BAL;

	CREATE TABLE #BAL(CUR_BAL DECIMAL(18,2), WDR_ELG_BAL DECIMAL(18,2), MIN_BAL DECIMAL(18,2), HOLD_AMT DECIMAL(18,2), AVAILABLE_BAL DECIMAL(18,2), INT_AMT DECIMAL(18,2))

	IF EXISTS(SELECT AC_GROUP_CODE FROM AC_GROUP WHERE APPROVED='YES' AND AC_TYPE_CODE='03' AND AC_GROUP_CODE=@AC_GROUP_CODE)
	BEGIN
			INSERT INTO #BAL
			SELECT CUR_BAL,MIN_BALANCE,C.HOLD_AMT
			,CASE WHEN T.DR_TRAN_BLOCKED <> 'YES' THEN 
				ISNULL(
					(CASE WHEN ((CUR_BAL-(CASE WHEN C.HOLD_AMT>MIN_BALANCE THEN C.HOLD_AMT ELSE MIN_BALANCE END)) <0 )
					THEN 0 
					ELSE
					(CUR_BAL-(CASE WHEN C.HOLD_AMT>MIN_BALANCE THEN C.HOLD_AMT ELSE MIN_BALANCE END))
					END)
				,0) ELSE 0 
			END WDR_ELG_BAL
			,(CASE WHEN T.ALLOWED_WDR_BELOW_MIN_BAL = 'YES' AND (CUR_BAL-MIN_BALANCE)<0 THEN 0 ELSE (CUR_BAL-MIN_BALANCE) END) AVAILABLE_BAL
			,(CASE WHEN T.AC_TYPE_SUB_TYPE_CODE='0303' THEN T.INST_AMT ELSE 0.00 END ) INSTALLMENT_AMT  
			FROM ( 
					SELECT SUM(GD.AMT) AS CUR_BAL,DAM.MIN_BALANCE,DAM.AC_NO,AG.AC_TYPE_SUB_TYPE_CODE,DAM.INST_AMT ,AGP.ALLOWED_WDR_BELOW_MIN_BAL, AGP.DR_TRAN_BLOCKED
					FROM GLTRAN_MAST GM 
							INNER JOIN GLTRAN_DETL AS GD  ON GM.VCH_NO=GD.VCH_NO AND GD.BR_CODE=@BR_CODE
							INNER JOIN DEPOSIT_AC_MAST DAM  ON GD.SOURCE_TYPE_ID = 3 AND GD.SOURCE_TRAN_ID = DAM.ID AND DAM.BR_CODE = @BR_CODE AND DAM.AC_NO = @AC_NO--GD.AC_NO = DAM.AC_NO AND AGGM.AC_GROUP_CODE = DAM.AC_GROUP_CODE
							INNER JOIN AC_GROUP_GL_MAP AGGM  ON GD.GL_CODE = AGGM.GL_CODE AND AGGM.NAMED_AC_CODE = '0301' AND DAM.AC_GROUP_CODE = AGGM.AC_GROUP_CODE
							INNER JOIN AC_GROUP AG  ON AGGM.AC_GROUP_CODE = AG.AC_GROUP_CODE AND AG.AC_TYPE_CODE = '03'
							INNER JOIN AC_GROUP_PARA AGP  ON AG.AC_GROUP_CODE = AGP.AC_GROUP_CODE 
					WHERE GM.TRAN_DATE<=@TRAN_DATE  --AND DAM.AC_GROUP_CODE = @AC_GROUP_CODE --AND GD.AC_NO=@AC_NO
					GROUP BY DAM.AC_NO,DAM.MIN_BALANCE,AC_TYPE_SUB_TYPE_CODE,DAM.INST_AMT ,AGP.ALLOWED_WDR_BELOW_MIN_BAL, AGP.DR_TRAN_BLOCKED
				) T 
			CROSS APPLY (
							SELECT ISNULL(SUM(HOLD_AMT),0) HOLD_AMT 
							FROM BAL_HOLD_HIST B 
									LEFT OUTER JOIN (
														SELECT DETL.BAL_HOLD_HIST_ID, MAST.TRAN_DATE
														FROM [BAL_HOLD_RELEASE_MAST] MAST 
																INNER JOIN [BAL_HOLD_RELEASE_DETL] DETL  ON DETL.BAL_HOLD_RELEASE_MAST_ID = MAST.TRAN_ID AND MAST.STATUS=1
														) X  ON X.BAL_HOLD_HIST_ID=B.TRAN_ID
							WHERE X.BAL_HOLD_HIST_ID IS NULL AND T.AC_NO =B.AC_NO AND B.STATUS=1
					) C 
	END
	ELSE
	BEGIN
			INSERT INTO #BAL
			SELECT CUR_BAL,
			ISNULL((CASE WHEN (LIMIT - CUR_BAL) <0 THEN 0 ELSE (LIMIT - CUR_BAL) END),0) WDR_ELG_BAL,
			MIN_BALANCE,HOLD_AMT,CUR_BAL AVAILABLE_BAL,0.00 INSTALLMENT_AMT 
			FROM (
					SELECT CASE WHEN SUM(AMT)>0 THEN SUM(AMT) ELSE SUM(AMT)*-1 END CUR_BAL,T.LIMIT,0.00 MIN_BALANCE,0.00 HOLD_AMT 
					FROM GLTRAN_DETL GD 
							INNER JOIN LOAN_MAST LM ON GD.SOURCE_TYPE_ID = 4 AND GD.SOURCE_TRAN_ID = LM.ID AND LM.BR_CODE = @BR_CODE AND LM.AC_NO = @AC_NO
							INNER JOIN AC_GROUP_GL_MAP AGGL ON GD.GL_CODE = AGGL.GL_CODE
							INNER JOIN (
											SELECT SUM(ASSIGNED_LIMIT) AS LIMIT 
											FROM AC_LIMIT  
											WHERE BR_CODE=@BR_CODE AND AC_NO =@AC_NO AND STATUS_CHANGE_DATE<=@TRAN_DATE AND STATUS=1 
										) T ON GD.AC_NO = @AC_NO AND GD.BR_CODE = @BR_CODE AND VALUE_DATE<=@TRAN_DATE AND AGGL.AC_GROUP_CODE=@AC_GROUP_CODE AND AGGL.NAMED_AC_CODE='0401'
					GROUP BY T.LIMIT
				) AM 
	END

	DECLARE @INT_TYPE_CODE VARCHAR(50)=''
	DECLARE @CR_INT_RATE DECIMAL(18,2),@FINAL_RATE DECIMAL(18,2)

	SELECT @INT_TYPE_CODE=INT_TYPE_CODE,@CR_INT_RATE= CR_INT_RATE   FROM DEPOSIT_AC_MAST DAM WHERE  DAM.AC_NO=@AC_NO AND DAM.BR_CODE=@BR_CODE
	
	IF(@INT_TYPE_CODE='03')
	BEGIN
		SET @FINAL_RATE=ISNULL((SELECT CONCAT(ISNULL(MIN( INT_RATE),0),' - ',ISNULL(MAX(TD.INT_RATE),0)) AS FINAL_INT_RATE 
		FROM DEPOSIT_AC_MAST DAM 
				INNER JOIN TIRED_INT_RATE_MAST TM  ON TM.AC_GROUP_CODE=DAM.AC_GROUP_CODE AND TM.INT_BASED_ON_CODE=DAM.INT_BASED_ON_CODE AND TM.RATE_CODE=DAM.RATE_CODE AND TM.EFFECT_DATE<=@TRAN_DATE
				INNER JOIN TIRED_INT_RATE_DETL TD  ON TM.TRAN_ID=TD.TRAN_ID
		WHERE DAM.AC_NO=@AC_NO AND DAM.BR_CODE=@BR_CODE AND TM.APPROVED='YES' AND TM.[ACTION]=1),0)
	END
	ELSE 
	BEGIN
		SET @FINAL_RATE = ISNULL(@CR_INT_RATE,0)
	END

	
	IF NOT EXISTS (SELECT TOP 1 'X' FROM #BAL)
	BEGIN
		SELECT  0.00 CUR_BAL , 0.00 WDR_ELG_BAL , 0.00 MIN_BAL , 0.00 HOLD_AMT ,0.00 AVAILABLE_BAL, 0.00 INT_AMT, @FINAL_RATE FINAL_RATE, @AC_STATUS AC_STATUS
	END
	ELSE
	BEGIN 
		SELECT *,@FINAL_RATE FINAL_RATE, @AC_STATUS AC_STATUS FROM #BAL
	END

	-----------------AC GROUP CHARGES-------------
	SELECT DISTINCT AGCHD.CHARGE_CODE,C.CHARGE_NAME,C.GL_CODE AS GL_CODE,	AGCHD1.FLAT_PCT,AGCHD1.CHARGE_VALUE,CAST(AGCHM.RN AS INT) RN 
	FROM AC_GROUP_CHARGE_HIST_DETL AGCHD 
			INNER JOIN (
						SELECT AGCHM.TRAN_ID,AGCHM.AC_GROUP_CODE,STATUS,EFFECT_DATE,ROW_NUMBER() OVER(PARTITION BY AGCHM.AC_GROUP_CODE ORDER BY AGCHM.EFFECT_DATE DESC)RN 
						FROM AC_GROUP_CHARGE_HIST_MAST AGCHM 
						WHERE AGCHM.EFFECT_DATE<=@TRAN_DATE AND AGCHM.STATUS=1
					)AGCHM ON AGCHM.TRAN_ID=AGCHD.AC_GROUP_CHARGE_HIST_MAST_ID AND AGCHM.AC_GROUP_CODE=@AC_GROUP_CODE AND AGCHM.RN=1
			INNER JOIN AC_GROUP_CHARGE_HIST_DETL_1 AGCHD1  ON AGCHD1.AC_GROUP_CHARGE_HIST_DETL_ID = AGCHD.TRAN_ID
			INNER JOIN CHARGE C  ON AGCHD.CHARGE_CODE = C.CHARGE_CODE
	WHERE AGCHM.AC_GROUP_CODE = @AC_GROUP_CODE AND AGCHM.STATUS=1 AND EFFECT_DATE<=@TRAN_DATE
	----------------------------------------------

	--------OPERATION TYPES-----------------------
	IF (@AC_TYPE_SUB_TYPE_CODE='0401' OR @SESSION_BR_CODE <> @BR_CODE)
	BEGIN
		 SELECT OP_CODE, OP_DESC FROM OPERATION_LIST WHERE OP_CODE IN ('01', '06', '07', '08', '10', '11', '12', '14', '15')
	END
	ELSE
	BEGIN
		 SELECT OP_CODE, OP_DESC FROM OPERATION_LIST WHERE OP_CODE IN ('01', '06', '07', '08', '09', '10', '11', '12', '13', '15')
	END
	----------------------------------------------

	--------SOURCE OF FUND------------------------
	SELECT TRAN_ID ,DBO.PROPERCASE(SOURCE_FUND_NAME) SOURCE_FUND_NAME FROM SOURCE_OF_FUND WHERE [STATUS]=1
	----------------------------------------------

	--------SIGNATURE--------------------------
	SELECT TOP 1 DS.DOC_FILE, ASIG.DOC_GUID, MIME_TYPE, FILE_EXTENSION  FROM AC_SIGNATURE ASIG
	INNER JOIN DOC_STORE DS ON DS.DOC_GUID=ASIG.DOC_GUID
	WHERE  AC_NO = @AC_NO AND [STATUS] = 1 ORDER BY TRAN_DATE DESC, TRAN_ID DESC
	-------------------------------------------

	DROP TABLE IF EXISTS #BAL;

END
--GO
--EXEC USP_CBS_TellerTransaction_Get_AccountInformation
--@AC_NO ='00115001777',
--@SESSION_BR_CODE ='001'
