CREATE  PROCEDURE USP_CBS_TellerTransaction_Get_BankList
(
    @BR_CODE VARCHAR(50),
    @BANK_CODE VARCHAR(50)='',
    @TYPE VARCHAR(50),
    @INPUT VARCHAR(50)=''
)
AS
BEGIN

    IF @TYPE='BANK'
    BEGIN
        SELECT DISTINCT B.BANK_ALIAS,BANK_NAME,B.BANK_CODE FROM BANK B
                                        INNER JOIN BANK_ACNO BA ON B.BANK_CODE = BA.BANK_CODE AND BA.AC_CLOSE <>'YES'
                                        WHERE B.APPROVED = 'YES' AND BA.BR_CODE = @BR_CODE AND (B.BANK_NAME LIKE @INPUT+'%' OR B.BANK_CODE=@INPUT OR B.BANK_ALIAS=@INPUT) ORDER BY B.BANK_CODE;

        SELECT INST_CODE, INST_NAME FROM INSTRUMENT
    END
    ELSE ---BANK_AC
    BEGIN
           SELECT NOSTRO_AC_NO FROM BANK_ACNO BA INNER JOIN BANK B ON B.BANK_CODE = BA.BANK_CODE
                                    WHERE (B.BANK_ALIAS=@BANK_CODE OR B.BANK_CODE=@BANK_CODE) AND BR_CODE=@BR_CODE AND BA.APPROVED='YES' AND AC_CLOSE<>'YES'
    END

END
--GO
--EXEC USP_TellerTransaction_Get_BankLisT '001','GIB','BANK'