CREATE  PROCEDURE USP_CBS_LoanDisbursement_Get_InsuranceParameters 
(
	@AC_GROUP_CODE VARCHAR(10),
	@BR_CODE VARCHAR(10)
)
AS
BEGIN

	DECLARE @EFFECT_DATE DATE=(SELECT TOP 1 DATE FROM DAYEND WHERE BR_CODE=@BR_CODE ORDER BY DATE DESC)
	--INSURANCE PARAMETERS
	SELECT CAST(CASE ISNULL(INSURED_LOAN, 'NO') WHEN 'YES' THEN 1 ELSE 0 END AS BIT) IS_INSURED_LOAN
	, PRIMARY_CUSTOMER_INSURANCE_IN_LOAN_APPLY_OPTION as PRIMARY_APPLY_OPTION, SECONDARY_CUSTOMER_INSURANCE_IN_LOAN_APPLY_OPTION as SECONDARY_APPLY_OPTION
	FROM AC_GROUP_PARA 
	WHERE AC_GROUP_CODE = @AC_GROUP_CODE;
	--LIST OF PRIMARY INSURANCE COMPANIES
	SELECT IC.INS_COMP_ID, IC.INS_COMP_NAME, IPR.INSURANCE_SCOPE
	FROM INSURANCE_COMPANY IC 
		INNER JOIN INSURANCE_PREMIUM_RATE_MAST IPR ON IC.INS_COMP_ID=IPR.INS_COMP_ID 
	WHERE IC.APPROVED = 'YES' AND IPR.AC_GROUP_CODE = @AC_GROUP_CODE
		AND ISNULL(IC.APPROVED, 'YES') = 'YES'
		AND IPR.[STATUS] = 1
		AND EFFECT_DATE <= @EFFECT_DATE AND INSURANCE_SCOPE=1
	GROUP BY IC.INS_COMP_ID,INS_COMP_NAME,INSURANCE_SCOPE;

	--LIST OF SECONDARY INSURANCE COMPANIES
	SELECT IC.INS_COMP_ID, IC.INS_COMP_NAME, IPR.INSURANCE_SCOPE
	FROM INSURANCE_COMPANY IC 
		INNER JOIN INSURANCE_PREMIUM_RATE_MAST IPR ON IC.INS_COMP_ID=IPR.INS_COMP_ID 
	WHERE IC.APPROVED = 'YES' AND IPR.AC_GROUP_CODE = @AC_GROUP_CODE
		AND ISNULL(IC.APPROVED, 'YES') = 'YES'
		AND IPR.[STATUS] = 1
		AND EFFECT_DATE <= @EFFECT_DATE AND INSURANCE_SCOPE=2
	GROUP BY IC.INS_COMP_ID,INS_COMP_NAME,INSURANCE_SCOPE;

	--SECONDARY INSURANCE PREMIUM RATES
	DECLARE @SEC_MAST TABLE (TRAN_ID INT, INS_COMP_ID VARCHAR(50))	
	INSERT INTO @SEC_MAST (TRAN_ID, INS_COMP_ID)
	SELECT TRAN_ID, INS_COMP_ID
	FROM SECONDARY_INSURANCE_PREMIUM_RATE_MAST MAST
	WHERE MAST.EFFECT_DATE <= @EFFECT_DATE
		AND MAST.AC_GROUP_CODE = @AC_GROUP_CODE
		AND MAST.[STATUS] = 1
	
	SELECT DETL1.TRAN_ID, DETL1.INS_HOLDER_TYPE, DETL1.PCT AS PREMIUM_VALUE, 0 AS [SOURCE], 0 AS APPLY_MODE, MAST.INS_COMP_ID, CAST(1 AS BIT) IS_DISTRIBUTIVE
	FROM @SEC_MAST MAST
		INNER JOIN SECONDARY_INSURANCE_PREMIUM_RATE_DETL1 DETL1 ON MAST.TRAN_ID = DETL1.ADDITIONAL_SECONDARY_INSURANCE_MAST_ID
	UNION
	SELECT DETL2.TRAN_ID, DETL2.INS_HOLDER_TYPE, DETL2.MODE_VALUE AS PREMIUM_VALUE, DETL2.[SOURCE], DETL2.APPLY_MODE, MAST.INS_COMP_ID, CAST(0 AS BIT) IS_DISTRIBUTIVE
	FROM @SEC_MAST MAST
		INNER JOIN SECONDARY_INSURANCE_PREMIUM_RATE_DETL2 DETL2 ON MAST.TRAN_ID = DETL2.ADDITIONAL_SECONDARY_INSURANCE_MAST_ID

	--RELATION
	SELECT RELATION_CODE,RELATION_NAME,GENDER_CODE, RELATION_CAT FROM RELATION
END
--GO
--EXEC USP_CBS_LoanDisbursement_Get_InsuranceParameters '30','001'

