CREATE  PROCEDURE USP_CBS_TellerTransaction_Get_AcGroupList
(
	@INPUT VARCHAR(100)
)
AS
BEGIN

	SELECT AC_GROUP_CODE,AC_GROUP_NAME,AC_TYPE_SUB_TYPE_CODE
	FROM(
		SELECT AC_GROUP_CODE,AC_GROUP_NAME,AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE APPROVED='YES' AND AC_TYPE_CODE='03'	
		UNION ALL 
		SELECT AC_GROUP_CODE,AC_GROUP_NAME,AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE APPROVED='YES' AND AC_TYPE_CODE='04' AND AC_TYPE_SUB_TYPE_CODE='0401'
	)AS AG
	WHERE AG.AC_GROUP_NAME LIKE @INPUT+'%' OR AG.AC_GROUP_CODE=@INPUT

END