CREATE  PROCEDURE USP_CBS_TellerTransaction_Get_GeneralInformation
AS
BEGIN
	SELECT AC_GROUP_CODE,AC_GROUP_NAME,AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE APPROVED='YES' AND AC_TYPE_CODE='03'	UNION ALL SELECT AC_GROUP_CODE,AC_GROUP_NAME,AC_TYPE_SUB_TYPE_CODE FROM AC_GROUP WHERE APPROVED='YES' AND AC_TYPE_CODE='04' AND AC_TYPE_SUB_TYPE_CODE='0401';
	SELECT TRAN_ID, IDENTITY_TYPE_NAME FROM IDENTITY_TYPE WHERE TRAN_ID IN ('1','2','3','5','6','12') AND [STATUS] = 1 ORDER BY DISP_SEQ
	SELECT OP_CODE,OP_DESC FROM OPERATION_LIST WHERE OP_CODE NOT IN ('02','03','04','05');
	SELECT GENDER_CODE, GENDER_NAME FROM GENDER;
	SELECT OCCUPATION_CODE, OCCUPATION_NAME FROM OCCUPATION;
END
--GO
--EXEC USP_CBS_TellerTransaction_Get_GeneralInformation


