CREATE  PROC USP_CBS_TellerTransaction_Get_MemberIdentityDetail
(
    @CUSTOMER_CODE VARCHAR(50),
    @CONDUCTOR_IDENTITY_TYPE_ID INT,
    @TYPE VARCHAR(50)=''
)
AS
BEGIN
    IF @TYPE='DOC'
    BEGIN
        SELECT TOP 1 IDENTITY_TYPE_ID, CD.DOC_GUID,MIME_TYPE,FILE_EXTENSION FROM  CUSTOMER_IDENTITY CI
                                    INNER JOIN CUSTOMER_IDENTITY_DOC CD ON CI.TRAN_ID=CD.CUSTOMER_IDENTITY_ID 
                                    INNER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID=CI.IDENTITY_TYPE_ID
                                    WHERE CUSTOMER_CODE = @CUSTOMER_CODE AND CI.IDENTITY_TYPE_ID=@CONDUCTOR_IDENTITY_TYPE_ID
                                    AND CI.STATUS=1 ORDER BY CD.TRAN_ID DESC
    END
    ELSE
    BEGIN
        IF @CONDUCTOR_IDENTITY_TYPE_ID = '5'
	    BEGIN 
	    SELECT TOP 1 CI.CUSTOMER_CODE ,
                            CI.IDENTITY_TYPE_ID CONDUCTOR_IDENTITY_TYPE_ID ,
                            ISNULL(CI.IDENTITY_NO,'') CONDUCTOR_IDENTITY_NO , 
                            ISNULL(CONVERT(VARCHAR(10), CI.ISSUE_DATE, 121),'') CONDUCTOR_IDENTITY_ISSUE_DATE ,
                            ISNULL(DT.NEP_DATE,'') CONDUCTOR_IDENTITY_ISSUE_DATE_NEP , 
                            ISNULL(CONVERT(VARCHAR(10), CI.[EXPIRY_DATE], 121),'') CONDUCTOR_IDENTITY_EXPIRY_DATE,
                             ISNULL(DT1.NEP_DATE,'') CONDUCTOR_IDENTITY_EXPIRY_DATE_NEP,
                            ISNULL((CASE WHEN (CI.IDENTITY_TYPE_ID='1' OR CI.IDENTITY_TYPE_ID='3') THEN DI.DISTRICT_NAME ELSE LB.LOCAL_BODY_NAME END),'') AS ISSUE_PLACE
                            FROM CUSTOMER_MAST CM
                                INNER JOIN CUSTOMER_IDENTITY CI ON CI.CUSTOMER_CODE = CM.CUSTOMER_CODE AND CI.IDENTITY_TYPE_ID =@CONDUCTOR_IDENTITY_TYPE_ID AND CI.STATUS=1
                                INNER JOIN DATE_TABLE DT ON DT.ENG_DATE = CI.ISSUE_DATE
                                INNER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID=CI.IDENTITY_TYPE_ID AND IT.STATUS=1
                                INNER JOIN IDENTITY_TYPE_ISSUE_OFFICE_TYPE OT ON IT.ISSUE_OFFICE_TYPE_ID=OT.TRAN_ID AND OT.STATUS=1
                                INNER JOIN LOCAL_BODY LB ON LB.LOCAL_BODY_CODE=CI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE
                                INNER JOIN DISTRICT DI ON DI.DISTRICT_CODE=LB.DISTRICT_CODE
                                INNER JOIN STATE ST ON ST.TRAN_ID=DI.STATE_ID
                                LEFT OUTER JOIN DATE_TABLE DT1 ON DT1.ENG_DATE = CI.[EXPIRY_DATE]
                            WHERE CI.CUSTOMER_CODE =@CUSTOMER_CODE
	    END
	    ELSE IF @CONDUCTOR_IDENTITY_TYPE_ID = '6'
	    BEGIN 
	    SELECT TOP 1 CI.CUSTOMER_CODE ,
                            CI.IDENTITY_TYPE_ID CONDUCTOR_IDENTITY_TYPE_ID ,
                            ISNULL(CI.IDENTITY_NO,'') CONDUCTOR_IDENTITY_NO , 
                            ISNULL(CONVERT(VARCHAR(10), CI.ISSUE_DATE, 121),'') CONDUCTOR_IDENTITY_ISSUE_DATE , 
                            ISNULL(DT.NEP_DATE,'') CONDUCTOR_IDENTITY_ISSUE_DATE_NEP , 
                            ISNULL(CONVERT(VARCHAR(10), CI.[EXPIRY_DATE], 121),'') CONDUCTOR_IDENTITY_EXPIRY_DATE,
                            ISNULL(DT1.NEP_DATE,'') CONDUCTOR_IDENTITY_EXPIRY_DATE_NEP,
                            '' ISSUE_PLACE
                            FROM CUSTOMER_MAST CM
                                INNER JOIN CUSTOMER_IDENTITY CI ON CI.CUSTOMER_CODE = CM.CUSTOMER_CODE AND CI.IDENTITY_TYPE_ID =@CONDUCTOR_IDENTITY_TYPE_ID AND CI.STATUS=1
                                INNER JOIN DATE_TABLE DT ON DT.ENG_DATE = CI.ISSUE_DATE
                                INNER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID=CI.IDENTITY_TYPE_ID AND IT.STATUS=1
                                LEFT OUTER JOIN DATE_TABLE DT1 ON DT1.ENG_DATE = CI.[EXPIRY_DATE]
                            WHERE CI.CUSTOMER_CODE =@CUSTOMER_CODE
	    END
	    ELSE IF @CONDUCTOR_IDENTITY_TYPE_ID = '12'
	    BEGIN 
	    SELECT TOP 1 CI.CUSTOMER_CODE ,
                            CI.IDENTITY_TYPE_ID CONDUCTOR_IDENTITY_TYPE_ID ,
                            ISNULL(CI.IDENTITY_NO,'') CONDUCTOR_IDENTITY_NO , 
                            ISNULL(CONVERT(VARCHAR(10), CI.ISSUE_DATE, 121),'') CONDUCTOR_IDENTITY_ISSUE_DATE ,
                            ISNULL(DT.NEP_DATE,'') CONDUCTOR_IDENTITY_ISSUE_DATE_NEP , 
                            ISNULL(CONVERT(VARCHAR(10), CI.[EXPIRY_DATE], 121),'') CONDUCTOR_IDENTITY_EXPIRY_DATE,
                            ISNULL(DT1.NEP_DATE,'') CONDUCTOR_IDENTITY_EXPIRY_DATE_NEP,
                            '' ISSUE_PLACE
                            FROM CUSTOMER_MAST CM
                                INNER JOIN CUSTOMER_IDENTITY CI ON CI.CUSTOMER_CODE = CM.CUSTOMER_CODE AND CI.IDENTITY_TYPE_ID =@CONDUCTOR_IDENTITY_TYPE_ID AND CI.STATUS=1
                                INNER JOIN DATE_TABLE DT ON DT.ENG_DATE = CI.ISSUE_DATE
                                INNER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID=CI.IDENTITY_TYPE_ID AND IT.STATUS=1
                                LEFT OUTER JOIN DATE_TABLE DT1 ON DT1.ENG_DATE = CI.[EXPIRY_DATE]
                            WHERE CI.CUSTOMER_CODE =@CUSTOMER_CODE
	    END
	    ELSE
	    BEGIN
	    SELECT TOP 1 CI.CUSTOMER_CODE ,
                            CI.IDENTITY_TYPE_ID CONDUCTOR_IDENTITY_TYPE_ID ,
                            ISNULL(CI.IDENTITY_NO,'') CONDUCTOR_IDENTITY_NO , 
                            ISNULL(CONVERT(VARCHAR(10), CI.ISSUE_DATE, 121),'') CONDUCTOR_IDENTITY_ISSUE_DATE ,
                            ISNULL(DT.NEP_DATE,'') CONDUCTOR_IDENTITY_ISSUE_DATE_NEP , 
                            ISNULL(CONVERT(VARCHAR(10), CI.[EXPIRY_DATE], 121),'') CONDUCTOR_IDENTITY_EXPIRY_DATE,
                            ISNULL(DT1.NEP_DATE,'') CONDUCTOR_IDENTITY_EXPIRY_DATE_NEP,
                            ISNULL((CASE WHEN (CI.IDENTITY_TYPE_ID='1' OR CI.IDENTITY_TYPE_ID='3') THEN DI.DISTRICT_NAME ELSE ST.STATE_NAME END),'') AS ISSUE_PLACE
                            FROM CUSTOMER_MAST CM
                                INNER JOIN CUSTOMER_IDENTITY CI ON CI.CUSTOMER_CODE = CM.CUSTOMER_CODE AND CI.IDENTITY_TYPE_ID =@CONDUCTOR_IDENTITY_TYPE_ID AND CI.STATUS=1
                                INNER JOIN DATE_TABLE DT ON DT.ENG_DATE = CI.ISSUE_DATE
                                INNER JOIN IDENTITY_TYPE IT ON IT.TRAN_ID=CI.IDENTITY_TYPE_ID AND IT.STATUS=1
                                INNER JOIN IDENTITY_TYPE_ISSUE_OFFICE_TYPE OT ON IT.ISSUE_OFFICE_TYPE_ID=OT.TRAN_ID AND OT.STATUS=1
                                INNER JOIN LOCAL_BODY LB ON LB.DISTRICT_CODE=CI.ISSUE_AUTHORITY_OFFICE_TYPE_CODE
                                INNER JOIN DISTRICT DI ON DI.DISTRICT_CODE=LB.DISTRICT_CODE
                                INNER JOIN STATE ST ON ST.TRAN_ID=DI.STATE_ID
                                LEFT OUTER JOIN DATE_TABLE DT1 ON DT1.ENG_DATE = CI.[EXPIRY_DATE]
                            WHERE CI.CUSTOMER_CODE =@CUSTOMER_CODE
	    END

    END
    
END
--GO
--EXEC USP_CBS_TellerTransaction_Get_MemberIdentityDetail
--@CUSTOMER_CODE='001000017',@CONDUCTOR_IDENTITY_TYPE_ID=1,@TYPE='DOC'